---
title: "KidsAIR: ambient data"
author: "Ethan Walker"
date: "Started 30 March 2020, Updated 30 April 2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE, 
                      include = TRUE, warning = FALSE, message = FALSE,
                      fig.height = 6, fig.width = 8)
```

```{r, message=FALSE}
library(tidyverse)
library(readxl)
library(naniar)
library(lubridate)
library(broom)
library(broom.mixed)
library(zoo)
library(lme4)
library(lmerTest)
library(ggmap)
library(maps)
library(tigris)
jv_palette <- c("#330099","#CC0066","#FF6633", 
                 "#0099CC", "#FF9900","#CC6633",
                  "#FF3366", "#33CC99", "#33999")
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", 
               "#0072B2", "#D55E00", "#CC79A7")
```

```{r}
# Load data
file_path <- c("C:/Users/ethan.walker/Box/Ethan Walker UM/R/KidsAIR/")


# WMT homes now geocoded
# Instead of zip location, pull home lat/lon from wmt_addresses.rmd and use below
wmt_geocoded <- addresses_geocoded %>% 
  mutate(lat_home = lat,
         long_home = lon,
         home = Home) %>% 
  select(home, lat_home, long_home)

wmt_zipcodes <- read_csv(paste0(file_path, "Input/WMT/wmt_zipcodes.csv")) %>% 
  rename_all(tolower)


nn_zipcodes <- read_csv(paste0(file_path, "Input/NN/nn_zipcodes.csv")) %>% 
  rename_all(tolower)


ak_zipcodes <- read_csv(paste0(file_path, "Input/AK/ak_zipcodes.csv")) %>% 
  rename_all(tolower)


# Zipcode data from: http://download.geonames.org/export/dump/ 
us_zipcodes <- read_tsv(paste0(file_path, "Input/us_zipcodes/us_zipcodes.txt"), 
                        col_names = c("country", "zip", "city", "state",
                                      "state_abbr", "trash1", "trash2", "trash3", 
                                      "trash4", "lat", "long", "trash5")) %>% 
  select(-trash1:-trash4, -trash5)


wmt_map <- map_data("state") %>% 
  filter(region == "montana" | region == "idaho")


nn_map <- map_data("state") %>% 
  filter(region == "arizona" | region == "utah" |
         region == "new mexico" | region == "colorado")


ak_map <- map_data("world") %>% 
  filter(subregion == "Alaska") %>% 
  filter(long < 0)


# Weather data and stations comes from the National Climatic Data Center:
# https://www7.ncdc.noaa.gov/CDO/cdoselect.cmd?datasetabbv=GSOD&countryabbv=&georegionabbv=
us_temp_stations <- read_table(paste0(file_path, "Input/ambient/temp_station_list.txt"), skip = 20,
                            col_names = c("station", "wban", "station_names",
                                          "country", "state", "call", "lat",
                                          "long", "elevation", "begin_date",
                                          "end_date")) %>% 
  filter(country == "US") %>% 
  mutate(lat = as.numeric(lat),
         long = as.numeric(long),
         elevation = as.numeric(elevation),
         begin_date = ymd(begin_date),
         end_date = ymd(end_date))


# Ambient PM data comes from EPA Air Quality Monitors:
# https://epa.maps.arcgis.com/apps/webappviewer/index.html?id=5f239fd3e72f424f98ef3d5def547eb5&extent=-146.2334,13.1913,-46.3896,56.5319 
pm_stations <- read_xlsx(paste0(file_path, "Input/ambient/pm_station_list.xlsx"))
```


```{r}
# Mapping zipcodes, weather stations, pm stations - WMT
# These steps are repeated for NN and AK below

# Zipcodes for each KidsAIR study home were downloaded from the server
# If there was no zipcode provided, the zipcode from the nearest town was used
# Here, WMT zipcodes are joined with the US zipcode data
# This step gives lat/long coordinates for each WMT zipcode
wmt_zipcodes_new <- wmt_zipcodes %>% 
  left_join(us_zipcodes, by = "zip") %>% 
  left_join(wmt_geocoded, by = "home")


# US weather stations list was filtered for MT and ID locations
# Stations were further filtered for data availability during study dates
# Temp data was joined with WMT zipcode data
# Lat/long differences were calculated
# The weather station closest to each zipcode was selected and plotted below
wmt_temp_stations <- us_temp_stations %>% 
  filter(state == "MT" | state == "ID") %>% 
  mutate(lat_temp = lat,
         long_temp = long) %>% 
  filter(begin_date < "2014-06-01") %>% 
  filter(end_date > "2020-03-21") %>% 
  #distinct(station, .keep_all = TRUE) %>% 
  full_join(wmt_zipcodes_new, by = "country") %>% 
  mutate(lat_diff = abs(lat_home - lat_temp),
         long_diff = abs(long_home - long_temp),
         sum_diff = lat_diff + long_diff,
         area = "WMT") %>% 
  arrange(home, sum_diff) %>% 
  distinct(home, .keep_all = TRUE) %>% 
  mutate(station_char = factor(station_names, 
                               levels = c("BERT MOONEY AIRPORT", "GLACIER PARK INTERNATIONAL AI",
                                          "GOLF (SIMMS)", "HELENA REGIONAL AIRPORT",
                                          "LEMHI COUNTY AIRPORT", "MISSOULA INTERNATIONAL AIRPOR",
                                          "MULLAN PASS"),
                               labels = c("bertmooneyairport", "glacierparkairport",
                                          "golfsimms", "helenaairport",
                                          "lemhicountyairport", "missoulaairport",
                                          "mullanpass"))) %>% 
  select(home, area, station, station_char, zip, elevation, lat_temp, long_temp, lat_home, 
         long_home, station_names)


# Here, zipcodes and weather stations are plotted on a map
# Colors match for weather stations and zips that are closest together
wmt_plot <- wmt_zipcodes_new %>% 
  ggplot() +
    geom_polygon(data=wmt_map, aes(x=long, y=lat, group=group), 
               colour="black", fill = "azure", size = 1.2) +
    geom_point(data=wmt_temp_stations, 
             aes(long_home, lat_home, color = station_names), size = 3) +
    geom_point(data=wmt_temp_stations, 
             aes(long_temp, lat_temp, color = station_names), 
             shape = 15, size = 3) +
    theme_void() +
    labs(title = "WMT zipcodes and weather stations", color = "Weather station") +
    scale_color_manual(values = cbPalette)
wmt_plot




# Lat/long coordinates for PM stations was manually extracted from the EPA site
# Similar to weather stations, each WMT zipcode was matched with the closest PM monitor
wmt_pm_stations <- pm_stations %>% 
  filter(area == "WMT") %>% 
  full_join(wmt_zipcodes_new, by = "country") %>% 
  mutate(lat_diff = abs(lat_home - lat_pm),
         long_diff = abs(long_home - long_pm),
         sum_diff = lat_diff + long_diff) %>% 
  arrange(home, sum_diff) %>% 
  distinct(home, .keep_all = TRUE) %>% 
  select(home, area, local_site, zip, lat_pm, long_pm, lat_home, long_home)


# PM monitors and zipcodes are plotted below
# Colors match for PM monitors and zips that are closest together
wmt_plot <- wmt_zipcodes_new %>% 
  ggplot() +
    geom_polygon(data=wmt_map, aes(x=long, y=lat, group=group), 
               colour="black", fill = "azure", size = 1.2) +
    geom_point(data=wmt_pm_stations, 
             aes(long_home, lat_home, color = local_site), size = 3) +
    geom_point(data=wmt_pm_stations, 
             aes(long_pm, lat_pm, color = local_site), 
             shape = 15, size = 3) +
    theme_void() +
    labs(title = "WMT zipcodes and PM monitors", color = "EPA Monitor") +
    scale_color_manual(values = cbPalette)
wmt_plot
```


```{r}
# Mapping zipcodes, weather stations, pm stations - NN

nn_zipcodes_new <- nn_zipcodes %>% 
  left_join(us_zipcodes, by = "zip") %>% 
  mutate(home = gsub(home, pattern = "_", replacement = ""),
         home = gsub(home, pattern = " ", replacement = "")) %>%
  mutate(lat_home = lat,
         long_home = long)


#Plot temp stations
nn_temp_stations <- us_temp_stations %>% 
  filter(state == "AZ" | state == "NM" |
         state == "UT" | state == "CO") %>% 
  mutate(lat_temp = lat,
         long_temp = long) %>% 
  filter(begin_date < "2014-06-01") %>% 
  filter(end_date > "2020-03-21") %>% 
  #distinct(station, .keep_all = TRUE) %>% 
  full_join(nn_zipcodes_new, by = "country") %>% 
  mutate(lat_diff = abs(lat_home - lat_temp),
         long_diff = abs(long_home - long_temp),
         sum_diff = lat_diff + long_diff,
         area = "NN") %>% 
  arrange(home, sum_diff) %>% 
  distinct(home, .keep_all = TRUE) %>% 
  filter(!is.na(home)) %>% 
  mutate(station_char = factor(station_names, 
                               levels = c("FOUR CORNERS REGIONAL ARPT", "GALLUP MUNICIPAL AIRPORT",
                                          "PAGE MUNICIPAL AIRPORT", "WINDOW ROCK AIRPORT",
                                          "WINSLOW-LINDBERGH REGIONAL AI"),
                               labels = c("fourcornersairport", "gallopairport",
                                          "pageairport", "windowrockairport",
                                          "winslowlindberghairport"))) %>% 
  select(home, area, station, station_char, zip, elevation, lat_temp, long_temp, lat_home, 
         long_home, station_names)



nn_plot_temp_stations <- wmt_zipcodes_new %>% 
  ggplot() +
    geom_polygon(data=nn_map, aes(x=long, y=lat, group=group), 
               colour="black", fill = "azure", size = 1.2) +
    geom_point(data=nn_temp_stations, 
             aes(long_home, lat_home, color = station_names), size = 3) +
    geom_point(data=nn_temp_stations, 
             aes(long_temp, lat_temp, color = station_names), 
             shape = 15, size = 3) +
    theme_void() +
    labs(title = "NN zipcodes and weather stations", color = "Weather station") +
    scale_color_manual(values = cbPalette)
nn_plot_temp_stations



#Plot PM stations
nn_pm_stations <- pm_stations %>% 
  filter(area == "NN") %>% 
  full_join(nn_zipcodes_new, by = "country") %>% 
  mutate(lat_diff = abs(lat_home - lat_pm),
         long_diff = abs(long_home - long_pm),
         sum_diff = lat_diff + long_diff) %>% 
  arrange(home, sum_diff) %>% 
  distinct(home, .keep_all = TRUE) %>% 
  filter(!is.na(home)) %>% 
  select(home, area, local_site, zip, lat_pm, long_pm, lat_home, long_home)


nn_plot <- nn_zipcodes_new %>% 
  ggplot() +
    geom_polygon(data=nn_map, aes(x=long, y=lat, group=group), 
               colour="black", fill = "azure", size = 1.2) +
    geom_point(data=nn_pm_stations, 
             aes(long_home, lat_home, color = local_site), size = 3) +
    geom_point(data=nn_pm_stations, 
             aes(long_pm, lat_pm, color = local_site), 
             shape = 15, size = 3) +
    theme_void() +
    labs(title = "NN zipcodes and PM monitors", color = "EPA monitor") +
    scale_color_manual(values = cbPalette)
nn_plot
```


```{r}
# Mapping zipcodes, weather stations, pm stations - WMT

ak_zipcodes_new <- ak_zipcodes %>% 
  left_join(us_zipcodes, by = "zip") %>% 
  mutate(home = gsub(home, pattern = "_", replacement = ""),
         home = gsub(home, pattern = " ", replacement = "")) %>%
  mutate(lat_home = lat,
         long_home = long)


#Plot temp stations
ak_temp_stations <- us_temp_stations %>% 
  filter(state == "AK") %>% 
  mutate(lat_temp = lat,
         long_temp = long) %>% 
  filter(begin_date < "2014-06-01") %>% 
  filter(end_date > "2020-03-21") %>% 
  #distinct(station, .keep_all = TRUE) %>% 
  full_join(ak_zipcodes_new, by = "country") %>% 
  mutate(lat_diff = abs(lat_home - lat_temp),
         long_diff = abs(long_home - long_temp),
         sum_diff = lat_diff + long_diff,
         area = "AK") %>% 
  arrange(home, sum_diff) %>% 
  distinct(home, .keep_all = TRUE) %>% 
  mutate(station_char = factor(station_names, 
                               levels = c("KIPNUK AIRPORT", "BETHEL AIRPORT",
                                          "QUINHAGAK AIRPORT"),
                               labels = c("kipnukairport", "bethelairport",
                                          "quinhagakairport"))) %>% 
  select(home, area, station, station_char, zip, elevation, lat_temp, long_temp, lat_home, 
         long_home, station_names)


zipcodes_map <- wmt_zipcodes_new %>% 
  ggplot() +
    geom_polygon(data=ak_map, aes(x=long, y=lat, group=group), 
               colour="black", fill = "azure", size = 1.2) +
    geom_point(data=ak_temp_stations, 
             aes(long_home, lat_home, color = station_names), size = 5) +
    geom_point(data=ak_temp_stations, 
             aes(long_temp, lat_temp, color = station_names), 
             shape = 15, size = 5) +
    theme_void() +
    labs(title = "AK zipcodes and weather stations", color = "Weather station") +
    scale_color_manual(values = cbPalette) 
zipcodes_map



#Plot PM stations
ak_pm_stations <- pm_stations %>% 
  filter(area == "AK") %>% 
  full_join(ak_zipcodes_new, by = "country") %>% 
  mutate(lat_diff = abs(lat_home - lat_pm),
         long_diff = abs(long_home - long_pm),
         sum_diff = lat_diff + long_diff) %>% 
  arrange(home, sum_diff) %>% 
  distinct(home, .keep_all = TRUE) %>% 
  filter(!is.na(home)) %>% 
  select(home, area, local_site, zip, lat_pm, long_pm, lat_home, long_home)


ak_plot <- ak_zipcodes_new %>% 
  ggplot() +
    geom_polygon(data=ak_map, aes(x=long, y=lat, group=group), 
               colour="black", fill = "azure", size = 1.2) +
    geom_point(data=ak_pm_stations, 
             aes(long_home, lat_home, color = local_site), size = 5) +
    geom_point(data=ak_pm_stations, 
             aes(long_pm, lat_pm, color = local_site), 
             shape = 15, size = 5) +
    theme_void() +
    labs(title = "AK zipcodes and PM monitors", color = "EPA monitor") +
    scale_color_manual(values = cbPalette)
ak_plot
```


```{r, echo=FALSE, include=FALSE, eval=FALSE}
# Compile temperature data and filter for closest stations

# Read in ambient weather files and bind together
list_files <- list.files(paste0(file_path, "Input/ambient/temp_data"))
# Set working directory and load files in list; extract file name and add as column
## run next 10 lines together
setwd(paste0(file_path, "Input/ambient/temp_data")) # set new working directory
initial_data = tibble(file_name = list_files) %>% # use list of files from above
  mutate(save_data = lapply(file_name, read_csv, 
                            col_names = c("station", "wban", "temp_date",
                                          "mean_temp", "t1", "mean_dewp", "t2",
                                          "t3", "t4", "mean_pressure", "t5",
                                          "mean_visib_miles", "t6", "mean_wind_knots",
                                          "t7", "max_wind_knots", "t8", "max_temp",
                                          "min_temp", "precip", "snow_depth", "t9"))) %>%
  unnest(save_data)


# Format combined file from above
temp_data <- initial_data %>% 
  filter(!is.na(t1)) %>% 
  separate(file_name, c("area", "station_char"), sep = "_") %>%
  mutate(temp_date = ymd(temp_date),
         mean_temp = as.numeric(mean_temp),
         mean_dewp = as.numeric(mean_dewp),
         mean_pressure = as.numeric(mean_pressure),
         mean_visib_miles = as.numeric(mean_visib_miles),
         mean_wind_knots = as.numeric(mean_wind_knots),
         max_wind_knots = as.numeric(max_wind_knots)) %>% 
  select(station_char, station, temp_date, mean_temp, mean_dewp,
         mean_pressure, mean_visib_miles, mean_wind_knots, max_wind_knots) %>% 
  replace_with_na_all(condition = ~.x %in% c(9999.9, 999.9))


# Bind together weather station names from each location
temp_stations <- rbind(wmt_temp_stations, nn_temp_stations, ak_temp_stations)


# Join weather data with station names
temp_data_joined <- temp_data %>% 
  left_join(temp_stations, by = c("station", "station_char")) 


#write_rds(temp_data_joined, paste0(file_path, "Output/kids_temp_data.rds"))
#write_csv(temp_data_joined, paste0(file_path, "Output/kids_temp_data.csv"))

kids_temp_data <- read_rds(paste0(file_path, "Output/kids_temp_data.rds"))
```


```{r, echo=FALSE, include=FALSE, eval=FALSE}
# Compile PM data and filter for correct dates/variables

pm_stations <- read_xlsx(paste0(file_path, "Input/ambient/pm_station_list.xlsx"))

# Read in ambient PM files and bind together
list_files <- list.files(paste0(file_path, "Input/ambient/pm_data"))
# Set working directory and load files in list; extract file name and add as column
## run next 28 lines together
setwd(paste0(file_path, "Input/ambient/pm_data")) # set new working directory
initial_data = tibble(file_name = list_files) %>% # use list of files from above
   mutate(save_data = lapply(file_name, read_csv, skip = 1,
                            col_names = c("t1", "t2", "t3", "t4", "parameter",
                                          "pm_lat", "pm_long", "t5", "parameter_name",
                                          "duration", "pollutant", "amb_pm_date",
                                          "year", "t6", "units", "t7", "t8", "t9",
                                          "t10", "t11", "mean_pollution", "t12",
                                          "t13", "t14", "aqi", "t15", "t16",
                                          "t17", "t18", "t19", "local_site",
                                          "t20", "t21", "t22"),
                            col_types = list(col_character(), col_character(), 
                                          col_character(), col_character(), 
                                          col_character(), col_double(), 
                                          col_double(), col_character(), 
                                          col_character(), col_character(), 
                                          col_character(), col_character(), 
                                          col_character(), col_character(), 
                                          col_character(), col_character(), 
                                          col_character(), col_character(),
                                          col_character(), col_character(), 
                                          col_double(), col_character(),
                                          col_character(), col_character(), 
                                          col_character(), col_character(), 
                                          col_character(), col_character(), 
                                          col_character(), col_character(), 
                                          col_character(), col_character(), 
                                          col_character(), col_character()))) %>%
  unnest(save_data)


# Format combined file from above
pm_data <- initial_data %>% 
  filter(t1 != "State Code") %>% 
  filter(pollutant == "PM25 24-hour 2012") %>% 
  select(local_site, pollutant, amb_pm_date, mean_pollution) %>% 
  mutate(amb_pm_24hr = as.numeric(mean_pollution),
         date1 = ymd(amb_pm_date),
         date2 = mdy(amb_pm_date)) %>% 
  unite(amb_pm_date, c("date1", "date2"), sep = "") %>% 
  separate(amb_pm_date, c("trash", "amb_pm_date"), sep = "NA") %>% 
  unite(amb_pm_date, c("trash", "amb_pm_date"), sep = "") %>% 
  group_by(local_site, amb_pm_date) %>% 
  distinct(pollutant, .keep_all = TRUE) %>% 
  select(local_site, amb_pm_date, amb_pm_24hr) %>% 
  arrange(local_site, amb_pm_date)
  

# Bind together PM monitor names from each location
pm_stations <- rbind(wmt_pm_stations, nn_pm_stations, ak_pm_stations)


# Join PM data with monitor names
pm_data_joined <- pm_data %>% 
  left_join(pm_stations, by = "local_site")


#write_rds(pm_data_joined, paste0(file_path, "Output/kids_amb_pm_data.rds"))
#write_csv(pm_data_joined, paste0(file_path, "Output/kids_amb_pm_data.csv"))

kids_amb_pm_data <- read_rds(paste0(file_path, "Output/kids_amb_pm_data.rds"))
```


```{r, echo=FALSE, include=FALSE, eval=FALSE}
# Add new variables to pm/temp datasets
file_path <- c("C:/Users/ethan.walker/Box/Ethan Walker UM/R/KidsAIR/")


kids_amb_pm_data <- read_rds(paste0(file_path, "Output/kids_amb_pm_data.rds"))
kids_temp_data <- read_rds(paste0(file_path, "Output/kids_temp_data.rds"))


# PM data
kids_amb_pm_data_new <- kids_amb_pm_data %>% 
  arrange(area, local_site, amb_pm_date, zip, home) %>% 
  group_by(area, local_site, zip, home) %>% 
  mutate(amb_pm_24hr_lag1 = lag(amb_pm_24hr),
         amb_pm_24hr_lag2 = lag(amb_pm_24hr, 2),
         amb_pm_24hr_lag3 = lag(amb_pm_24hr, 3),
         amb_pm_roll_mean_2day = rollmean(amb_pm_24hr, 2, fill = NA, align = "right"),
         amb_pm_roll_mean_3day = rollmean(amb_pm_24hr, 3, fill = NA, align = "right"),
         amb_pm_roll_mean_4day = rollmean(amb_pm_24hr, 4, fill = NA, align = "right")) %>% 
  ungroup()

#write_rds(kids_amb_pm_data_new, paste0(file_path, "Output/kids_amb_pm_data_new.rds"))
#write_csv(kids_amb_pm_data_new, paste0(file_path, "Output/kids_amb_pm_data_new.csv"))


# Temp data
kids_amb_temp_data_new <- kids_temp_data %>% 
  arrange(area, station, temp_date, zip, home) %>% 
  group_by(area, station, zip, home) %>% 
  mutate(mean_temp_lag1 = lag(mean_temp),
         mean_temp_lag2 = lag(mean_temp, 2),
         mean_temp_lag3 = lag(mean_temp, 3),
         mean_temp_roll_2day = rollmean(mean_temp, 2, fill = NA, align = "right"),
         mean_temp_roll_3day = rollmean(mean_temp, 3, fill = NA, align = "right"),
         mean_temp_roll_4day = rollmean(mean_temp, 4, fill = NA, align = "right")) %>% 
  ungroup()

#write_rds(kids_amb_temp_data_new, paste0(file_path, "Output/kids_amb_temp_data_new.rds"))
#write_csv(kids_amb_temp_data_new, paste0(file_path, "Output/kids_amb_temp_data_new.csv"))
```


