---
title: "KidsAIR initial data work"
author: "Ethan Walker"
date: "Started 19 Nov 2019, Updated 5 Dec 2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
library(tidyverse)
library(readxl)
library(naniar)
library(lubridate)
library(zoo)
```

# Load, format, and save KidsAIR Dusttrack data
```{r}
##### Read in dusttrack .txt files (from WMT) #####

# List files
list_txt_files <- list.files("Input/WMT/dusttrack_txt_files")

# Set working directory and load files in list; extract file name and add as column
## run next 6 lines together
setwd("Input/WMT/dusttrack_txt_files")
initial_data = tibble(file_list = list_txt_files) %>%
  extract(file_list, "home_winter_id", remove = FALSE) %>%
  mutate(save_data = lapply(file_list, read_csv, skip = 28)) %>%
  unnest(save_data) %>%
  select(-file_list) 

# Format combined file from above; combine with other PM data below
wmt_pm_txt <- initial_data %>% 
  mutate(date = mdy(`MM/dd/yyyy`),
         time = `hh:mm:ss`,
         pm = as.numeric(`mg/m^3`),
         area = "WMT") %>% 
  unite("datetime", c("date", "time"), sep = " ", remove = FALSE) %>% 
  select(home_winter_id, datetime, date, time, pm, area)
  

##### Read in dusttrack .csv files (all areas) #####

### WMT ###
# List files
list_csv_files <- list.files("Input/WMT/dusttrack_csv_files")

# Set working directory and load files in list; extract file name and add as column
## run next 6 lines together
setwd("Input/WMT/dusttrack_csv_files")
initial_data = tibble(file_list = list_csv_files) %>%
  extract(file_list, "home_winter_id", remove = FALSE) %>%
  mutate(save_data = lapply(file_list, read_csv)) %>%
  unnest(save_data) %>%
  select(-file_list) 

# Format combined file from above; combine with other PM data below
wmt_pm_csv <- initial_data %>% 
  mutate(date = mdy(Date),
         time = Time,
         pm = as.numeric(AEROSOL),
         area = "WMT") %>% 
  unite("datetime", c("date", "time"), sep = " ", remove = FALSE) %>% 
  select(home_winter_id, datetime, date, time, pm, area) %>% 
  filter(!is.na(pm))

### NN ###
# List files
list_csv_files <- list.files("Input/NN/dusttrack_csv_files")

# Set working directory and load files in list; extract file name and add as column
## run next 6 lines together
setwd("Input/NN/dusttrack_csv_files")
initial_data = tibble(file_list = list_csv_files) %>%
  extract(file_list, "home_winter_id", remove = FALSE) %>%
  mutate(save_data = lapply(file_list, read_csv)) %>%
  unnest(save_data) %>%
  select(-file_list) 

# Format combined file from above; combine with other PM data below
nn_pm_csv <- initial_data %>% 
  mutate(date = mdy(Date),
         time = Time,
         pm = as.numeric(AEROSOL),
         area = "NN") %>% 
  unite("datetime", c("date", "time"), sep = " ", remove = FALSE) %>% 
  select(home_winter_id, datetime, date, time, pm, area) %>% 
  filter(!is.na(pm))

### AK ###
# List files
list_csv_files <- list.files("Input/AK/dusttrack_csv_files")

# Set working directory and load files in list; extract file name and add as column
## run next 6 lines together
setwd("Input/AK/dusttrack_csv_files")
initial_data = tibble(file_list = list_csv_files) %>%
  extract(file_list, "home_winter_id", remove = FALSE) %>%
  mutate(save_data = lapply(file_list, read_csv)) %>%
  unnest(save_data) %>%
  select(-file_list) 

# Format combined file from above; combine with other PM data below
ak_pm_csv <- initial_data %>% 
  mutate(date = mdy(Date),
         time = Time,
         pm = as.numeric(AEROSOL),
         area = "AK") %>% 
  unite("datetime", c("date", "time"), sep = " ", remove = FALSE) %>% 
  select(home_winter_id, datetime, date, time, pm, area) %>% 
  filter(!is.na(pm))


##### Read in other dusttrack .csv files (WMT and NN) #####

### WMT ### 
# List files
list_other_files <- list.files("Input/WMT/dusttrack_other_files")

# Set working directory and load files in list; extract file name and add as column
## run next 6 lines together
setwd("Input/WMT/dusttrack_other_files")
initial_data = tibble(file_list = list_other_files) %>%
  extract(file_list, "home_winter_id", remove = FALSE) %>%
  mutate(save_data = lapply(file_list, read_csv)) %>%
  unnest(save_data) %>%
  select(-file_list) 

# Format combined file from above; combine with other PM data below
wmt_pm_other <- initial_data %>% 
  mutate(trash1 = `Instrument Name`,
         trash2 = `DustTrak II`) %>% 
  select(home_winter_id, trash1, trash2) %>% 
  group_by(home_winter_id) %>% 
  mutate(trash3 = if_else(trash1 == "Test Start Date" | trash1 == "Test Start Time", 
                              trash2, "NA"),
         trash4 = if_else(trash1 == "Test Start Date" | trash1 == "Test Start Time", 
                              trash1, "NA"),
         trash1 = as.numeric(trash1),
         trash1 = as.character(trash1),
         trash5 = if_else(trash3 != "NA", trash3, trash1)) %>% 
  filter(!is.na(trash5)) %>% 
  replace_with_na(replace = list(trash3 = "NA", trash4 = "NA")) %>% 
  spread(trash4, trash3) %>% 
  mutate(`Test Start Time` = lag(`Test Start Time`)) %>% 
  unite("datetime", `Test Start Date`:`Test Start Time`, sep = " ") %>%
  mutate(datetime = lead(datetime)) %>% 
  replace_with_na(replace = list(datetime = "NA NA")) %>% 
  mutate(datetime2 = first(datetime),
         datetime = mdy_hms(datetime2),
         trash1 = as.numeric(trash1)) %>% 
  filter(!is.na(trash1)) %>% 
  mutate(datetime2 = datetime + seconds(trash1),
         datetime2 = ymd_hms(datetime2)) %>% 
  separate(datetime2, into = c("date", "time"), sep = " ", remove = FALSE) %>% 
  mutate(pm = as.numeric(trash2),
         datetime = datetime2,
         area = "WMT") %>% 
  select(home_winter_id, datetime, date, time, pm, area) %>% 
  ungroup()


### NN ### 
# List files
list_other_files <- list.files("Input/NN/dusttrack_other_files")

# Set working directory and load files in list; extract file name and add as column
## run next 6 lines together
setwd("Input/NN/dusttrack_other_files")
initial_data = tibble(file_list = list_other_files) %>%
  extract(file_list, "home_winter_id", remove = FALSE) %>%
  mutate(save_data = lapply(file_list, read_csv)) %>%
  unnest(save_data) %>%
  select(-file_list) 

# Format combined file from above; combine with other PM data below
nn_pm_other <- initial_data %>% 
  mutate(trash1 = `Instrument Name`,
         trash2 = `DustTrak II`) %>% 
  select(home_winter_id, trash1, trash2) %>% 
  filter(!is.na(trash1)) %>% 
  group_by(home_winter_id) %>% 
  mutate(trash3 = if_else(trash1 == "Test Start Date" | trash1 == "Test Start Time", 
                              trash1, "NA"),
         trash4 = if_else(trash1 == "Test Start Date" | trash1 == "Test Start Time", 
                              trash2, "NA"),
         trash1 = as.numeric(trash1),
         trash1 = as.character(trash1),
         trash5 = if_else(trash3 != "NA", trash3, trash1)) %>% 
  replace_with_na(replace = list(trash3 = "NA", trash4 = "NA")) %>% 
  filter(!is.na(trash5)) %>% 
  spread(trash3, trash4) %>% 
  mutate(`Test Start Time` = lag(`Test Start Time`)) %>% 
  unite("datetime", `Test Start Date`:`Test Start Time`, sep = " ") %>%
  mutate(datetime = lead(datetime)) %>% 
  replace_with_na(replace = list(datetime = "NA NA")) %>% 
  mutate(datetime2 = first(datetime),
         datetime = mdy_hms(datetime2),
         trash1 = as.numeric(trash1)) %>% 
  filter(!is.na(trash1)) %>% 
  mutate(datetime2 = datetime + seconds(trash1),
         datetime2 = ymd_hms(datetime2)) %>% 
  separate(datetime2, into = c("date", "time"), sep = " ", remove = FALSE) %>% 
  mutate(pm = as.numeric(trash2),
         datetime = datetime2,
         area = "NN") %>% 
  select(home_winter_id, datetime, date, time, pm, area) %>% 
  ungroup() %>% 
  mutate(home_winter_id = if_else(home_winter_id == "220001" | home_winter_id == "220002",
                                  "22", home_winter_id),
         home_winter_id = if_else(home_winter_id == "550001" | home_winter_id == "550002",
                                  "55", home_winter_id),
         home_winter_id = if_else(home_winter_id == "810001" | home_winter_id == "810002",
                                  "81", home_winter_id))


##### Bind all files from above #####
kids_pm <- rbind(wmt_pm_csv, wmt_pm_txt, wmt_pm_other,
                nn_pm_csv, nn_pm_other,
                ak_pm_csv)


# Save pm dataset as RDS and CSV
write_rds(kids_pm, "Output/kids_pm_full.rds")
#write_csv(kids_pm, "Output/kids_pm_full.csv")

# Load data and clean up
kids_pm <- read_rds("Output/kids_pm_full.rds")
  
kids_pm_check <- kids_pm %>% 
  group_by(home_winter_id) %>% 
  summarise(obs = n()) %>% 
  ungroup()
  

ak_dt_home <- read_csv("Input/AK/ak_dt_home.csv")
nn_dt_home <- read_csv("Input/NN/nn_dt_home.csv")
wmt_dt_home <- read_csv("Input/WMT/wmt_dt_home.csv")

dt_home <- rbind(ak_dt_home, nn_dt_home, wmt_dt_home) %>% 
  rename_all(tolower) %>% 
  filter(!is.na(homewinterid)) %>% 
  mutate(home_winter_id = as.character(homewinterid)) %>% 
  left_join(kids_pm_check, by = "home_winter_id")


##### Add to new variables to Kids PM data #####
kids_pm_new <- kids_pm %>% 
  mutate(home_winter_id = as.character(home_winter_id),
         area = as.factor(area),
         pm_date = date,
         pm_time = time,
         pm_datetime = datetime,
         pm = as.numeric(pm)) %>% 
  select(home_winter_id, area, pm_date, pm_time, pm_datetime, pm) %>% 
  arrange(home_winter_id, pm_date) %>% 
  group_by(home_winter_id) %>% 
  # new variables summarizing pm2.5 within each home_winter_id
  mutate(pm_total_observations = n(),
         pm_total_summed = sum(pm),
         min_datetime = first(pm_datetime),
         max_datetime = last(pm_datetime),
         min_datetime = ymd_hms(min_datetime),
         max_datetime = ymd_hms(max_datetime),
         diff_datetime = interval(min_datetime, max_datetime),
         pm_total_days = diff_datetime/86400,
         pm_24hr_mean = pm_total_summed/pm_total_days,
         pm_rolling_24hr = rollsum(pm, 1440, fill = "extend", align = "right"),
         obs = row_number(),
         sampling_day = if_else(obs < 1441, 1, 0),
         sampling_day = if_else(obs < 2881 & obs > 1440, 2, sampling_day),
         sampling_day = if_else(obs < 4321 & obs > 2880, 3, sampling_day),
         sampling_day = if_else(obs < 5761 & obs > 4320, 4, sampling_day),
         sampling_day = if_else(obs < 7201 & obs > 5760, 5, sampling_day),
         sampling_day = if_else(obs < 8641 & obs > 7200, 6, sampling_day),
         sampling_day = if_else(obs < 10081 & obs > 8640, 7, sampling_day),
         sampling_day = if_else(obs > 10080, 8, sampling_day)) %>%
  group_by(home_winter_id, sampling_day) %>% 
  mutate(pm_24hr_daily = sum(pm),
         pm_24hr_daily_weighted = pm_24hr_daily*(1440/n()),
         pm_sampling_day = sampling_day) %>% 
  ungroup() %>% 
  select(-min_datetime, -max_datetime, -diff_datetime, -obs, -sampling_day) 


# Save pm dataset as RDS and CSV
write_rds(kids_pm_new, "Output/kids_pm_new.rds")
#write_csv(kids_pm_new, "Output/kids_pm_new.csv")
```


# Original code/files from Emily - save for future reference
```{r}
##### Load combined dusttrack files from Emily W #####
##### Compare these with the raw data pulled in above #####

## List sheets within the excel file
list_sheets_nn <- excel_sheets("Input/nn_kids_dusttrack_20191121.xlsx")
## Apply the read_xlsx function to each item in the sheet list
## Bind the items from each sheet into a single dataframe
pm_initial_nn <- data.frame(do.call("rbind", lapply(list_sheets_nn, read_xlsx, 
                                      path = "Input/nn_kids_dusttrack_20191121.xlsx"))) %>% 
  mutate(area = "NN")

list_sheets_wmt <- excel_sheets("Input/wmt_kids_dusttrack_20191121.xlsx")
pm_initial_wmt <- data.frame(do.call("rbind", lapply(list_sheets_wmt, read_xlsx, 
                                      path = "Input/wmt_kids_dusttrack_20191121.xlsx"))) %>% 
  mutate(area = "WMT")

# Bind data together from different study areas
pm_initial <- rbind(pm_initial_nm, pm_initial_wmt)

# Rename and create new variables
kids_pm <- pm_initial %>% 
  # separate time from incorrect/associated date
  separate(time, into = c("trash", "time"), sep = " ") %>% 
  # format/rename variables
  mutate(home_winter_id = as.factor(homeid),
         pm_date = ymd(date),
         pm_time = hms(time),
         pm = as.numeric(aerosol)) %>% 
  # new datetime variable
  unite(pm_datetime, c("date", "time"), sep = " ", remove = FALSE) %>% 
  select(home_winter_id, area, pm_date, pm_time, pm_datetime, pm) %>% 
  arrange(home_winter_id, pm_date) %>% 
  group_by(home_winter_id) %>% 
  # new variables summarizing pm2.5 within each home_winter_id
  mutate(pm_total_observations = n(),
         pm_total_summed = sum(pm),
         min_datetime = first(pm_datetime),
         max_datetime = last(pm_datetime),
         min_datetime = ymd_hms(min_datetime),
         max_datetime = ymd_hms(max_datetime),
         diff_datetime = interval(min_datetime, max_datetime),
         pm_total_days = diff_datetime/86400,
         pm_24hr_mean = pm_total_summed/pm_total_days,
         pm_rolling_24hr = rollsum(pm, 1440, fill = "extend", align = "right"),
         obs = row_number(),
         sampling_day = if_else(obs < 1441, 1, 0),
         sampling_day = if_else(obs < 2881 & obs > 1440, 2, sampling_day),
         sampling_day = if_else(obs < 4321 & obs > 2880, 3, sampling_day),
         sampling_day = if_else(obs < 5761 & obs > 4320, 4, sampling_day),
         sampling_day = if_else(obs < 7201 & obs > 5760, 5, sampling_day),
         sampling_day = if_else(obs < 8641 & obs > 7200, 6, sampling_day),
         sampling_day = if_else(obs < 10081 & obs > 8640, 7, sampling_day),
         sampling_day = if_else(obs > 10080, 8, sampling_day)) %>%
  group_by(home_winter_id, sampling_day) %>% 
  mutate(pm_24hr_daily = sum(pm),
         pm_24hr_daily_weighted = pm_24hr_daily*(1440/n()),
         pm_sampling_day = sampling_day) %>% 
  ungroup() %>% 
  select(-min_datetime, -max_datetime, -diff_datetime, -obs, -sampling_day) 

# Save pm dataset as RDS and CSV
write_rds(kids_pm, "Output/kids_pm.rds")
write_csv(kids_pm, "Output/kids_pm.csv")
```


# Load, format, and save fuel moisture content data
```{r}
# Load data
moisture_initial_wmt <- read_xlsx("Input/wmt_kids_moisture_20191122.xlsx")

kids_moisture <- moisture_initial_wmt %>% 
  # rename variables
  mutate(moisture_id = as.factor(ID),  
         home_winter_id = as.factor(HomeWinterID),
         moisture_date = ymd(CompletedDate),
         moisture_1 = as.numeric(Moisture1),
         moisture_2 = as.numeric(Moisture2),
         moisture_3 = as.numeric(Moisture3),
         moisture_ave = as.numeric(MoistureAve),
         moisture_missing = as.character(WhatMissing),
         moisture_incomplete = as.factor(Incomplete),
         moisture_ignore_missing = as.factor(IgnoreMissingData),
         moisture_ignore_reason = as.character(IgnoreReason),
         moisture_tech = as.character(Technician),
         moisture_split = as.factor(Split),
         area = "WMT") %>% 
  # replace 0 and -999 values with NA
  replace_with_na(replace = list(moisture_1 = 0, moisture_2 = 0,
                                 moisture_3 = 0, moisture_ave = 0)) %>% 
  replace_with_na(replace = list(moisture_1 = -999, moisture_2 = -999,
                                 moisture_3 = -999)) %>% 
  # gather 3 moisture samples to calculate average
  gather("sample", "value", c("moisture_1":"moisture_3")) %>% 
  group_by(home_winter_id, moisture_date) %>% 
  mutate(moisture_ave = mean(value, na.rm = TRUE)) %>% 
  ungroup() %>% 
  # spread 3 moisture samples back to wide format
  spread(sample, value) %>% 
  select(moisture_id, home_winter_id, area, moisture_date, moisture_1, moisture_2, moisture_3, 
         moisture_ave, moisture_missing, moisture_incomplete, moisture_ignore_missing,
         moisture_ignore_reason, moisture_tech, moisture_split)
  
# Save as RDS and CSV
write_rds(kids_moisture, "Output/kids_moisture.rds")
write_csv(kids_moisture, "Output/kids_moisture.csv")
```

# Load, format, and save home and child overview/demographic data
```{r}
# Load files
wmt_child_initial <- read_xlsx("Input/wmt_child_20191126.xlsx")
wmt_home_initial <- read_xlsx("Input/wmt_home_20191126.xlsx")
wmt_homewinter_initial <- read_xlsx("Input/wmt_homewinter_20191126.xlsx")
wmt_parent_demographics_initial <- read_xlsx("Input/wmt_parent_demographics_20191126.xlsx")

# join all files from above
joined1 <- wmt_child_initial %>% 
  mutate(hispanic_child = as.factor(Hispanic),
         race_child = as.factor(Race),
         comments_child = Comments,
         what_missing_child = WhatMissing,
         incomplete_child = Incomplete,
         ignore_missing_child = IgnoreMissingData,
         ignore_reason_child = IgnoreReason) %>% 
  select(-ID, -Hispanic, -Race, -Comments, -WhatMissing, -Incomplete,
         -IgnoreMissingData, -IgnoreReason) %>% 
  left_join(wmt_homewinter_initial, by = "HomeID") %>% 
  left_join(wmt_home_initial, by = "HomeID") %>% 
  left_join(wmt_parent_demographics_initial, by = "HomeWinterID") %>%
  mutate(gender_parent = as.factor(Gender),
         hispanic_parent = as.factor(Hispanic),
         race_parent = as.factor(Race),
         what_missing_parent = WhatMissing,
         incomplete_parent = Incomplete,
         ignore_missing_parent = IgnoreMissingData,
         ignore_reason_parent = IgnoreReason) %>%
  select(-ID, -Hispanic, -Race, -WhatMissing, -Incomplete,
         -IgnoreMissingData, -IgnoreReason, -Gender, -EnterDate) %>%
  rename_all(tolower)

# create dataset of id's and treatment assignment
wmt_ids_linked <- joined1 %>% 
  select(childid, homeid, home, homewinterid, winterid, txcondition) %>% 
  mutate(child_id = as.character(childid),
         home_id = as.character(homeid),
         home_winter_id = as.character(homewinterid),
         winter_id = as.character(winterid),
         treatment = as.factor(txcondition)) %>% 
  select(-childid, -homeid, -homewinterid, -winterid, -txcondition)
  
# create dataset of demographic data
wmt_demographic_data <- joined1 %>% 
  mutate(child_id = as.character(childid),
         home_id = as.character(homeid),
         age_nov1 = as.factor(agenov1),
         child_assent_date = ymd(childassentdate),
         parent_consent_date = ymd(parentconsentdate),
         home_winter_id = as.character(homewinterid),
         total_residents = as.numeric(totalres),
         total_residents_under5 = as.numeric(underfive),
         ignore_blanks_parent = ignoreblanks,
         income = as.factor(income),
         education = as.factor(education)) %>% 
  select(child_id, home_id, hispanic_child, age_nov1, race_child, child_assent_date,
         parent_consent_date, comments_child, what_missing_child, incomplete_child,
         enrolled, ignore_missing_child, ignore_reason_child,
         home_winter_id, gender_parent, hispanic_parent, race_parent, income,
         education, total_residents, total_residents_under5, incomplete_parent,
         ignore_blanks_parent, what_missing_parent, ignore_missing_parent,
         ignore_reason_parent) %>% 
  distinct(child_id, .keep_all = TRUE)

# create dataset of data on home details
## lower on priority list - see which variables we will use and clean later
wmt_home_details_uncleaned <- wmt_homewinter_initial %>%
  left_join(wmt_home_initial, by = "HomeID") %>% 
  rename_all(tolower)


# Save as RDS and CSV
write_rds(wmt_ids_linked, "Output/wmt_ids_linked.rds")
write_rds(wmt_demographic_data, "Output/wmt_demographic_data.rds")
write_csv(wmt_ids_linked, "Output/wmt_ids_linked.csv")
write_csv(wmt_demographic_data, "Output/wmt_demographic_data.csv")
```


```{r}

```

