---
title: 'KidsAIR: household demographics summary'
author: "Ethan Walker"
date: "Started 27 Jan 2020, Updated 12 May 2020"
output:
  beamer_presentation: default
  powerpoint_presentation: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE, 
                      include = TRUE, warning = FALSE,
                      fig.height = 6, fig.width = 8)
```

```{r, message=FALSE}
library(tidyverse)
library(readxl)
library(naniar)
library(lubridate)
library(zoo)
library(knitr)
jv_palette <- c("#330099","#CC0066","#FF6633", 
                 "#0099CC", "#FF9900","#CC6633",
                  "#FF3366", "#33CC99", "#33999")
```


```{r}
# Load individual datasets
file_path <- c("C:/Users/ethan.walker/Box/Ethan Walker UM/R/KidsAIR/")

kids_linked_ids <- read_rds(paste0(file_path, "Output/kids_linked_ids.rds"))
demographics_initial <- read_rds(paste0(file_path, "Output/demographics_clean.rds")) 
pm_clean <- read_rds(paste0(file_path, "Output/pm_clean.rds"))
```


```{r}
# number of placebo households, total and by area
placebo_homes <- kids_linked_ids %>% 
  filter(winter_id == 1) %>% 
  filter(treatment == "Placebo") %>% 
  count(area)

# number of placebo households, total and by area
treatment_homes <- kids_linked_ids %>% 
  filter(winter_id == 1) %>% 
  count(treatment)

# number of placebo households, total and by area
treatment_kids <- demographics_initial %>% 
  filter(winter_id == 2) %>% 
  count(treatment)
```

```{r}
# add new vars to dataset

```

```{r}
# summary data for manuscript tables
demo_funct_total <- function(var, data = demographics_initial){

demographics_summary <- data %>% 
  rename(new_var = var) %>% 
  filter(winter_id == 1) %>% 
  filter(treatment == "Placebo") %>% 
  distinct(home, .keep_all = TRUE) %>% 
  mutate(total_n = n()) %>% 
  group_by(area) %>% 
  mutate(area_n = n()) %>% 
  group_by(new_var) %>% 
  mutate(n = n(),
         percent = n()/total_n) %>% 
  distinct(new_var, .keep_all = TRUE) %>% 
  select(new_var, n, percent)
demographics_summary
}

demo_funct_total("gender_parent")
demo_funct_total("hispanic_parent")
demo_funct_total("race_parent")


demo_funct_area <- function(var, data = demographics_initial){

demographics_summary <- data %>% 
  rename(new_var = var) %>% 
  filter(winter_id == 1) %>% 
  filter(treatment == "Placebo") %>% 
  distinct(home, .keep_all = TRUE) %>% 
  mutate(total_n = n()) %>% 
  group_by(area) %>% 
  mutate(area_n = n()) %>% 
  group_by(area, new_var) %>% 
  mutate(n = n(),
         percent = n()/area_n) %>% 
  distinct(new_var, .keep_all = TRUE) %>% 
  select(new_var, n, percent)
demographics_summary
}

demo_funct_area("gender_parent")
demo_funct_area("hispanic_parent")
demo_funct_area("race_parent")
```


```{r}
# Filter for homes that have PM data

# 93 Winter 1 placebo homes have PM data
pm_homes_placebo <- pm_clean %>% 
  filter(winter_id == 1) %>% 
  filter(treatment == "Placebo") %>% 
  group_by(area, home) %>% 
  mutate(initial_obs = if_else(pm_datetime_new == first_datetime_new, 1, 0)) %>% 
  filter(initial_obs == 1) %>% 
  mutate(pm_home = "true") %>% 
  select(area, home, home_winter_id, pm_home) %>% 
  ungroup() %>% 
  arrange(area, home)

demographics_filtered <- demographics_clean %>% 
  # change to correct joining data of interest
  left_join(pm_homes_placebo, by = c("area", "home", "home_winter_id")) %>% 
  filter(pm_home == "true") %>% 
  filter(winter_id == 1) %>% 
  ungroup() %>% 
  arrange(area, home)
```


```{r, include=FALSE}
# Summarize numeric vars
kids_dems <- demographics_clean %>%  
  filter(winter_id == 1) %>% 
  filter(treatment == "Placebo") %>%
  distinct(home, .keep_all = TRUE) %>%  
  filter(!is.na(gender_parent)) %>% 
  group_by(area) %>% 
  summarize("Mean" = mean(total_residents, na.rm = TRUE), 
            "SD" = sd(total_residents, na.rm = TRUE),
            "min" = min(total_residents, na.rm = TRUE), 
            "max" = max(total_residents, na.rm = TRUE))
kable(kids_dems, digits = 1, align = "c")

# Summarize factor vars
alaska_dems <- demographics_filtered %>%  
  #distinct(home, .keep_all = TRUE) %>% 
  filter(area == "AK") %>% 
  group_by(age_child_nov) %>% 
  #summarize(n = n(), percent = (n()/10)*100)
  summarize(n = n(), percent = (n()/18)*100)
alaska_dems

navajo_dems <- demographics_filtered %>%  
  #distinct(home, .keep_all = TRUE) %>% 
  filter(area == "NN") %>% 
  group_by(age_child_nov) %>% 
  #summarize(n = n(), percent = (n()/23)*100)
  summarize(n = n(), percent = (n()/32)*100)
navajo_dems

montana_dems <- demographics_filtered %>%  
  #distinct(home, .keep_all = TRUE) %>% 
  filter(area == "WMT") %>% 
  group_by(age_child_nov) %>% 
  #summarize(n = n(), percent = (n()/60)*100)
  summarize(n = n(), percent = (n()/87)*100)
montana_dems

## Select specific var to assess individually/group by area
table(demographics_filtered$education, demographics_filtered$area, useNA = "ifany")
```

```{r}
# Filter for Winter 1; remove NAs

demographics_filtered <- demographics_clean %>% 
  filter(winter_id == 1) %>% 
  filter(residents_under_five != 0) %>% 
  mutate(income = factor(income,
                         levels = c("Less than $20,000", "$20,000 to $29,999",
                                    "$30,000 to $39,999", "$40,000 to $49,999",
                                    "$50,000 to $74,999", "$75,000 to $99,999",
                                    "$100,000 or more")),
         education = factor(education,
                            levels = c("Less than high school",
                                       "High school diploma or GED",
                                       "Some college",
                                       "College degree")),
         total_residents = as.numeric(total_residents),
         total_residents = if_else(total_residents == 1, 2, total_residents),
         race_parent = factor(race_parent,
                              levels = c("American Indian/Alaskan Native",
                                         "Asian", "White",
                                         "More than one race"),
                              labels = c("AI/AN", "Asian", "White", "Multiple")),
         race_child = factor(race_child,
                              levels = c("American Indian/Alaskan Native",
                                         "White", "More than one race"),
                              labels = c("AI/AN", "White", "Multiple")),
         age_child_nov = factor(age_child_nov,
                                levels = c("Less than 1", "1", "2", "3", "4")))
```


```{r}
# Demographics summary stats function

demographics_function <- function(data, var, title_label, y_label) {
  
  demographics_plot <- data %>% 
  filter(winter_id == 1) %>% 
  select(area, var) %>% 
  rename(plot_var = var) %>% 
  filter(!is.na(plot_var)) %>% 
  ggplot() +
    geom_bar(aes(plot_var, fill = area)) +
    theme_minimal() +
    theme(axis.text.x = element_text(size = 16, colour = "black", 
                                     angle = 40, vjust = 0.7, hjust = 0.7),
          axis.text.y = element_text(size = 16, colour = "black"),
          title = element_text(size = 20, colour = "black"),
          legend.text = element_text(size = 18, colour = "black"),
          legend.title = element_text(size = 18, colour = "black"),
          axis.title.y = element_text(size = 18, colour = "black"),
          axis.title.x = element_blank(),
          axis.line.x = element_line(colour = "black", size = 1.2), 
          axis.line.y = element_line(colour = "black", size = 1.2), 
          axis.ticks = element_blank(),
          panel.grid = element_blank()) +
    labs(title = title_label) +
    ylab(y_label) +
    scale_fill_manual(values = jv_palette)
  demographics_plot
  
}
```

```{r}
demographics_function(demographics_filtered, "gender_parent", "Parent sex", "count")
```

\pagebreak

```{r}
demographics_function(demographics_filtered, "hispanic_parent", "Parent Hispanic ethnicity", "count")
```

\pagebreak

```{r}
demographics_function(demographics_filtered, "race_parent", "Parent race", "count")
```

\pagebreak

```{r}
demographics_function(demographics_filtered, "hispanic_child", "Child Hispanic ethnicity", "count")
```

\pagebreak

```{r}
demographics_function(demographics_filtered, "race_child", "Child race", "count")
```

\pagebreak

```{r}
demographics_function(demographics_filtered, "age_child_nov", "Child age Nov 1st", "count")
```

\pagebreak

```{r}
demographics_function(demographics_filtered, "income", "Household income", "count")
```

\pagebreak

```{r}
demographics_function(demographics_filtered, "education", "Parent education", "count")
```

\pagebreak

```{r}
demographics_function(demographics_filtered, "total_residents", "Total residents", "count")
```

\pagebreak

```{r}
demographics_function(demographics_filtered, "residents_under_five", 
                      "Residents under 5 years of age", "count")
```

