---
title: "KidsAIR: covariate associations exposure analysis"
author: "Ethan Walker"
date: "Started 2 Feb 2020, Updated 16 April 2020"
output: pdf_document
header-includes:
    - \usepackage[labelformat=empty]{caption}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = FALSE, include = FALSE,
                      message = FALSE, warning = FALSE)
```

```{r, eval=TRUE, include=TRUE}
library(readxl)
library(naniar)
library(lubridate)
library(broom)
library(broom.mixed)
library(zoo)
library(lme4)
library(lmerTest)
library(mctest)
library(tidyverse)
library(knitr)
library(kableExtra)
```


```{r, eval=TRUE, include=TRUE}
# Load individual datasets

input_path <- c("C:/Users/ethan.walker/Box/Ethan Walker UM/R/KidsAIR/Input/")
output_path <- c("C:/Users/ethan.walker/Box/Ethan Walker UM/R/KidsAIR/")
input_file <- c("exposure_analysis_data_long_new.rds")
output_file <- c("exposure_analysis_data_long_new.rds")

exposure_analysis_data_long <- 
  read_rds(paste0(output_path, "Output/exposure_analysis_data_long_new.rds")) 

exposure_analysis_data_medium <- 
  read_rds(paste0(output_path, "Output/exposure_analysis_data_medium.rds")) 

exposure_analysis_data_short <- 
  read_rds(paste0(output_path, "Output/exposure_analysis_data_short.rds"))

sums_rolling_pm_data <- 
  read_rds(paste0(output_path, "Output/sums_rolling_pm_data.rds"))

health_exposure_data_sampling_day <- 
  read_rds(paste0(output_path, "Output/health_exposure_data_sampling_day.rds"))
```

```{r, eval=TRUE, include=TRUE}
####### Format SUMs data to merge with analysis data below
sums_temp_change <- sums_rolling_pm_data %>% 
  filter(winter_id == 1 & treatment == "Placebo") %>% 
  group_by(area, home, sampling_day) %>% 
  distinct(datetime_sums, .keep_all = TRUE) %>% 
  group_by(area, home, sampling_day) %>% 
  mutate(time_diff = (lead(datetime_sums) - datetime_sums)) %>% 
  mutate(lead_temp = if_else(time_diff < 20, lead(temp_c_sums, 4), lead(temp_c_sums)),
         lead_temp = if_else(time_diff > 25, 999, lead_temp)) %>% 
  replace_with_na(replace = list(lead_temp = 999)) %>% 
  mutate(temp_diff = lead_temp - temp_c_sums,
         # change temp in the following line
         temp_diff_check = if_else(temp_diff >= 5, 1, 0),
         heat_event = if_else(temp_diff_check == 1 & lag(temp_diff_check) == 1, 0,
                              temp_diff_check),
         heat_event = if_else(is.na(temp_diff_check), 1,
                              heat_event)) %>% 
  group_by(area, home, sampling_day) %>% 
  mutate(sums_events_sampling_day = sum(heat_event, na.rm = TRUE),
         sums_events_sampling_day_cat = cut(sums_events_sampling_day, 
                                            breaks = c(0, 2, 50),
                           labels = c("<2", "2+"),
                                 right = FALSE)) %>% 
  distinct(sampling_day, .keep_all = TRUE) %>% 
  ungroup() %>% 
  select(area:pm_rolling_20, sums_mean_winter:sums_mean_sampling_period,
         time_diff:sums_events_sampling_day_cat) %>% 
  arrange(area, home, sample_date) %>% 
  group_by(home) %>% 
  mutate(sums_events_sampling_period = mean(sums_events_sampling_day, na.rm = TRUE)) %>% 
  select(area, home, home_winter_id, sums_events_sampling_period) %>% 
  distinct(home, .keep_all = TRUE) %>% 
  ungroup()

####### Format ambient data to merge with analysis data below
ambient_data <- exposure_analysis_data_long %>% 
  filter(winter_id == 1 & treatment == "Placebo") %>% 
  #filter(area == "AK") %>% 
  filter(!is.na(sampling_day)) %>% 
  filter(!is.na(sample_date)) %>%
  select(area, home, child_id_char, sample_date, sampling_day, pm_mean_daily,
         amb_pm_24hr:mean_temp_roll_4day) %>% 
  group_by(home) %>% 
  mutate(amb_pm_sampling_period_5 = mean(amb_pm_24hr, na.rm = TRUE)/5,
         mean_temp_sampling_period_5 = mean(mean_temp, na.rm = TRUE)/5) %>% 
  distinct(home, .keep_all = TRUE) %>% 
  ungroup()

####### Format home activity data to merge with analysis data below
home_activity_data <- exposure_analysis_data_medium %>% 
  filter(winter_id == 1 & treatment == "Placebo") %>% 
  group_by(area, home) %>% 
  distinct(sampling_day, .keep_all = TRUE) %>% 
  group_by(area, home) %>% 
  mutate_at(vars(starts_with("home_act")), as.numeric) %>% 
  mutate_at(vars(starts_with("home_act")), funs(. - 1)) %>% 
  mutate_at(vars(starts_with("home_act")), funs(sum(.))) %>% 
  ungroup() %>% 
  distinct(area, home, .keep_all = TRUE) %>% 
  select(home, area, sampling_day, starts_with("home_act"))

####### Format full data to use for analysis
analysis_data <- exposure_analysis_data_short %>% 
  filter(winter_id == 1 & treatment == "Placebo" & area == "WMT") %>% 
  group_by(area, home) %>% 
  distinct(home, .keep_all = TRUE) %>% 
  ungroup() %>% 
  mutate(moisture_closest_2level = cut(moisture_closest, breaks = c(0, 10.5, 100),
                                 labels = c("<10.5", "10.5+"),
                                 right = FALSE),
         moisture_winter_2level = cut(mean_moisture_winter, breaks = c(0, 10.5, 100),
                                 labels = c("<10.5", "10.5+"),
                                 right = FALSE)) %>% 
  mutate(temp_max_2level = cut(temp_indoor_max, breaks = c(0, 30, 100),
                                 labels = c("<30", "30+"),
                                 right = FALSE),
         temp_min_2level = cut(temp_indoor_min, breaks = c(0, 16.5, 100),
                                 labels = c("<16.5", "16.5+"),
                                 right = FALSE),
         rh_max_2level = cut(rh_indoor_max, breaks = c(0, 40, 100),
                                 labels = c("<40", "40+"),
                                 right = FALSE),
         rh_min_2level = cut(rh_indoor_min, breaks = c(0, 20, 100),
                                 labels = c("<20", "20+"),
                                 right = FALSE)) %>% 
  mutate(sums_mean_sampling_period_5 = sums_mean_sampling_period/5,
         temp_perc_25_2level = cut(temp_perc_25, breaks = c(0, 50, 100),
                                 labels = c("<50", "50+"),
                                 right = FALSE),
         temp_perc_27_2level = cut(temp_perc_27, breaks = c(0, 35, 100),
                                 labels = c("<35", "35+"),
                                 right = FALSE),
         temp_perc_30_2level = cut(temp_perc_30, breaks = c(0, 10, 100),
                                 labels = c("<10", "10+"),
                                 right = FALSE)) %>% 
  left_join(sums_temp_change, by = c("area", "home")) %>% 
  left_join(ambient_data, by = c("area", "home")) %>% 
  select(-starts_with("home_act")) %>% 
  left_join(home_activity_data, by = c("area", "home")) %>% 
  mutate(home_act_door_2level = cut(home_act_door, breaks = c(0, 1, 7),
                                 labels = c("<1", "1+"),
                                 right = FALSE),
         home_act_smoke_2level = cut(home_act_smoking, breaks = c(0, 1, 7),
                                 labels = c("<1", "1+"),
                                 right = FALSE),
         home_act_windows_2level = cut(home_act_windows, breaks = c(0, 1, 7),
                                 labels = c("<1", "1+"),
                                 right = FALSE),
         home_act_sweep_2level = cut(home_act_sweep, breaks = c(0, 3, 7),
                                 labels = c("<3", "3+"),
                                 right = FALSE))
  

####### Function to run analysis
analysis_function <- function(covar, label, 
                              dataset = analysis_data){
  
  analysis_data <- dataset %>% 
    filter(winter_id == 1 & treatment == "Placebo") %>% 
    group_by(area, home) %>% 
    distinct(home, .keep_all = TRUE) %>% 
    rename(analysis_covar = covar) %>% 
    ungroup() %>% 
    select(pm_mean_sampling_period, analysis_covar) 
  
  analysis_results <- lm(log(pm_mean_sampling_period) ~ analysis_covar, analysis_data)
  
  tidy_results <<- tidy(analysis_results, conf.int = TRUE) %>% 
    filter(term != '(Intercept)') %>% 
    mutate(Estimate = round(estimate, digits = 2),
           'P-value' = round(p.value, digits = 2),
           'Upper 95% CL' = round(conf.high, digits = 2),
           'Lower 95% CL' = round(conf.low, digits = 2),
           Term = gsub("analysis_covar", paste0(label, ": "), term)) %>% 
    select(Term, Estimate, 'Lower 95% CL', 'Upper 95% CL', 'P-value')
  
}

####### Variables to run through fuction and save results
d1 <- analysis_function("education_3level", "Education")
d2 <- analysis_function("income_3level", "Income")
d3 <- analysis_function("race_parent_2level", "Parent race")
d4 <- analysis_function("total_residents_2level", "Total residents")
d5 <- analysis_function("residents_under5_2level", "Residents under 5 y/o")
d6 <- analysis_function("residents_smoke", "Residents smoke")

d7 <- analysis_function("home_type_2level", "Home type")
d8 <- analysis_function("home_year_built_2level", "Home age")
d9 <- analysis_function("home_sqft_2level", "home sqft")
d10 <- analysis_function("home_floors_2level", "Home floors")
d11 <- analysis_function("home_bedrooms_2level", "Home bedrooms")
d12 <- analysis_function("home_windows_2level", "Home windows")
d13 <- analysis_function("home_pets_2level", "Pets - total")
d14 <- analysis_function("home_furry_2level", "Pets - furry")
d15 <- analysis_function("secondary_heat_3level", "Secondary heating")
d16 <- analysis_function("stove_age_3level", "Stove age")
d17 <- analysis_function("stove_cert", "Stove EPA certified")
d18 <- analysis_function("chimney_clean_3level", "Chimney cleaned")
d19 <- analysis_function("home_damp", "Home - damp")
d20 <- analysis_function("home_mold", "Home - mold")
d21 <- analysis_function("home_fireplace", "Home fireplace")
d22 <- analysis_function("home_furnace", "Home furnace")

d23 <- analysis_function("burn_level_3level", "Burn level")
d24 <- analysis_function("wood_collect_2level", "Wood collect time")
d25 <- analysis_function("wood_collect_method_2level", "Wood collect method")
d26 <- analysis_function("wood_cords", "Wood cords")

d27 <- analysis_function("moisture_closest", "Wood moisture - closest to sampling")
d28 <- analysis_function("moisture_closest_2level", "Wood moisture - closest to sampling")
d29 <- analysis_function("mean_moisture_winter", "Wood moisture - Winter mean")
d30 <- analysis_function("moisture_winter_2level", "Wood moisture - Winter mean")

d31 <- analysis_function("temp_min_5", "Minimum indoor temp - per 5 degree increase")
d32 <- analysis_function("temp_max_5", "Maximum indoor temp - per 5 degree increase")
d33 <- analysis_function("rh_min_5", "Minimum indoor RH - per 5% increase")
d34 <- analysis_function("rh_max_5", "Maximum indoor RH - per 5% increase")
d35 <- analysis_function("temp_min_2level", "Minimum indoor temp")
d36 <- analysis_function("temp_max_2level", "Maximum indoor temp")
d37 <- analysis_function("rh_min_2level", "Minimum indoor RH")
d38 <- analysis_function("rh_max_2level", "Maximum indoor RH")

d39 <- analysis_function("sums_mean_sampling_period_5", "SUMs mean temperature")
d40 <- analysis_function("temp_perc_25_2level", "SUMs - % obs > 25 degrees C")
d41 <- analysis_function("temp_perc_27_2level", "SUMs - % obs > 27 degrees C")
d42 <- analysis_function("temp_perc_30_2level", "SUMs - % obs > 30 degrees C")
d43 <- analysis_function("sums_events_sampling_period", 
                         "Daily SUMs events - 5C temp increase in 20 min")

d44 <- analysis_function("amb_pm_sampling_period_5", "Mean ambient PM2.5 - per 5ug/m3 increase")
d45 <- analysis_function("mean_temp_sampling_period_5", 
                         "Mean ambient temp - per 5 degree increase")

d46 <- analysis_function("home_act_gas", "Home activity - gas appliance")
d47 <- analysis_function("home_act_elect", "Home activity - electric appliance")
d48 <- analysis_function("home_act_propane", "Home activity - propane appliance")
d49 <- analysis_function("home_act_oil", "Home activity - oil appliance")
d50 <- analysis_function("home_act_other", "Home activity - other appliance")
d51 <- analysis_function("home_act_smoking", "Home activity - smoking")
d52 <- analysis_function("home_act_incense", "Home activity - incense")
d53 <- analysis_function("home_act_candle", "Home activity - candle")
d54 <- analysis_function("home_act_windows", "Home activity - windows open")
d55 <- analysis_function("home_act_door", "Home activity - doors open")
d56 <- analysis_function("home_act_sweep", "Home activity - cleaning")
d57 <- analysis_function("home_act_smoke_2level", "Home activity - smoking 2 level")
d58 <- analysis_function("home_act_windows_2level", "Home activity - windows 2 level")
d59 <- analysis_function("home_act_door_2level", "Home activity - doors 2 level")
d60 <- analysis_function("home_act_sweep_2level", "Home activity - cleaning 2 level")

d61 <- analysis_function("stove_grade_3level", "Stove grade")

####### Combine results to use in a table
table_data <- rbind(d1, d2, d3, d4, d5, d6,
                    d7, d8, d9, d10, d11, d12, d13, d14, d15, d16, d17, d18,
                    d19, d20, d21, d22,
                    d23, d24, d25, d26,
                    d27, d28, d29, d30,
                    d31, d32, d33, d34, d35, d36, d37, d38,
                    d39, d40, d41, d42, d43,
                    d44, d45,
                    d46, d47, d48, d49, d50, d51, d52, d53, d54, d55, d56,
                    d57, d58, d59, d60,
                    d61)

####### Print full table of results
kable(table_data, longtable = TRUE,
      caption = "Indoor PM2.5 (natural log transformed) and covariate associations") %>% 
   kable_styling(latex_options = "repeat_header") %>% 
   row_spec(0, bold = TRUE) %>% 
   pack_rows("Demographic variables", 1, 8) %>%
   pack_rows("Home characteristics", 9, 31) %>%
   pack_rows("Stove use", 32, 36) %>%
   pack_rows("Wood moisture content", 37, 40) %>%
   pack_rows("Indoor temperature and relative humidity", 41, 48) %>%
   pack_rows("Stove Use Monitors (SUMs) temperature", 49, 53) %>%
   pack_rows("Ambient data", 54, 55) %>%
   pack_rows("Home activities - Sum of all sampling days", 56, 69) %>%
   pack_rows("Stove grade", 70, 71) %>%
   footnote(c("PM2.5 = fine particulate matter", 
              "PM2.5 and all covariates have been averaged or summed to produce 1 observation per sampling period"))
```


```{r}
###### Chunks below are useful for checking individual associations

# Demographics

analysis_data <- exposure_analysis_data_short %>% 
  filter(winter_id == 1 & treatment == "Placebo") %>% 
  group_by(area, home) %>% 
  distinct(home, .keep_all = TRUE) %>% 
  filter(!is.na(pm_mean_sampling_period)) %>% 
  ungroup()

# Variables to use:
## education_3level, income_3level, race_parent_2level, 
## total_residents_2level, residents_under5_2level, resident_smokes

table(analysis_data$residents_smoke)
median(analysis_data$home_furry, na.rm = TRUE)

pm_demographics_results <- lm(log(pm_mean_sampling_period) ~ education_3level, 
                              data = analysis_data)

summary(pm_demographics_results)
glance(pm_demographics_results)

tidy(pm_demographics_results) %>% 
    filter(term != '(Intercept)') %>% 
    mutate(estimate = round(estimate, digits = 2),
           'p-value' = round(p.value, digits = 2),
           term = gsub("education_3level", "Education:  ", term)) %>% 
    select(term, estimate, 'p-value')

plot(pm_demographics_results)
```

```{r}
# Home characteristics

analysis_data <- exposure_analysis_data_short %>% 
  filter(winter_id == 1 & treatment == "Placebo") %>% 
  group_by(area, home) %>% 
  distinct(home, .keep_all = TRUE) %>% 
  ungroup()

# Variables to use:
## home_type_2level, home_year_built_2level, home_sqft_2level, home_floors_2level
## home_bedrooms_2level, home_windows_2level, home_pets_2level, home_furry_2level
## secondary_heat_3level, stove_age_3level, stove_cert, chimney_clean_3level,
## home_damp, home_mold, home_fireplace, home_furnace, home_insert

table(analysis_data$home_insert)
median(analysis_data$home_furry, na.rm = TRUE)

pm_home_char_results <- lm(log(pm_mean_sampling_period) ~ home_insert, 
                           data = analysis_data)
summary(pm_home_char_results)
tidy(pm_home_char_results)
plot(pm_home_char_results)
```

```{r}
# Stove use

analysis_data <- exposure_analysis_data_short %>% 
  filter(winter_id == 1 & treatment == "Placebo") %>% 
  group_by(area, home) %>% 
  distinct(home, .keep_all = TRUE) %>% 
  ungroup()

# Variables to use:
## burn_level_3level, wood_collect_2level, wood_collect_method_2level,
## wood_cords

table(analysis_data$burn_level_3level)
median(analysis_data$wood_cords, na.rm = TRUE)

pm_stove_use_results <- lm(log(pm_mean_sampling_period) ~ wood_collect_method_2level, 
                           data = analysis_data)
summary(pm_stove_use_results)
tidy(pm_stove_use_results)
plot(pm_stove_use_results)
pm_stove_use_plot <- pm_stove_use %>% 
  ggplot() + 
    geom_boxplot(aes(burn_level, mean_pm))
pm_stove_use_plot
```

```{r}
# Stove grades

analysis_data <- exposure_analysis_data_short %>% 
  filter(winter_id == 1 & treatment == "Placebo") %>% 
  group_by(area, home) %>% 
  distinct(home, .keep_all = TRUE) %>% 
  ungroup()

# Variables to use:
## stove_grade_3level

table(analysis_data$stove_grade_3level)

pm_stove_grades_results <- lm(log(pm_mean_sampling_period) ~ stove_grade_3level, 
                              data = analysis_data)
summary(pm_stove_grades_results)
tidy(pm_stove_grades_results)
anova(pm_stove_grades_results)
plot(pm_stove_grades_results)
pm_stove_grades_plot <- pm_stove_grades %>% 
  ggplot() + 
    geom_boxplot(aes(stove_grade, mean_pm))
pm_stove_grades_plot
```

```{r}
# Home activity

analysis_data <- exposure_analysis_data_medium %>% 
  filter(winter_id == 1 & treatment == "Placebo") %>% 
  group_by(area, home) %>% 
  distinct(sampling_day, .keep_all = TRUE) %>% 
  ungroup()

# Variables to use:
## home_act_gas, home_act_elect, home_act_propane, home_act_oil, home_act_other,
## home_act_smoke, home_act_incense, home_act_candle, home_act_windows,
## home_act_door, home_act_sweep

table(analysis_data$home_act_sweep)

pm_home_act_results <- lmer(log(pm_mean_sampling_day) ~ home_act_sweep + 
                              (1 | home), data = analysis_data)
summary(pm_home_act_results)
tidy(pm_home_act_results)
plot(pm_home_act_results, 
     xlab = "fitted values", ylab = "residuals")
qqnorm(residuals(pm_home_act_results), main = "QQ Plot")
```

```{r}
# Wood moisture content
 
analysis_data <- exposure_analysis_data_short %>% 
  filter(winter_id == 1 & treatment == "Placebo") %>% 
  group_by(area, home) %>% 
  distinct(home, .keep_all = TRUE) %>% 
  ungroup() %>% 
  mutate(moisture_closest_2level = cut(moisture_closest, breaks = c(0, 10.5, 100),
                                 labels = c("<10.5", "10.5+"),
                                 right = FALSE),
         moisture_winter_2level = cut(mean_moisture_winter, breaks = c(0, 10.5, 100),
                                 labels = c("<10.5", "10.5+"),
                                 right = FALSE)) 

# Variables to use:
## moisture_closest, moisture_closest_2level
## mean_moisture_winter, moisture_winter_2level

table(analysis_data$moisture_closest_2level)
median(analysis_data$mean_moisture_winter, na.rm = TRUE)


pm_moisture_results <- lm(log(pm_mean_sampling_period) ~ 
                            moisture_winter_2level, data = analysis_data)
summary(pm_moisture_results)
plot(pm_moisture_results)
```

```{r}
# Indoor temp/RH

analysis_data <- exposure_analysis_data_short %>% 
  filter(winter_id == 1 & treatment == "Placebo") %>% 
  group_by(area, home) %>% 
  distinct(home, .keep_all = TRUE) %>% 
  ungroup() %>% 
  mutate(temp_max_2level = cut(temp_indoor_max, breaks = c(0, 30, 100),
                                 labels = c("<30", "30+"),
                                 right = FALSE),
         temp_min_2level = cut(temp_indoor_min, breaks = c(0, 16.5, 100),
                                 labels = c("<16.5", "16.5+"),
                                 right = FALSE),
         rh_max_2level = cut(rh_indoor_max, breaks = c(0, 40, 100),
                                 labels = c("<40", "40+"),
                                 right = FALSE),
         rh_min_2level = cut(rh_indoor_min, breaks = c(0, 20, 100),
                                 labels = c("<20", "20+"),
                                 right = FALSE))

# Variables to use:
## rh_min_5, rh_max_5, temp_min_5, temp_max_5
## temp_max_2level, temp_min_2level,rh_max_2level ,rh_min_2level

table(analysis_data$temp_max_2level)
median(analysis_data$rh_indoor_min, na.rm = TRUE)


pm_temp_rh_results <- lm(log(pm_mean_sampling_period) ~ temp_max_2level, 
                         data = analysis_data)
summary(pm_temp_rh_results)
tidy(pm_temp_rh_results)
plot(pm_temp_rh_results)
```

```{r}
# SUMs - by sampling day

analysis_data <- exposure_analysis_data_medium %>% 
  filter(winter_id == 1 & treatment == "Placebo") %>% 
  group_by(area, home) %>% 
  distinct(sampling_day, .keep_all = TRUE) %>% 
  mutate(sums_mean_sampling_day_5 = sums_mean_sampling_day/5,
         temp_perc_25_2level = cut(temp_perc_25, breaks = c(0, 50, 100),
                                 labels = c("<50", "50+"),
                                 right = FALSE),
         temp_perc_27_2level = cut(temp_perc_27, breaks = c(0, 35, 100),
                                 labels = c("<35", "35+"),
                                 right = FALSE),
         temp_perc_30_2level = cut(temp_perc_30, breaks = c(0, 10, 100),
                                 labels = c("<10", "10+"),
                                 right = FALSE)) %>% 
  ungroup()

# Variables to use:
## sums_mean_sampling_day_5, temp_perc_25_2level
## temp_perc_27_2level, temp_perc_30_2level

table(analysis_data$temp_perc_30_2level)
median(analysis_data$temp_perc_30, na.rm = TRUE)

pm_sums_results <- lmer(log(pm_mean_sampling_day) ~ temp_perc_30_2level + 
                              (1 | home), data = analysis_data)
pm_sums_results <- lmer(pm_mean_sampling_day ~ temp_perc_30_2level + 
                              (1 | home), data = analysis_data)
summary(pm_sums_results)
tidy(pm_sums_results)
plot(pm_sums_results, 
     xlab = "fitted values", ylab = "residuals")
qqnorm(residuals(pm_sums_results), main = "QQ Plot")
```

```{r}
# SUMs - by sampling period

analysis_data <- exposure_analysis_data_short %>% 
  filter(winter_id == 1 & treatment == "Placebo") %>% 
  group_by(area, home) %>% 
  distinct(home, .keep_all = TRUE) %>% 
  mutate(sums_mean_sampling_period_5 = sums_mean_sampling_period/5,
         temp_perc_25_2level = cut(temp_perc_25, breaks = c(0, 50, 100),
                                 labels = c("<50", "50+"),
                                 right = FALSE),
         temp_perc_27_2level = cut(temp_perc_27, breaks = c(0, 35, 100),
                                 labels = c("<35", "35+"),
                                 right = FALSE),
         temp_perc_30_2level = cut(temp_perc_30, breaks = c(0, 10, 100),
                                 labels = c("<10", "10+"),
                                 right = FALSE)) %>% 
  ungroup()

# Variables to use:
## sums_mean_sampling_period_5, temp_perc_25_2level
## temp_perc_27_2level, temp_perc_30_2level

table(analysis_data$temp_perc_25_2level)
median(analysis_data$temp_perc_30, na.rm = TRUE)

pm_sums_results <- lm(log(pm_mean_sampling_period) ~ sums_mean_sampling_period_5, 
                      data = analysis_data)
pm_sums_results <- lm(pm_mean_sampling_period ~ sums_mean_sampling_period_5, 
                      data = analysis_data)
summary(pm_sums_results)
tidy(pm_sums_results)
plot(pm_sums_results, 
     xlab = "fitted values", ylab = "residuals")
qqnorm(residuals(pm_sums_results), main = "QQ Plot")
```

```{r}
# SUMs - mean PM per SUMs interval

analysis_data <- sums_rolling_pm_data %>% 
  mutate(temp_c_sums_5 = temp_c_sums/5)

cor.test(analysis_data$temp_c_sums, analysis_data$pm_rolling_20, method = "spearman")
pm_sums_model <- lmer(log(pm_rolling_20) ~ temp_c_sums_5 + (1 | home), 
                      data = analysis_data)
pm_sums_model <- lmer(pm_rolling_20 ~ temp_c_sums_5 + (1 | home), 
                      data = analysis_data)

summary(pm_sums_model)
tidy(pm_sums_model)
exp((0.1496794)-1)*100
plot(pm_sums_model, 
     xlab = "fitted values", ylab = "residuals")
qqnorm(residuals(pm_sums_model), main = "QQ Plot")

pm_sums_plot <- analysis_data %>% 
  ggplot() + 
    geom_point(aes(log(pm_rolling_20), temp_c_sums)) +
    geom_smooth(aes(log(pm_rolling_20), temp_c_sums)) +
    theme_minimal()
pm_sums_plot
```

```{r}
# SUMs - events per sampling day 

sums_temp_change <- sums_rolling_pm_data %>% 
  filter(winter_id == 1 & treatment == "Placebo") %>% 
  group_by(area, home, sampling_day) %>% 
  distinct(datetime_sums, .keep_all = TRUE) %>% 
  group_by(area, home, sampling_day) %>% 
  mutate(time_diff = (lead(datetime_sums) - datetime_sums)) %>% 
  mutate(lead_temp = if_else(time_diff < 20, lead(temp_c_sums, 4), lead(temp_c_sums)),
         lead_temp = if_else(time_diff > 25, 999, lead_temp)) %>% 
  replace_with_na(replace = list(lead_temp = 999)) %>% 
  mutate(temp_diff = lead_temp - temp_c_sums,
         # change temp in the following line
         temp_diff_check = if_else(temp_diff >= 5, 1, 0),
         heat_event = if_else(temp_diff_check == 1 & lag(temp_diff_check) == 1, 0,
                              temp_diff_check),
         heat_event = if_else(is.na(temp_diff_check), 1,
                              heat_event)) %>% 
  group_by(area, home, sampling_day) %>% 
  mutate(sums_events_sampling_day = sum(heat_event, na.rm = TRUE),
         sums_events_sampling_day_cat = cut(sums_events_sampling_day, 
                                            breaks = c(0, 2, 50),
                           labels = c("<2", "2+"),
                                 right = FALSE)) %>% 
  distinct(sampling_day, .keep_all = TRUE) %>% 
  ungroup() %>% 
  select(area:pm_rolling_20, sums_mean_winter:sums_mean_sampling_period,
         time_diff:sums_events_sampling_day_cat) %>% 
  arrange(area, home, sample_date) 


median(sums_temp_change$sums_events, na.rm = TRUE)
table(sums_temp_change$sums_events_sampling_day_cat)

pm_sums_model <- lmer(pm_mean_sampling_day ~ sums_events_sampling_day_cat + 
                        (1 | home), data = sums_temp_change)
pm_sums_model <- lmer(log(pm_mean_sampling_day) ~ sums_events_sampling_day_cat + 
                        (1 | home), data = sums_temp_change)

summary(pm_sums_model)
tidy(pm_sums_model)
#exp((0.146291)-1)*100
plot(pm_sums_model, 
     xlab = "fitted values", ylab = "residuals")
qqnorm(residuals(pm_sums_model), main = "QQ Plot")

pm_sums_plot <- sums_temp_change %>% 
  filter(!is.na(sums_events)) %>% 
  ggplot() + 
    geom_boxplot(aes(sums_events_cat, log(pm_mean_sampling_day))) +
    theme_minimal()
pm_sums_plot
```

```{r}
# Ambient temp/PM - by sampling date

analysis_data <- exposure_analysis_data_long %>% 
  filter(winter_id == 1 & treatment == "Placebo") %>% 
  #filter(area == "AK") %>% 
  filter(!is.na(sampling_day)) %>% 
  filter(!is.na(sample_date)) %>%
  select(area, home, child_id_char, sample_date, sampling_day, pm_mean_daily,
         zip:mean_temp_roll_4day) %>% 
  mutate(amb_pm_5 = amb_pm_24hr/5,
         mean_temp_5 = mean_temp/5,
         mean_temp_cat = cut(mean_temp, breaks = c(0, 30, 150),
                           labels = c("<30", "30+"),
                                 right = FALSE),
         amb_pm_cat = cut(amb_pm_24hr, breaks = c(0, 7, 100),
                           labels = c("<7", "7+"),
                                 right = FALSE))


median(analysis_data$amb_pm_24hr, na.rm = TRUE)
table(analysis_data$amb_pm_cat)
  

# Variables to use:
## amb_pm_5, amb_pm_cat,
## amb_pm_24hr, amb_pm_24hr_lag1, amb_pm_24hr_lag2, amb_pm_24hr_lag3
## amb_pm_roll_mean_2day, amb_pm_roll_mean_3day, amb_pm_roll_mean_4day
## mean_temp_5, mean_temp_cat,
## mean_temp, mean_temp_lag1, mean_temp_lag2, mean_temp_lag3
## mean_temp_roll_2day, mean_temp_roll_3day, mean_temp_roll_4day

  
cor.test(analysis_data$mean_temp, analysis_data$pm_mean_daily, method = "spearman")
pm_ambient_model <- lmer(log(pm_mean_daily) ~ amb_pm_cat + (1 | home), 
                      data = analysis_data)
pm_ambient_model <- lmer(pm_mean_daily ~ amb_pm_cat + (1 | home), 
                      data = analysis_data)

#summary(pm_ambient_model)
tidy(pm_ambient_model)
exp((-0.06723228)-1)*100
plot(pm_ambient_model, 
     xlab = "fitted values", ylab = "residuals")
qqnorm(residuals(pm_ambient_model), main = "QQ Plot")

pm_sums_plot <- analysis_data %>% 
  ggplot() + 
    geom_point(aes(log(pm_mean_daily), mean_temp)) +
    geom_smooth(aes(log(pm_mean_daily), mean_temp)) +
    theme_minimal()
pm_sums_plot
```



