---
title: "KidsAIR: exposure model"
author: "Ethan Walker"
date: "Started 19 March 2020, Updated 20 March 2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
library(tidyverse)
library(readxl)
library(naniar)
library(lubridate)
library(zoo)
library(lme4)
library(lmerTest)
library(pbkrtest)
library(emmeans)
library(broom)
library(MuMIn)
library(leaps)
jv_palette <- c("#330099","#CC0066","#FF6633", 
                 "#0099CC", "#FF9900","#CC6633",
                  "#FF3366", "#33CC99", "#33999")
```

```{r}
exposure_analysis_data_long <- read_rds("Output/exposure_analysis_data_long_new.rds") 

exposure_analysis_data_medium <- read_rds("Output/exposure_analysis_data_medium.rds") 

exposure_analysis_data_short <- read_rds("Output/exposure_analysis_data_short.rds")

sums_rolling_pm_data <- read_rds("Output/sums_rolling_pm_data.rds")
```

# Linear model
```{r}
subset_model <- lm(log(pm_mean) ~ 
                        income_3level + home_act_smoking + 
                        area, data = exposure_analysis_data_short)

full_model <- lm(log(pm_mean) ~ 
                        education_3level + income_3level + 
                        total_residents_2level + home_floors_2level + home_windows_2level + 
                        stove_age_3level + chimney_clean_3level + 
                        wood_collect_2level + 
                        stove_grade_3level + 
                        home_act_smoking + 
                        moisture_2level + 
                        temp_perc_30_cat +
                        area, data = exposure_analysis_data_short)

summary(subset_model)
r.squaredGLMM(subset_model)

tidy_results <- tidy(full_model)
tidy_results

plot(full_model, 
     xlab = "fitted values", ylab = "residuals")
qqnorm(residuals(full_model), main = "QQ Plot")
```

# Best subsets selection using dredge() from MuMIn
```{r}
options(na.action = "na.fail")

all_subsets <- dredge(full_model, rank = "AIC", extra = c("R^2"))
```


# Linear mixed model with repeated measures
```{r}
subset_model <- lmer(log(pm_mean_daily) ~ 
                        education_3level + income_3level + race_parent_2level + 
                        area + sampling_day + day_of_week +
                        (1 | home), data = exposure_analysis_data_long)

full_model <- lmer(log(pm_mean_daily) ~ 
                        education_3level + income_3level + race_parent_2level + 
                        total_residents_2level + residents_smoke + 
                        home_type_2level + home_floors_2level + home_windows_2level + 
                        stove_age_3level + chimney_clean_3level + home_mold + 
                        home_fireplace + 
                        wood_collect_2level + 
                        stove_grade_3level + 
                        home_act_gas + home_act_propane + home_act_smoking + 
                        moisture_2level + 
                        temp_max_5 + 
                        temp_perc_30_cat +
                        area + sampling_day + day_of_week +
                        (1 | home), data = exposure_analysis_data_long)

summary(full_model)
r.squaredGLMM(full_model)

tidy_results <- tidy(full_model)
tidy_results

plot(full_model, 
     xlab = "fitted values", ylab = "residuals")
qqnorm(residuals(full_model), main = "QQ Plot")
```
