---
title: "KidsAIR initial home/child data work"
author: "Ethan Walker"
date: "Started 19 Nov 2019, Updated 12 May 2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
library(tidyverse)
library(readxl)
library(naniar)
library(lubridate)
library(zoo)
```


# Load, format, and save home and child overview/demographic data for WMT
```{r}
file_path <- c("C:/Users/ethan.walker/Box/Ethan Walker UM/R/KidsAIR/")

# Load files 
## Box location: All Files > NoonGroupData > KidsAIR > 
## 2019-November-Data > WMT > child.xlsx
wmt_child_initial <- read_xlsx(paste0(file_path, "Input/WMT/wmt_child_20191126.xlsx")) %>% 
  rename_all(tolower) %>% 
  # filter(enrolled == 1) %>% # filter out kids who weren't enrolled
  select(childid, homeid, id, hispanic, race, agenov1, enrolled) %>% 
  mutate(child_id_num = as.character(childid),
         home_id = as.character(homeid),
         child_id_char = as.character(id),
         hispanic_child = as.factor(hispanic),
         race_child = as.factor(race),
         age_child_nov = as.character(agenov1)) %>% 
  select(child_id_num, home_id, child_id_char, hispanic_child,
         race_child, age_child_nov, enrolled) 

## Box location: All Files > NoonGroupData > KidsAIR > 
## 2019-November-Data > WMT > home.xlsx
wmt_home_initial <- read_xlsx(paste0(file_path, "Input/WMT/wmt_home_20191126.xlsx")) %>% 
  rename_all(tolower) %>% 
  select(homeid, home, txcondition) %>% 
  mutate(home_id = as.character(homeid),
         home = as.character(home),
         treatment = as.factor(txcondition)) %>% 
  select(home_id, home, treatment)

## Box location: All Files > NoonGroupData > KidsAIR > 
## 2019-November-Data > WMT > homewinter.xlsx
wmt_homewinter_initial <- read_xlsx(paste0(file_path, "Input/WMT/wmt_homewinter_20191126.xlsx")) %>% 
  rename_all(tolower) %>% 
  select(homewinterid, homeid, winterid, interventiondate, interventiontime) %>% 
  filter(winterid != 3) %>% # filter for winterid == 1 or 2. What about missing intervention date?
  mutate(home_winter_id = as.character(homewinterid),
         home_id = as.character(homeid),
         winter_id = as.character(winterid),
         intervention_date = interventiondate,
         intervention_time = interventiontime) %>% 
  select(home_winter_id, home_id, winter_id, intervention_date, intervention_time)

## Box location: All Files > NoonGroupData > KidsAIR > 
## 2019-November-Data > WMT > Home Data > parentdemographics.xlsx
wmt_parent_demographics_initial <-
  read_xlsx(paste0(file_path, "Input/WMT/wmt_parent_demographics_20191126.xlsx")) %>% 
  rename_all(tolower) %>% 
  #filter(whatmissing != "all" | is.na(whatmissing)) %>%  # filter out if missing == "all"
  select(homewinterid, gender, hispanic, race, income, education,
         totalres, underfive) %>% 
  mutate(home_winter_id = as.character(homewinterid),
         gender_parent = as.factor(gender),
         hispanic_parent = as.factor(hispanic),
         race_parent = as.factor(race),
         income = as.factor(income),
         education = as.factor(education),
         total_residents = as.character(totalres),
         residents_under_five = as.character(underfive)) %>% 
  select(home_winter_id, gender_parent, hispanic_parent, race_parent,
         income, education, total_residents, residents_under_five) 

# join all files from above
joined1 <- wmt_homewinter_initial %>% 
  full_join(wmt_parent_demographics_initial, by = "home_winter_id") %>% 
  #mutate(home_id = if_else(home_winter_id == 275, "153", home_id)) %>% 
  ### 1st big filter - remove those with no home_id
  ### All other past this point should be considered "enrolled"
  filter(!is.na(home_id)) %>% 
  full_join(wmt_home_initial, by = "home_id") %>% 
  full_join(wmt_child_initial, by = "home_id") %>% 
  filter(!is.na(home_winter_id)) %>% 
  mutate(area = "WMT") 
  ### Once data is joined for all areas, filter for homes with treatment assignment
  ### This will help further refine data for analysis and be a number in the flow chart
  

# create dataset of id's and treatment assignment
wmt_home_ids_linked <- joined1 %>% 
  select(area, home_id, winter_id, home, home_winter_id, treatment) %>% 
  distinct(home_winter_id, .keep_all = TRUE) %>% 
  arrange(home_id, winter_id)
  
# create dataset of child demographic data
wmt_child_demographics <- joined1 %>% 
  #distinct(child_id_num, .keep_all = TRUE) %>% 
  arrange(home_id, child_id_num, winter_id) 


# Save as RDS and CSV
write_rds(wmt_home_ids_linked, paste0(file_path, "Output/wmt_ids_linked.rds"))
write_rds(wmt_child_demographics, paste0(file_path, "Output/wmt_demographic_data.rds"))
``` 

# Load, format, and save home and child overview/demographic data for NN
```{r}
# Load files
## Box location: All Files > NoonGroupData > KidsAIR > 
## 2019-November-Data > Navajo > child.xlsx
nn_child_initial <- read_xlsx(paste0(file_path, "Input/NN/nn_child_20191216.xlsx")) %>% 
  rename_all(tolower) %>% 
  # filter(enrolled == 1) %>% # filter out kids who weren't enrolled
  select(childid, homeid, id, hispanic, race, agenov1, enrolled) %>% 
  mutate(child_id_num = as.character(childid),
         home_id = as.character(homeid),
         child_id_char = as.character(id),
         child_id_char = gsub(child_id_char, pattern = " ", replacement = ""),
         child_id_char = gsub(child_id_char, pattern = "_", replacement = ""),
         child_id_char = gsub(child_id_char, pattern = "-", replacement = ""),
         hispanic_child = as.factor(hispanic),
         race_child = as.factor(race),
         age_child_nov = as.character(agenov1)) %>% 
  select(child_id_num, home_id, child_id_char, hispanic_child,
         race_child, age_child_nov, enrolled)

## Box location: All Files > NoonGroupData > KidsAIR > 
## 2019-November-Data > Navajo > home.xlsx
nn_home_initial <- read_xlsx(paste0(file_path, "Input/NN/nn_home_20191216.xlsx")) %>% 
  rename_all(tolower) %>% 
  select(homeid, home, txcondition) %>% 
  mutate(home_id = as.character(homeid),
         home = as.character(home),
         treatment = as.factor(txcondition)) %>% 
  select(home_id, home, treatment)

## Box location: All Files > NoonGroupData > KidsAIR > 
## 2019-November-Data > Navajo > homewinter.xlsx
nn_homewinter_initial <- read_xlsx(paste0(file_path, "Input/NN/nn_homewinter_20191216.xlsx")) %>% 
  rename_all(tolower) %>% 
  select(homewinterid, homeid, winterid, interventiondate, interventiontime) %>% 
  mutate(home_winter_id = as.character(homewinterid),
         home_id = as.character(homeid),
         winter_id = as.character(winterid),
         intervention_date = interventiondate,
         intervention_time = interventiontime) %>% 
  mutate(winter_id = as.numeric(winter_id),
         winter_id = if_else(home_id == 62 | home_id == 45, winter_id + 1, winter_id),
         winter_id = as.character(winter_id)) %>% 
  filter(winter_id == 1 | winter_id ==2) %>% # filter for winterid == 1 or 2. What about missing intervention date?
  select(home_winter_id, home_id, winter_id, intervention_date, intervention_time)

## Box location: All Files > NoonGroupData > KidsAIR > 
## 2019-November-Data > Navajo > Home Data > parentdemographics.xlsx
nn_parent_demographics_initial <-
  read_xlsx(paste0(file_path, "Input/NN/nn_parent_demographics_20191216.xlsx")) %>% 
  rename_all(tolower) %>% 
  #filter(whatmissing != "all" | is.na(whatmissing)) %>%  # filter out if missing == "all"
  select(homewinterid, gender, hispanic, race, income, education,
         totalres, underfive) %>% 
  mutate(home_winter_id = as.character(homewinterid),
         gender_parent = as.factor(gender),
         hispanic_parent = as.factor(hispanic),
         race_parent = as.factor(race),
         income = as.factor(income),
         education = as.factor(education),
         total_residents = as.character(totalres),
         residents_under_five = as.character(underfive)) %>% 
  select(home_winter_id, gender_parent, hispanic_parent, race_parent,
         income, education, total_residents, residents_under_five)

# join all files from above
joined1 <- nn_homewinter_initial %>% 
  full_join(nn_parent_demographics_initial, by = "home_winter_id") %>% 
  ### 1st big filter - remove those with no home_id
  ### All other past this point should be considered "enrolled"
  filter(!is.na(home_id)) %>% 
  full_join(nn_home_initial, by = "home_id") %>% 
  full_join(nn_child_initial, by = "home_id") %>% 
  mutate(area = "NN") 
  ### Once data is joined for all areas, filter for homes with treatment assignment
  ### This will help further refine data for analysis and be a number in the flow chart
  

# create dataset of id's and treatment assignment
nn_home_ids_linked <- joined1 %>% 
  select(area, home_id, winter_id, home, home_winter_id, treatment) %>% 
  distinct(home_winter_id, .keep_all = TRUE) %>% 
  arrange(home_id, winter_id)
  
# create dataset of child demographic data
nn_child_demographics <- joined1 %>% 
  #distinct(child_id_num, .keep_all = TRUE) %>% 
  arrange(home_id, child_id_num, winter_id) 


# Save as RDS and CSV
write_rds(nn_home_ids_linked, paste0(file_path, "Output/nn_ids_linked.rds"))
write_rds(nn_child_demographics, paste0(file_path, "Output/nn_demographic_data.rds"))
```

# Load, format, and save home and child overview/demographic data for AK
```{r}
# Load files 
## Box location: All Files > NoonGroupData > KidsAIR > 
## 2019-November-Data > AK > child.xlsx
ak_child_initial <- read_xlsx(paste0(file_path, "Input/AK/ak_child_20191216.xlsx")) %>% 
  rename_all(tolower) %>% 
  # filter(enrolled == 1) %>% # filter out kids who weren't enrolled
  select(childid, homeid, id, hispanic, race, agenov1, enrolled) %>% 
  mutate(child_id_num = as.character(childid),
         home_id = as.character(homeid),
         child_id_char = as.character(id),
         hispanic_child = as.factor(hispanic),
         race_child = as.factor(race),
         age_child_nov = as.character(agenov1)) %>% 
  select(child_id_num, home_id, child_id_char, hispanic_child,
         race_child, age_child_nov, enrolled)

## Box location: All Files > NoonGroupData > KidsAIR > 
## 2019-November-Data > AK > home.xlsx
ak_home_initial <- read_xlsx(paste0(file_path, "Input/AK/ak_home_20191216.xlsx")) %>% 
  rename_all(tolower) %>% 
  select(homeid, home, txcondition) %>% 
  mutate(home_id = as.character(homeid),
         home = as.character(home),
         treatment = as.factor(txcondition)) %>% 
  select(home_id, home, treatment)

## Box location: All Files > NoonGroupData > KidsAIR > 
## 2019-November-Data > AK > homewinter.xlsx
ak_homewinter_initial <- read_xlsx(paste0(file_path, "Input/AK/ak_homewinter_20191216.xlsx")) %>% 
  rename_all(tolower) %>% 
  select(homewinterid, homeid, winterid, interventiondate, interventiontime) %>% 
  filter(winterid != 3) %>% # filter for winterid == 1 or 2. What about missing intervention date?
  mutate(home_winter_id = as.character(homewinterid),
         home_id = as.character(homeid),
         winter_id = as.character(winterid),
         intervention_date = interventiondate,
         intervention_time = interventiontime) %>% 
  select(home_winter_id, home_id, winter_id, intervention_date, intervention_time)

## Box location: All Files > NoonGroupData > KidsAIR > 
## 2019-November-Data > AK > Home Data > parentdemographics.xlsx
ak_parent_demographics_initial <-
  read_xlsx(paste0(file_path, "Input/AK/ak_parent_demographics_20191216.xlsx")) %>% 
  rename_all(tolower) %>% 
  #filter(whatmissing != "all" | is.na(whatmissing)) %>%  # filter out if missing == "all"
  select(homewinterid, gender, hispanic, race, income, education,
         totalres, underfive) %>% 
  mutate(home_winter_id = as.character(homewinterid),
         gender_parent = as.factor(gender),
         hispanic_parent = as.factor(hispanic),
         race_parent = as.factor(race),
         income = as.factor(income),
         education = as.factor(education),
         total_residents = as.character(totalres),
         residents_under_five = as.character(underfive)) %>% 
  select(home_winter_id, gender_parent, hispanic_parent, race_parent,
         income, education, total_residents, residents_under_five)

# join all files from above
joined1 <- ak_homewinter_initial %>% 
  full_join(ak_parent_demographics_initial, by = "home_winter_id") %>% 
  ### 1st big filter - remove those with no home_id
  ### All other past this point should be considered "enrolled"
  filter(!is.na(home_id)) %>% 
  full_join(ak_home_initial, by = "home_id") %>% 
  full_join(ak_child_initial, by = "home_id") %>% 
  mutate(area = "AK") 
  ### Once data is joined for all areas, filter for homes with treatment assignment
  ### This will help further refine data for analysis and be a number in the flow chart
  

# create dataset of id's and treatment assignment
ak_home_ids_linked <- joined1 %>% 
  select(area, home_id, winter_id, home, home_winter_id, treatment) %>% 
  distinct(home_winter_id, .keep_all = TRUE) %>% 
  arrange(home_id, winter_id) 
  
# create dataset of child demographic data
ak_child_demographics <- joined1 %>% 
  #distinct(child_id_num, .keep_all = TRUE) %>% 
  arrange(home_id, child_id_num, winter_id) 


# Save as RDS and CSV
write_rds(ak_home_ids_linked, paste0(file_path, "Output/ak_ids_linked.rds"))
write_rds(ak_child_demographics, paste0(file_path, "Output/ak_demographic_data.rds"))
```

# Count total observations in dataset for homes and kids
```{r}
file_path <- c("C:/Users/ethan.walker/Box/Ethan Walker UM/R/KidsAIR/")

ak_demographics <- read_rds(paste0(file_path, "Output/ak_demographic_data.rds"))
nn_demographics <- read_rds(paste0(file_path, "Output/nn_demographic_data.rds"))
wmt_demographics <- read_rds(paste0(file_path, "Output/wmt_demographic_data.rds"))

kids_demographics <- rbind(ak_demographics, nn_demographics, wmt_demographics) %>% 
  mutate(home_id = as.numeric(home_id)) %>% 
  filter(home_id < 1000) %>%
  mutate(home_id = as.character(home_id)) %>% 
  # distinct(area, home_id)  # distinct homes in database = 360
  filter(!is.na(child_id_num)) %>% 
  # distinct(area, child_id_num, .keep_all = TRUE) %>%  # distinct kids in database = 512
  # distinct(area, home_id, .keep_all = TRUE) %>% # distinct homes with kids in databse = 340
  ### WMA222 and WMA 233 had a treatment but no kids - not counting in flow chart
  filter(!is.na(treatment)) %>%  
  distinct(area, child_id_num, .keep_all = TRUE) %>%   # distinct kids with treatment = 512
  distinct(area, home_id, .keep_all = TRUE)  # distinct homes with kids with treatment = 340
```


# Combine linked id data for WMT, NN, AK
```{r}
file_path <- c("C:/Users/ethan.walker/Box/Ethan Walker UM/R/KidsAIR/")

ak_ids <- read_rds(paste0(file_path, "Output/ak_ids_linked.rds"))
nn_ids <- read_rds(paste0(file_path, "Output/nn_ids_linked.rds"))
wmt_ids <- read_rds(paste0(file_path, "Output/wmt_ids_linked.rds"))

kids_ids <- rbind(ak_ids, nn_ids, wmt_ids) %>% 
  mutate(home_id = as.numeric(home_id)) %>% 
  filter(home_id < 1000) %>%  
  mutate(home_id = as.character(home_id)) %>% 
  # distinct(area, home_id)  # enrolled homes in database = 360
  filter(!is.na(treatment)) %>% 
  # distinct(area, home_id)  # randomized homes with treatment assignment = 342
  ### WMA222 and WMA 233 had a treatment but no kids - not counting in flow chart
  filter(home != "WMA222" & home != "WMA233") %>% 
  #distinct(area, home_id)  # randomized homes with treatment assignment = 340
  ungroup() %>% 
  arrange(area, home)

write_rds(kids_ids, paste0(file_path, "Output/kids_linked_ids.rds"))
```

# Combine demographic data for WMT, NN, AK
```{r}
file_path <- c("C:/Users/ethan.walker/Box/Ethan Walker UM/R/KidsAIR/")

ak_demographics <- read_rds(paste0(file_path, "Output/ak_demographic_data.rds"))
nn_demographics <- read_rds(paste0(file_path, "Output/nn_demographic_data.rds"))
wmt_demographics <- read_rds(paste0(file_path, "Output/wmt_demographic_data.rds"))

kids_demographics <- rbind(ak_demographics, nn_demographics, wmt_demographics) %>% 
  mutate(home_id = as.numeric(home_id)) %>% 
  filter(home_id < 1000) %>%
  mutate(home_id = as.character(home_id)) %>% 
  filter(!is.na(child_id_num)) %>% 
  filter(!is.na(treatment)) %>% 
  separate(intervention_time, c("trash", "intervention_time"), sep = " ") %>% 
  unite(intervention_datetime, c("intervention_date", "intervention_time"),
        sep = " ", remove = FALSE) %>% 
  mutate(intervention_datetime = ymd_hms(intervention_datetime)) %>% 
  select(-trash) %>% 
  ungroup() %>% 
  arrange(area, home, child_id_char)

write_rds(kids_demographics, paste0(file_path, "Output/kids_combined_demographics.rds"))
```

