---
title: "KidsAIR home activity and characteristics cleaning"
author: "Ethan Walker"
date: "Started 13 Jan 2020, Updated 19 June 2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
library(tidyverse)
library(readxl)
library(naniar)
library(lubridate)
library(zoo)

file_path <- c("C:/Users/ethan.walker/Box/Ethan Walker UM/R/KidsAIR/")
kids_linked_ids <- read_rds(paste0(file_path, "Output/kids_linked_ids_final.rds")) 
demographics <- read_rds(paste0(file_path, "Output/demographics_final.rds")) 
```

# Load, format, and save home char data
```{r}
##### WMT #####
# Load data
home_char_initial_wmt <- read_csv(paste0(file_path, "Input/WMT/homechar.csv"), 
                                  na = c("NULL", ""))

wmt_home_char <- home_char_initial_wmt %>% 
  # rename variables
  mutate(home_winter_id = as.factor(HomeWinterID),
         residents_total = as.numeric(Residents),
         residents_under5 = as.numeric(Under5),
         residents_under18 = as.numeric(Under18),
         residents_smoke = as.factor(Smoke),
         residents_smoke_inside = as.factor(SmokeInside),
         home_type = as.factor(HomeType),
         home_year_built = as.numeric(YearHomeBuilt),
         home_sqft = as.numeric(SqFootage),
         home_floors = as.numeric(NumFloors),
         home_bedrooms = as.numeric(NumBedrooms),
         home_windows = as.numeric(NumWindows),
         home_pets = as.numeric(NumPets),
         home_furry = as.numeric(NumFurryPets),
         primary_heat = as.factor(PrimaryHeat),
         secondary_heat = as.factor(SecondaryHeat),
         stove_model = as.character(WoodstoveModel),
         stove_age = as.factor(WoodstoveAge),
         stove_cert = as.factor(WoodstoveEPACert),
         chimney_clean = as.factor(ChimneyCleaned),
         home_damp = as.factor(Damp),
         home_mold = as.factor(Mold),
         home_fireplace = as.factor(ExistingFireplace),
         home_furnace = as.factor(ExistingFurnace),
         home_woodstove = as.factor(ExistingWoodstove),
         home_insert = as.factor(ExistingInsert),
         area = "WMT") %>% 
  select(home_winter_id, area, residents_total, residents_under5,
         residents_under18, residents_smoke, residents_smoke_inside,
         home_type, home_year_built, home_sqft, home_floors, home_bedrooms,
         home_windows, home_pets, home_furry, primary_heat,
         secondary_heat, stove_model, stove_age, stove_cert, chimney_clean,
         home_damp, home_mold, home_fireplace, home_furnace,
         home_woodstove, home_insert) %>% 
  ungroup() %>% 
  arrange(home_winter_id)

# Save as RDS
write_rds(wmt_home_char, paste0(file_path, "Output/wmt_home_char.rds"))


##### NN #####
# Load data
home_char_initial_nn <- read_csv(paste0(file_path, "Input/NN/homechar.csv"), na = c("NULL", ""))

nn_home_char <- home_char_initial_nn %>% 
  # rename variables
   mutate(home_winter_id = as.factor(HomeWinterID),
         residents_total = as.numeric(Residents),
         residents_under5 = as.numeric(Under5),
         residents_under18 = as.numeric(Under18),
         residents_smoke = as.factor(Smoke),
         residents_smoke_inside = as.factor(SmokeInside),
         home_type = as.factor(HomeType),
         home_year_built = as.numeric(YearHomeBuilt),
         home_sqft = as.numeric(SqFootage),
         home_floors = as.numeric(NumFloors),
         home_bedrooms = as.numeric(NumBedrooms),
         home_windows = as.numeric(NumWindows),
         home_pets = as.numeric(NumPets),
         home_furry = as.numeric(NumFurryPets),
         primary_heat = as.factor(PrimaryHeat),
         secondary_heat = as.factor(SecondaryHeat),
         stove_model = as.character(WoodstoveModel),
         stove_age = as.factor(WoodstoveAge),
         stove_cert = as.factor(WoodstoveEPACert),
         chimney_clean = as.factor(ChimneyCleaned),
         home_damp = as.factor(Damp),
         home_mold = as.factor(Mold),
         home_fireplace = as.factor(ExistingFireplace),
         home_furnace = as.factor(ExistingFurnace),
         home_woodstove = as.factor(ExistingWoodstove),
         home_insert = as.factor(ExistingInsert),
         area = "NN") %>% 
  select(home_winter_id, area, residents_total, residents_under5,
         residents_under18, residents_smoke, residents_smoke_inside,
         home_type, home_year_built, home_sqft, home_floors, home_bedrooms,
         home_windows, home_pets, home_furry, primary_heat,
         secondary_heat, stove_model, stove_age, stove_cert, chimney_clean,
         home_damp, home_mold, home_fireplace, home_furnace,
         home_woodstove, home_insert) %>% 
  ungroup() %>% 
  arrange(home_winter_id)

# Save as RDS
write_rds(nn_home_char, paste0(file_path, "Output/nn_home_char.rds"))


##### AK #####
# Load data
home_char_initial_ak <- read_csv(paste0(file_path, "Input/AK/homechar.csv"), na = c("NULL", ""))

ak_home_char <- home_char_initial_ak %>% 
  # rename variables
  mutate(home_winter_id = as.factor(HomeWinterID),
         residents_total = as.numeric(Residents),
         residents_under5 = as.numeric(Under5),
         residents_under18 = as.numeric(Under18),
         residents_smoke = as.factor(Smoke),
         residents_smoke_inside = as.factor(SmokeInside),
         home_type = as.factor(HomeType),
         home_year_built = as.numeric(YearHomeBuilt),
         home_sqft = as.numeric(SqFootage),
         home_floors = as.numeric(NumFloors),
         home_bedrooms = as.numeric(NumBedrooms),
         home_windows = as.numeric(NumWindows),
         home_pets = as.numeric(NumPets),
         home_furry = as.numeric(NumFurryPets),
         primary_heat = as.factor(PrimaryHeat),
         secondary_heat = as.factor(SecondaryHeat),
         stove_model = as.character(WoodstoveModel),
         stove_age = as.factor(WoodstoveAge),
         stove_cert = as.factor(WoodstoveEPACert),
         chimney_clean = as.factor(ChimneyCleaned),
         home_damp = as.factor(Damp),
         home_mold = as.factor(Mold),
         home_fireplace = as.factor(ExistingFireplace),
         home_furnace = as.factor(ExistingFurnace),
         home_woodstove = as.factor(ExistingWoodstove),
         home_insert = as.factor(ExistingInsert),
         area = "AK") %>% 
  select(home_winter_id, area, residents_total, residents_under5,
         residents_under18, residents_smoke, residents_smoke_inside,
         home_type, home_year_built, home_sqft, home_floors, home_bedrooms,
         home_windows, home_pets, home_furry, primary_heat,
         secondary_heat, stove_model, stove_age, stove_cert, chimney_clean,
         home_damp, home_mold, home_fireplace, home_furnace,
         home_woodstove, home_insert) %>% 
  ungroup() %>% 
  arrange(home_winter_id)

# Save as RDS
write_rds(ak_home_char, paste0(file_path, "Output/ak_home_char.rds"))
```

# Join home characteristic data from different areas
```{r}
file_path <- c("C:/Users/ethan.walker/Box/Ethan Walker UM/R/KidsAIR/")

wmt_home_char <- read_rds(paste0(file_path, "Output/wmt_home_char.rds"))
nn_home_char <- read_rds(paste0(file_path, "Output/nn_home_char.rds"))
ak_home_char <- read_rds(paste0(file_path, "Output/ak_home_char.rds"))

kids_home_char <- rbind(wmt_home_char, nn_home_char, ak_home_char)

# write_rds(kids_home_char, paste0(file_path, "Output/kids_home_char.rds"))
```

# Clean up all home characteristics data
```{r}
file_path <- c("C:/Users/ethan.walker/Box/Ethan Walker UM/R/KidsAIR/")
kids_home_char <- read_rds(paste0(file_path, "Output/kids_home_char.rds"))
kids_linked_ids <- read_rds(paste0(file_path, "Output/kids_linked_ids_final.rds")) 

home_char_clean <- kids_home_char %>% 
  mutate(area = as.factor(area)) %>% 
  right_join(kids_linked_ids, by = c("area", "home_winter_id")) %>% 
  # cleaning based on checking odd values with paper logs
  mutate(residents_under5 = if_else(residents_under5 == 10, 1, residents_under5),
         residents_under5 = if_else(home == "CH307" | home == "CH323", 1, residents_under5)) %>% 
  replace_with_na(replace = list(home_year_built = 0)) %>% 
  replace_with_na(replace = list(home_floors = 0)) %>% 
  replace_with_na(replace = list(home_windows = 0)) %>% 
  replace_with_na(replace = list(residents_total = 0)) %>% 
  replace_with_na(replace = list(residents_under5 = 0)) %>% 
  replace_with_na(replace = list(residents_under18 = 0)) %>% 
  replace_with_na(replace = list(home_sqft = 0)) %>% 
  mutate(home_year_built = if_else(home_year_built == 15, 2002, home_year_built),
         home_year_built = if_else(home_year_built == 874, 1980, home_year_built)) %>% 
  replace_with_na(replace = list(home_year_built = 1400)) %>% 
  mutate(home_sqft = if_else(home_sqft == 14 & home == "CH102", 360, home_sqft),
         home_sqft = if_else(home_sqft == 14 & home == "CH107", 1152, home_sqft)) %>% 
  replace_with_na(replace = list(home_sqft = 12)) %>% 
  replace_with_na(replace = list(home_sqft = 14)) %>% 
  replace_with_na(replace = list(home_sqft = 20)) %>% 
  replace_with_na(replace = list(home_sqft = 24)) %>% 
  replace_with_na(replace = list(home_sqft = 90)) %>% 
  mutate(home_furry = if_else(home_furry == 4 & home == "WMA368", 1, home_furry),
         home_furry = if_else(home_furry == 10 & home == "WMA345", 14, home_furry),
         home_furry = if_else(home == "WMA309", 3, home_furry),
         home_pets = if_else(home == "WMA309", 3, home_pets),
         home_pets = if_else(home == "WMA437", 3, home_pets),
         home_furry = if_else(home == "WMA437", 3, home_furry)) %>% 
  replace_with_na(replace = list(home_furry = 14)) %>% 
  ungroup() %>% 
  arrange(area, home, winter_id)

summary(home_char_clean)

write_rds(home_char_clean, paste0(file_path, "Output/home_char_clean.rds"))
```

###############################################

# Load, format, and save home activity data
```{r}
##### WMT #####
# Load data
home_act_initial_wmt <- read_csv(paste0(file_path, "Input/WMT/homeactivity.csv"), na = c("NULL", ""))

wmt_home_act <- home_act_initial_wmt %>% 
  # rename variables
  mutate(home_winter_id = as.factor(HomeWinterID),
         home_act_day = as.factor(Day),
         home_act_gas = as.factor(Gas),
         home_act_elect = as.factor(Electrical),
         home_act_propane = as.factor(Propane),
         home_act_oil = as.factor(Oil),
         home_act_other = as.factor(Other),
         home_act_smoking = as.factor(Smoking),
         home_act_incense = as.factor(Incense),
         home_act_candle = as.factor(Candle),
         home_act_kerosene = as.factor(Kerosene),
         home_act_windows = as.factor(OpenWindows),
         home_act_door = as.factor(OpenDoor),
         home_act_sweep = as.factor(Sweeping),
         home_act_comments = as.character(Comments),
         area = "WMT") %>% 
  select(home_winter_id, area, home_act_day,
         home_act_gas, home_act_elect, home_act_propane,
         home_act_oil, home_act_other, home_act_smoking,
         home_act_incense, home_act_candle, home_act_kerosene,
         home_act_windows, home_act_door, home_act_sweep, home_act_comments) %>% 
  ungroup() %>% 
  arrange(home_winter_id, home_act_day)

# Save as RDS
write_rds(wmt_home_act, paste0(file_path, "Output/wmt_home_act.rds"))


##### NN #####
# Load data
home_act_initial_nn <- read_csv(paste0(file_path, "Input/NN/homeactivity.csv"), na = c("NULL", ""))

nn_home_act <- home_act_initial_nn %>% 
  # rename variables
  mutate(home_winter_id = as.factor(HomeWinterID),
         home_act_day = as.factor(Day),
         home_act_gas = as.factor(Gas),
         home_act_elect = as.factor(Electrical),
         home_act_propane = as.factor(Propane),
         home_act_oil = as.factor(Oil),
         home_act_other = as.factor(Other),
         home_act_smoking = as.factor(Smoking),
         home_act_incense = as.factor(Incense),
         home_act_candle = as.factor(Candle),
         home_act_kerosene = as.factor(Kerosene),
         home_act_windows = as.factor(OpenWindows),
         home_act_door = as.factor(OpenDoor),
         home_act_sweep = as.factor(Sweeping),
         home_act_comments = as.character(IgnoreReason),
         area = "NN") %>% 
  select(home_winter_id, area, home_act_day,
         home_act_gas, home_act_elect, home_act_propane,
         home_act_oil, home_act_other, home_act_smoking,
         home_act_incense, home_act_candle, home_act_kerosene,
         home_act_windows, home_act_door, home_act_sweep, home_act_comments) %>% 
  ungroup() %>% 
  arrange(home_winter_id, home_act_day)

# Save as RDS
write_rds(nn_home_act, paste0(file_path, "Output/nn_home_act.rds"))


##### AK #####
# Load data
home_act_initial_ak <- read_csv(paste0(file_path, "Input/AK/homeactivity.csv"), na = c("NULL", ""))

ak_home_act <- home_act_initial_ak %>% 
  # rename variables
  mutate(home_winter_id = as.factor(HomeWinterID),
         home_act_day = as.factor(Day),
         home_act_gas = as.factor(Gas),
         home_act_elect = as.factor(Electrical),
         home_act_propane = as.factor(Propane),
         home_act_oil = as.factor(Oil),
         home_act_other = as.factor(Other),
         home_act_smoking = as.factor(Smoking),
         home_act_incense = as.factor(Incense),
         home_act_candle = as.factor(Candle),
         home_act_kerosene = as.factor(Kerosene),
         home_act_windows = as.factor(OpenWindows),
         home_act_door = as.factor(OpenDoor),
         home_act_sweep = as.factor(Sweeping),
         home_act_comments = as.character(IgnoreReason),
         area = "AK") %>% 
  select(home_winter_id, area, home_act_day,
         home_act_gas, home_act_elect, home_act_propane,
         home_act_oil, home_act_other, home_act_smoking,
         home_act_incense, home_act_candle, home_act_kerosene,
         home_act_windows, home_act_door, home_act_sweep, home_act_comments) %>% 
  ungroup() %>% 
  arrange(home_winter_id, home_act_day)

# Save as RDS
write_rds(ak_home_act, paste0(file_path, "Output/ak_home_act.rds"))
```

# Join home activity data from different areas
```{r}
wmt_home_act <- read_rds(paste0(file_path, "Output/wmt_home_act.rds"))
nn_home_act <- read_rds(paste0(file_path, "Output/nn_home_act.rds"))
ak_home_act <- read_rds(paste0(file_path, "Output/ak_home_act.rds"))

kids_home_act <- rbind(wmt_home_act, nn_home_act, ak_home_act)

# write_rds(kids_home_act, paste0(file_path, "Output/kids_home_act.rds"))
```

# Clean up all home activity data
```{r}
file_path <- c("C:/Users/ethan.walker/Box/Ethan Walker UM/R/KidsAIR/")
kids_home_act <- read_rds(paste0(file_path, "Output/kids_home_act.rds"))
kids_linked_ids <- read_rds(paste0(file_path, "Output/kids_linked_ids_final.rds"))

home_act_clean <- kids_home_act %>% 
  mutate(area = as.factor(area)) %>% 
  right_join(kids_linked_ids, by = c("area", "home_winter_id"))

summary(home_act_clean)

write_rds(home_act_clean, paste0(file_path, "Output/home_act_clean.rds"))
```

