---
title: "Kids home characteristics/activity summary"
author: "Ethan Walker"
date: "Started 15 Jan 2020, Updated 23 June 2020"
output:
  pdf_document: default
  powerpoint_presentation: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE, 
                      include = TRUE, warning = FALSE,
                      fig.height = 5, fig.width = 7)
```

```{r, message=FALSE}
library(tidyverse)
library(readxl)
library(naniar)
library(lubridate)
library(zoo)
library(knitr)
library(forcats)
jv_palette <- c("#330099","#CC0066","#FF6633", 
                 "#0099CC", "#FF9900","#CC6633",
                  "#FF3366", "#33CC99", "#33999")
```

```{r}
# Load dataset
file_path <- c("C:/Users/ethan.walker/Box/Ethan Walker UM/R/KidsAIR/")

home_char_clean <- read_rds(paste0(file_path, "Output/home_char_clean.rds")) 
home_act_clean <- read_rds(paste0(file_path, "Output/home_act_clean.rds"))
kids_linked_ids <- read_rds(paste0(file_path, "Output/kids_linked_ids.rds"))
#pm_clean <- read_rds("Output/pm_clean.rds")
```

# Check Winter 1 vs Winter 2 data for home characteristics
```{r}
home_char_check_num <- home_char_clean %>% 
  group_by(home) %>% 
  arrange(home, winter_id) %>% 
  pivot_longer(cols = c(residents_total:residents_under18, home_year_built:home_furry), 
               names_to = "var", values_to = "value") %>% 
  group_by(home, var) %>% 
  arrange(home, var, winter_id) %>% 
  mutate(data_check = if_else(value == lead(value), 1, 0),
         data_check = if_else(is.na(data_check), lag(data_check), data_check)) %>% 
  filter(data_check == 0) %>% 
  select(area, home, winter_id, var, value) %>% 
  mutate(value = as.numeric(value),
         data_check = if_else(var == "residents_total" & abs(value - lead(value)) > 1, 1, 0),
         data_check = if_else(var == "residents_under5" & abs(value - lead(value)) > 1, 1, data_check),
         data_check = if_else(var == "residents_under18" & abs(value - lead(value)) > 1, 1, data_check),
         data_check = if_else(var == "home_year_built" & abs(value - lead(value)) > 10, 1, data_check),
         data_check = if_else(var == "home_sqft" & abs(value - lead(value)) > 200, 1, data_check),
         data_check = if_else(var == "home_floors" & abs(value - lead(value)) > 1, 1, data_check),
         data_check = if_else(var == "home_bedrooms" & abs(value - lead(value)) > 1, 1, data_check),
         data_check = if_else(var == "home_windows" & abs(value - lead(value)) > 5, 1, data_check),
         data_check = if_else(var == "home_pets" & abs(value - lead(value)) > 2, 1, data_check),
         data_check = if_else(var == "home_furry" & abs(value - lead(value)) > 2, 1, data_check),
         data_check = if_else(is.na(data_check), lag(data_check), data_check),
         value = as.character(value)) %>% 
  filter(data_check == 1) %>% 
  select(area, home, winter_id, var, value)

write_csv(home_char_check_num, paste0(file_path, "Output/home_char_check_num.csv"))
  
  
  
home_char_check_fact <- home_char_clean %>% 
  group_by(home) %>% 
  arrange(home, winter_id) %>% 
  pivot_longer(cols = c(home_type, stove_age, stove_cert, home_fireplace:home_insert), 
               names_to = "var", values_to = "value") %>% 
  group_by(home, var) %>% 
  arrange(home, var, winter_id) %>% 
  mutate(data_check = if_else(value == lead(value), 1, 0),
         data_check = if_else(is.na(data_check), lag(data_check), data_check)) %>% 
  filter(data_check == 0) %>% 
  select(area, home, winter_id, var, value) %>% 
  mutate(var2 = var,
         value2 = value) %>% 
  pivot_wider(names_from = "var2", values_from = "value2") %>% 
  ungroup() %>% 
  mutate_at(c("home_insert", "stove_age", "home_furnace", "home_woodstove", 
              "stove_cert", "home_type", "home_fireplace"), as.character) %>% 
  mutate_at(c("home_insert", "stove_age", "home_furnace", "home_woodstove", 
              "stove_cert", "home_type", "home_fireplace"), as.factor) %>% 
  mutate_at(c("home_insert", "stove_age", "home_furnace", "home_woodstove", 
              "stove_cert", "home_type", "home_fireplace"), as.numeric)
  
home_char_check_fact$value_num <- 
  coalesce(home_char_check_fact$home_insert, 
           home_char_check_fact$stove_age, 
           home_char_check_fact$home_furnace, 
           home_char_check_fact$home_woodstove, 
           home_char_check_fact$stove_cert, 
           home_char_check_fact$home_type, 
           home_char_check_fact$home_fireplace)

home_char_check_fact2 <- home_char_check_fact %>% 
  select(area, home, winter_id, var, value, value_num) %>% 
  group_by(home, var) %>% 
  mutate(data_check = if_else(abs(value_num - lead(value_num)) > 1, 1, 0),
         data_check = if_else(is.na(data_check), lag(data_check), data_check),
         value = as.character(value)) 

write_csv(home_char_check_fact2, paste0(file_path, "Output/home_char_check_fact.csv"))

home_char_check <- rbind(home_char_check_num, home_char_check_fact2) %>% 
  arrange(home, var, winter_id) %>% 
  mutate(data_check = if_else(is.na(value_num), 1, data_check))

write_csv(home_char_check, paste0(file_path, "Output/home_char_check.csv"))
```


```{r, include=FALSE}
# Summarize numeric vars
home_char_summary <- home_char_clean %>% 
  #filter(winter_id == 1 | winter_id == 2) %>% 
  filter(winter_id == 1 & treatment == "Placebo") %>% 
  group_by(area) %>% 
  summarize("N" = n(),
            "Mean Sqft" = mean(home_sqft, na.rm = TRUE), 
            "SD Sqft" = sd(home_sqft, na.rm = TRUE), 
            "Min Sqft" = min(home_sqft, na.rm = TRUE), 
            "Median Sqft" = median(home_sqft, na.rm = TRUE), 
            "Max Sqft" = max(home_sqft, na.rm = TRUE))
kable(home_char_summary, digits = 1, align = "c")

# Summarize factor vars
## Use this as a quick look at all vars
table_list <- home_char_clean %>%  
  filter(winter_id == 1 | winter_id == 2) %>% 
  filter(residents_total != 0) %>% 
  #filter(area == "WMT") %>% 
  select(-home_winter_id, -home_sqft, -stove_model, -home_id, -home, -treatment) 
#lapply(table_list, table)

## Select specific var to assess individually/group by area
table(table_list$winter_id, table_list$area, table_list$home_type, useNA = "ifany")

table(home_char_summary$stove_age)
```


```{r}
table(home_char_clean$primary_heat, home_char_clean$secondary_heat, home_char_clean$area,
      dnn = c("primary heating", "secondary heating", "area"))
```


```{r, include=FALSE}
# Summarize factor vars
## Use this as a quick look at all vars
table_list <- home_act_clean %>% 
  filter(winter_id == 1) %>% 
  #filter(area == "WMT") %>% 
  select(-home_winter_id, -home_act_comments, -home_id, -home, -treatment) 
#lapply(table_list, table)

## Select specific var to assess individually/group by area
#table(table_list$home_act_sweep, table_list$area, useNA = "ifany")
```


```{r}
home_char_filtered <- read_rds("Output/home_char_clean.rds") %>% 
  mutate(chimney_clean = factor(chimney_clean,
                                levels = c("Less than 6 months ago",
                                           "6-12 months ago", "12-18 months ago",
                                           "More than 18 months ago"),
                                labels = c("< 6 months ago",
                                           "6-12 months ago", "12-18 months ago",
                                           "> 18 months ago")),
         stove_age = factor(stove_age,
                            levels = c("0-5 years old", "6-10 years old",
                                       "11-15 years old", "16 + years old",
                                       "Do not know")))
```


```{r, fig.height=8}
home_char_plot <- home_char_filtered %>% 
  filter(winter_id == 1 & treatment == "Placebo") %>% 
  select(area, residents_smoke, residents_smoke_inside, home_damp:home_insert) %>% 
  pivot_longer(cols = c("residents_smoke":"home_insert"), names_to = "var") %>% 
  filter(!is.na(value)) %>% 
  ggplot() +
    geom_bar(aes(value, fill = area)) +
    theme_minimal() +
    theme(strip.text = element_text(size = 16, colour = "black"),
          axis.text.x = element_text(size = 14, colour = "black", 
                                     angle = 25, vjust = 0.6),
          legend.text = element_text(size = 16, colour = "black"),
          legend.title = element_text(size = 16, colour = "black"),
          axis.text.y = element_text(size = 16, colour = "black"),
          axis.title.y = element_text(size = 16, colour = "black"),
          axis.title.x = element_blank(),
          axis.line.x = element_line(colour = "black", size = 1.2), 
          axis.line.y = element_line(colour = "black", size = 1.2), 
          axis.ticks = element_blank()) +
    facet_wrap(~var, ncol = 2) +
    scale_fill_manual(values = jv_palette)
home_char_plot
```


```{r}
home_char_function <- function(data, var, title_label, y_label) {
  
  home_char_plot <- data %>% 
  filter(winter_id == 1) %>% 
  select(area, var) %>% 
  rename(plot_var = var) %>% 
  filter(!is.na(plot_var)) %>% 
  ggplot() +
    geom_bar(aes(plot_var, fill = area)) +
    theme_minimal() +
    theme(axis.text.x = element_text(size = 16, colour = "black", 
                                     angle = 40, vjust = 0.7, hjust = 0.7),
          axis.text.y = element_text(size = 16, colour = "black"),
          title = element_text(size = 20, colour = "black"),
          legend.text = element_text(size = 18, colour = "black"),
          legend.title = element_text(size = 18, colour = "black"),
          axis.title.y = element_text(size = 18, colour = "black"),
          axis.title.x = element_blank(),
          axis.line.x = element_line(colour = "black", size = 1.2), 
          axis.line.y = element_line(colour = "black", size = 1.2), 
          axis.ticks = element_blank(),
          panel.grid = element_blank()) +
    labs(title = title_label) +
    ylab(y_label) +
    scale_fill_manual(values = jv_palette)
  home_char_plot
  
}

home_char_function(home_char_filtered, "residents_smoke", "Residents smoke", "count")
home_char_function(home_char_filtered, "residents_smoke_inside", "Residents smoke inside", "count")
home_char_function(home_char_filtered, "home_type", "Home type", "count")
home_char_function(home_char_filtered, "home_floors", "Floors in home", "count")
home_char_function(home_char_filtered, "home_windows", "Windows in home", "count")
home_char_function(home_char_filtered, "home_bedrooms", "Bedrooms in home", "count")
home_char_function(home_char_filtered, "home_pets", "Pets in home", "count")
home_char_function(home_char_filtered, "home_furry", "Furry pet in home", "count")
home_char_function(home_char_filtered, "primary_heat", "Primary heat", "count")
home_char_function(home_char_filtered, "secondary_heat", "Secondary heat", "count")
home_char_function(home_char_filtered, "stove_age", "Stove age", "count")
home_char_function(home_char_filtered, "stove_cert", "Stove EPA certified", "count")
home_char_function(home_char_filtered, "chimney_clean", "Chimney last cleaned", "count")
home_char_function(home_char_filtered, "home_mold", "Home mold", "count")
home_char_function(home_char_filtered, "home_damp", "Home damp", "count")
home_char_function(home_char_filtered, "home_fireplace", "Home fireplace", "count")
home_char_function(home_char_filtered, "home_furnace", "Home furnace", "count")
```

```{r, fig.height=8}
home_act_plot <- home_act_clean %>% 
  filter(winter_id == 1 & treatment == "Placebo") %>% 
  select(area, home_act_gas:home_act_sweep) %>% 
  pivot_longer(cols = c("home_act_gas":"home_act_sweep"), names_to = "var") %>% 
  filter(!is.na(value)) %>% 
  ggplot() +
    geom_bar(aes(value, fill = area)) +
    theme_minimal() +
    theme(strip.text = element_text(size = 16, colour = "black"),
          axis.text.x = element_text(size = 14, colour = "black", 
                                     angle = 25, vjust = 0.6),
          legend.text = element_text(size = 16, colour = "black"),
          legend.title = element_text(size = 16, colour = "black"),
          axis.text.y = element_text(size = 16, colour = "black"),
          axis.title.y = element_text(size = 16, colour = "black"),
          axis.title.x = element_blank(),
          axis.line.x = element_line(colour = "black", size = 1.2), 
          axis.line.y = element_line(colour = "black", size = 1.2), 
          axis.ticks = element_blank()) +
    facet_wrap(~var, ncol = 2) +
    scale_fill_manual(values = jv_palette)
home_act_plot
```


```{r}
home_act_function <- function(data, var, title_label, y_label) {
  
  home_act_plot <- data %>% 
  filter(winter_id == 1) %>% 
  select(area, var) %>% 
  rename(plot_var = var) %>% 
  filter(!is.na(plot_var)) %>% 
  ggplot() +
    geom_bar(aes(plot_var, fill = area)) +
    theme_minimal() +
    theme(axis.text.x = element_text(size = 16, colour = "black", 
                                     angle = 40, vjust = 0.7, hjust = 0.7),
          axis.text.y = element_text(size = 16, colour = "black"),
          title = element_text(size = 20, colour = "black"),
          legend.text = element_text(size = 18, colour = "black"),
          legend.title = element_text(size = 18, colour = "black"),
          axis.title.y = element_text(size = 18, colour = "black"),
          axis.title.x = element_blank(),
          axis.line.x = element_line(colour = "black", size = 1.2), 
          axis.line.y = element_line(colour = "black", size = 1.2), 
          axis.ticks = element_blank(),
          panel.grid = element_blank()) +
    labs(title = title_label) +
    ylab(y_label) +
    scale_fill_manual(values = jv_palette)
  home_act_plot
  
}

home_act_function(home_act_clean, "home_act_gas", "Gas appliance used", "count")
home_act_function(home_act_clean, "home_act_elect", "Electric appliance used", "count")
home_act_function(home_act_clean, "home_act_propane", "Propane appliance used", "count")
home_act_function(home_act_clean, "home_act_oil", "Oil appliance used", "count")
home_act_function(home_act_clean, "home_act_smoking", "Smoking in home", "count")
home_act_function(home_act_clean, "home_act_incense", "Incense burned", "count")
home_act_function(home_act_clean, "home_act_candle", "Candle burned", "count")
home_act_function(home_act_clean, "home_act_kerosene", "Kerosene burned", "count")
home_act_function(home_act_clean, "home_act_windows", "Windows open", "count")
home_act_function(home_act_clean, "home_act_door", "Doors open", "count")
home_act_function(home_act_clean, "home_act_sweep", "Sweeping/cleaning/vacuuming", "count")
```


```{r, include=FALSE, eval=FALSE}
#### Abstract/manuscript tables ####

# Filter for homes that have PM data

# 93 Winter 1 placebo homes have PM data
pm_homes_placebo <- pm_clean %>% 
  filter(winter_id == 1) %>% 
  filter(treatment == "Placebo") %>% 
  group_by(area, home) %>% 
  mutate(initial_obs = if_else(pm_datetime_new == first_datetime_new, 1, 0)) %>% 
  filter(initial_obs == 1) %>% 
  mutate(pm_home = "true") %>% 
  select(area, home, home_winter_id, pm_home) %>% 
  ungroup() %>% 
  arrange(area, home)

home_char_filtered <- home_char_clean %>% 
  # change to correct joining data of interest
  left_join(pm_homes_placebo, by = c("area", "home", "home_winter_id")) %>% 
  filter(pm_home == "true") %>% 
  filter(winter_id == 1) %>% 
  ungroup() %>% 
  arrange(area, home)

home_act_filtered <- home_act_clean %>% 
  # change to correct joining data of interest
  left_join(pm_homes_placebo, by = c("area", "home", "home_winter_id")) %>% 
  filter(pm_home == "true") %>% 
  filter(winter_id == 1) %>% 
  ungroup() %>% 
  arrange(area, home)
```

```{r, include=FALSE, eval=FALSE}
# Summarize numeric vars
kids_char <- home_char_filtered %>%  
  distinct(home, .keep_all = TRUE) %>%  
  group_by(area) %>% 
  summarize("Mean" = mean(home_furry, na.rm = TRUE), 
            "SD" = sd(home_furry, na.rm = TRUE),
            "min" = min(home_furry, na.rm = TRUE), 
            "max" = max(home_furry, na.rm = TRUE))
kable(kids_char, digits = 1, align = "c")


home_char_filtered %>% 
  count(stove_age)


# Summarize factor vars
alaska_char <- home_act_filtered %>%  
  #distinct(home, .keep_all = TRUE) %>% 
  filter(area == "AK") %>% 
  group_by(home_act_sweep) %>% 
  #summarize(n = n(), percent = (n()/10)*100)
  summarize(n = n(), percent = (n()/60)*100)
alaska_char

navajo_char <- home_act_filtered %>%  
  #distinct(home, .keep_all = TRUE) %>% 
  filter(area == "NN") %>% 
  group_by(home_act_sweep) %>% 
  #summarize(n = n(), percent = (n()/23)*100)
  summarize(n = n(), percent = (n()/138)*100)
navajo_char

montana_char <- home_act_filtered %>%  
  #distinct(home, .keep_all = TRUE) %>% 
  filter(area == "WMT") %>% 
  group_by(home_act_sweep) %>% 
  #summarize(n = n(), percent = (n()/60)*100)
  summarize(n = n(), percent = (n()/360)*100)
montana_char

kids_char <- rbind(alaska_char, navajo_char, montana_char)
kids_char
```

