---
title: "KidsAIR: Join data and format full dataset"
author: "Ethan Walker"
date: "Started 14 Jan 2020, Updated 14 Jan 2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
library(tidyverse)
library(readxl)
library(naniar)
library(lubridate)
library(zoo)
```
# Use this Markdown to join datasets for analysis

# Load individual datasets
```{r}
# These files are millions of observations long and take time to load/edit
# Make a separate way to join these data and only use when necessary
# Also consider how to join/analyze these data since they were collected
# at different frequencies (20 or 25 min for SUMs; 1 min for PM)
pm_clean <- read_rds("Output/pm_clean.rds")
sums_clean <- read_rds("Output/sums_clean.rds")

# These other files have fewer observations and are easier to work with
# Make a full dataset by joining these datasets together
kids_linked_ids <- read_rds("Output/kids_linked_ids.rds")
demographics_clean <- read_rds("Output/demographics_clean.rds")
moisture_clean <- read_rds("Output/moisture_clean.rds")
indoor_temp_rh_clean <- read_rds("Output/indoor_temp_rh_clean.rds")
stove_use_clean <- read_rds("Output/stove_use_clean.rds")
stove_grades_clean <- read_rds("Output/stove_grades_clean.rds")
home_char_clean <- read_rds("Output/home_char_clean.rds")
home_act_clean <- read_rds("Output/home_act_clean.rds")
```

# Join small datasets
```{r}

```

# Format small dataset
```{r}

```

# Join SUMs and DustTrak datasets
## Fix vars/dates in data dictionary once finalized
```{r}
pm_join <- read_rds("Output/pm_clean.rds") %>% 
  mutate(sample_datetime = ymd_hms(pm_datetime_new)) %>% 
  separate(sample_datetime, c("sample_date", "sample_time"), sep = " ", remove = FALSE) %>% 
  group_by(area, home) %>% 
  arrange(sample_datetime) %>% 
  mutate(pm_last_datetime = last(sample_datetime),
         pm_first_datetime = first_datetime_new,
         sample_datetime = round_date(sample_datetime, unit = "minute"),
         pm_rolling_20 = rollmean(pm, 20, fill = "extend")) %>% 
  ungroup() %>% 
  arrange(area, home, sample_datetime) 

sums_join <- read_rds("Output/sums_clean.rds") %>% 
  mutate(sample_datetime = ymd_hms(datetime_sums)) %>% 
  separate(sample_datetime, c("sample_date", "sample_time"), sep = " ", remove = FALSE) %>% 
  mutate(sample_datetime = round_date(sample_datetime, unit = "minute")) %>% 
  ungroup() %>% 
  arrange(area, home, sample_datetime)

pm_sums_joined <- sums_join %>% 
  left_join(pm_join, by = c("area", "home", "sample_datetime")) %>% 
  filter(pm_rolling_20 < 1000)

cor.test(pm_sums_joined$temp_c_sums, pm_sums_joined$pm_rolling_20, method = "spearman")
pm_sums_model <- lm(log(pm_sums_joined$pm_rolling_20) ~ pm_sums_joined$temp_c_sums)

summary(pm_sums_model)
exp((0.0235293)-1)*100
plot(pm_sums_model)
plot(pm_sums_joined$pm_rolling_20, pm_sums_joined$temp_c_sums)
```



