---
title: "KidsAIR: Main analysis initial steps"
author: "Ethan Walker"
date: "Started 23 Sept 2020, Updated 6 Nov 2020"
output: pdf_document
header-includes:
    - \usepackage[labelformat=empty]{caption}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = FALSE, include = FALSE,
                      message = FALSE, warning = FALSE)
```

```{r, eval=TRUE, include=TRUE}
library(readxl)
library(naniar)
library(lubridate)
library(broom)
library(broom.mixed)
library(zoo)
library(lme4)
library(lmerTest)
library(mctest)
library(tidyverse)
library(knitr)
library(kableExtra)
```


```{r, eval=TRUE, include=TRUE}
# Load individual datasets, add new vars, and merge/select analysis dataset

file_path <- c("C:/Users/ethan.walker/Box/Ethan Walker UM/R/KidsAIR/")


health_exposure_data_sampling_day <- 
  read_rds(paste0(file_path, "Output/health_exposure_data_sampling_day.rds"))


treatments_masked <- read_csv(paste0(file_path, "Input/KidsAIRrnd_masked.csv"), na = "NULL") %>% 
  mutate(home = gsub(" ", "", x = home),
         home = gsub("_", "", x = home))


kids_amb_pm_data <- 
  read_rds(paste0(file_path, "Output/kids_amb_pm_data_new.rds")) %>% 
  mutate(sample_date = ymd(amb_pm_date))


kids_amb_temp_data <- 
  read_rds(paste0(file_path, "Output/kids_amb_temp_data_new.rds")) %>% 
  mutate(sample_date = ymd(temp_date)) 


# Condense LRTI data to 1 obs per child/winter and select analysis vars
lrti_1obs_per_winter <- read_rds(paste0(file_path, "Output/lrti_final_data.rds")) %>% 
  arrange(area, home, child_id_num, winter_id) %>% 
  mutate(cohort = round_date(csq_date, unit = "year")) %>% 
  separate(cohort, c("cohort", "trash"), sep = "-") %>% 
  group_by(area, child_id_num, winter_id) %>% 
  mutate(lrti_events_winter = n(),
         lrti_events_winter = as.numeric(lrti_events_winter),
         lrti_events_winter = if_else(is.na(person_time_lrti), 0, lrti_events_winter),
         person_time_lrti_winter = sum(person_time_lrti),
         person_time_no_lrti_winter = as.numeric(person_time_possible - person_time_lrti_winter),
         person_time_no_lrti_winter = if_else(is.na(person_time_no_lrti_winter), person_time_possible,
                                             person_time_no_lrti_winter),
         person_time_at_risk_winter = as.numeric(person_time_no_lrti_winter)/7,
         lrti_incidence_winter = lrti_events_winter/person_time_at_risk_winter,
         lrti_incidence_winter = if_else(is.na(lrti_incidence_winter), 0, lrti_incidence_winter)) %>% 
  arrange(area, home, child_id_num, winter_id) %>%
  distinct(area, child_id_num, winter_id, .keep_all = TRUE) %>% 
  ungroup() %>% 
  dplyr::select(area, home, cohort, child_id_num, winter_id, 
                lrti_events_winter, person_time_at_risk_winter, lrti_incidence_winter) 


# Condense LRTI data to 1 obs per child and select analysis vars
lrti_1obs_total <- read_rds(paste0(file_path, "Output/lrti_final_data.rds")) %>% 
  arrange(area, home, child_id_num, winter_id) %>% 
  mutate(cohort = round_date(csq_date, unit = "year")) %>% 
  separate(cohort, c("cohort", "trash"), sep = "-") %>% 
  group_by(area, child_id_num, winter_id) %>% 
  mutate(lrti_events = n()) %>% 
  distinct(area, child_id_num, winter_id, .keep_all = TRUE) %>% 
  group_by(area, child_id_num) %>% 
  mutate(lrti_events = as.numeric(lrti_events),
         lrti_events = if_else(is.na(person_time_no_lrti_total), 0, lrti_events),
         lrti_events_total = sum(lrti_events, na.rm = TRUE),
         person_time_no_lrti_total = as.numeric(person_time_no_lrti_total),
         person_time_no_lrti_total = if_else(is.na(person_time_no_lrti_total), person_time_possible,
                                             person_time_no_lrti_total),
         person_time_at_risk_total = sum(person_time_no_lrti_total, na.rm = TRUE),
         person_time_at_risk_total = as.numeric(person_time_at_risk_total)/7,
         lrti_incidence_total = lrti_events_total/person_time_at_risk_total,
         lrti_incidence_total = if_else(is.na(lrti_incidence_total), 0, lrti_incidence_total)) %>% 
  arrange(area, home, child_id_num, winter_id) %>% 
  left_join(kids_amb_pm_data, by = c("area", "home")) %>% 
  mutate(pm_filter = if_else(sample_date >= person_time_start & sample_date <= person_time_end, 1, 0)) %>% 
  filter(pm_filter == 1) %>% 
  group_by(area, child_id_num) %>% 
  mutate(amb_pm_lrti = mean(amb_pm_24hr, na.rm = TRUE)) %>% 
  distinct(area, child_id_num, winter_id, .keep_all = TRUE) %>% 
  ungroup() %>% 
  dplyr::select(area, home, cohort, child_id_num, lrti_events_total, person_time_at_risk_total, lrti_incidence_total,
         amb_pm_lrti, person_time_start, person_time_end, home_winter_id, winter_id) %>% 
  left_join(kids_amb_temp_data, by = c("area", "home")) %>% 
  mutate(temp_filter = if_else(sample_date >= person_time_start & sample_date <= person_time_end, 1, 0)) %>% 
  filter(temp_filter == 1 | child_id_num == 94) %>% 
  group_by(area, child_id_num) %>% 
  mutate(amb_temp_lrti = mean(mean_temp, na.rm = TRUE),
         amb_temp_lrti = if_else(child_id_num == 94, NaN, amb_temp_lrti),
         amb_dewp_lrti = mean(mean_dewp, na.rm = TRUE),
         amb_dewp_lrti = if_else(child_id_num == 94, NaN, amb_dewp_lrti),
         amb_pressure_lrti = mean(mean_pressure, na.rm = TRUE),
         amb_pressure_lrti = if_else(child_id_num == 94, NaN, amb_pressure_lrti),
         amb_wind_lrti = mean(mean_wind_knots, na.rm = TRUE),
         amb_wind_lrti = if_else(child_id_num == 94, NaN, amb_wind_lrti)) %>% 
  ungroup() %>% 
  dplyr::select(area, home, cohort, child_id_num, winter_id,
                lrti_events_total, person_time_at_risk_total, lrti_incidence_total,
         amb_pm_lrti, amb_temp_lrti, amb_dewp_lrti, amb_pressure_lrti, amb_wind_lrti) %>% 
  distinct(area, child_id_num, .keep_all = TRUE) %>% 
  ungroup() %>% 
  dplyr::select(area, home, cohort, child_id_num, lrti_events_total, person_time_at_risk_total, lrti_incidence_total,
         amb_pm_lrti, amb_temp_lrti, amb_dewp_lrti, amb_pressure_lrti, amb_wind_lrti) 


# Merge dataset with blinded treatments and final LRTI data, select analysis variables
kids_analysis_data_1obs_per_child <- health_exposure_data_sampling_day %>% 
  #select(-treatment_assigned, -treatment_actual) %>% 
  mutate(child_age = fct_collapse(age_child_nov,
                                  "< 1" = "Less than 1",
                                  "1+" = c(1, 2, 3, 4))) %>% 
  left_join(treatments_masked, by = "home") %>% 
  arrange(area, home, child_id_num, winter_id, age_child_nov) %>% 
  right_join(lrti_1obs_total, by = c("area", "home", "child_id_num")) %>% 
  distinct(area, child_id_num, .keep_all = TRUE) %>% 
  dplyr::select(area, home, cohort, child_id_num, child_age, lrti_events_total, 
         person_time_at_risk_total, lrti_incidence_total, newtx, treatment_assigned,
         amb_pm_lrti, amb_temp_lrti, amb_dewp_lrti, amb_pressure_lrti, amb_wind_lrti, gender,
         gender_parent, hispanic_parent, race_parent, education_3level, income_3level,
         home_floors_2level, home_year_built_2level, home_pets_2level, home_pets,
         stove_age_3level, chimney_clean_3level, wood_collect_method_2level, home_sqft_2level,
         wood_collect_2level, stove_grade_3level, burn_level_3level, ruca_code,
         ruca_code_2, ruca_code_3, residents_smoke, residents_smoke_inside,
         residents_under_five, home_bedrooms, pm_mean_sampling_period, 
         pm_sample_interval, pm_at_home_sampling_period,
         moisture_closest, temp_indoor_max, rh_indoor_max, sums_events_sampling_period_2.5,
         sums_events_sampling_period_5, sums_events_sampling_period_7.5,
         home_act_smoking_sum, home_act_windows_sum, home_act_sweep_sum, home_act_door_sum) %>% 
  rename(treatment = newtx,
         person_time_at_risk = person_time_at_risk_total) %>% 
  mutate(log_person_time_at_risk = log(person_time_at_risk)) %>% 
  mutate(lrti_events_di_total = if_else(lrti_events_total == 0, 0, 1)) %>% 
  mutate(treatment = factor(treatment,
                            levels = c("Blackfoot", "Dearborn", "Smith")),
         treatment_assigned = factor(treatment_assigned,
                                     levels = c("Placebo", "Filter", "Education"))) 

write_rds(kids_analysis_data_1obs_per_child, 
          paste0(file_path, "Output/kids_analysis_data_1obs_per_child.rds"))
write_csv(kids_analysis_data_1obs_per_child, 
          paste0(file_path, "Output/kids_analysis_data_1obs_per_child.csv"), na = "")



kids_analysis_data_2obs_per_child <- health_exposure_data_sampling_day %>% 
  #select(-treatment_assigned, -treatment_actual) %>% 
  mutate(child_age = fct_collapse(age_child_nov,
                                  "< 1" = "Less than 1",
                                  "1+" = c(1, 2, 3, 4))) %>% 
  left_join(treatments_masked, by = "home") %>% 
  arrange(area, home, child_id_num, winter_id, age_child_nov) %>% 
  right_join(lrti_1obs_per_winter, by = c("area", "home", "child_id_num", "winter_id")) %>% 
  distinct(area, child_id_num, winter_id, .keep_all = TRUE) %>% 
  dplyr::select(area, home, cohort, child_id_num, home_winter_id, winter_id, child_age, gender,
         lrti_events_winter, person_time_at_risk_winter, lrti_incidence_winter, newtx, treatment_assigned,
         gender_parent, hispanic_parent, race_parent, education_3level, income_3level,
         home_floors_2level, home_year_built_2level, home_pets_2level, home_pets,
         stove_age_3level, chimney_clean_3level, wood_collect_method_2level, home_sqft_2level,
         wood_collect_2level, stove_grade_3level, burn_level_3level, ruca_code,
         ruca_code_2, ruca_code_3, residents_smoke, residents_smoke_inside,
         residents_under_five, home_bedrooms, pm_mean_sampling_period, 
         pm_sample_interval, pm_at_home_sampling_period,
         moisture_closest, temp_indoor_max, rh_indoor_max, sums_events_sampling_period_2.5,
         sums_events_sampling_period_5, sums_events_sampling_period_7.5,
         home_act_smoking_sum, home_act_windows_sum, home_act_sweep_sum, home_act_door_sum) %>% 
  rename(treatment = newtx) %>% 
  mutate(log_person_time_at_risk_winter = log(person_time_at_risk_winter)) %>% 
  mutate(lrti_events_di_winter = if_else(lrti_events_winter == 0, 0, 1)) %>% 
  mutate(treatment = factor(treatment,
                            levels = c("Blackfoot", "Dearborn", "Smith")),
         treatment_assigned = factor(treatment_assigned,
                                     levels = c("Placebo", "Filter", "Education"))) 

write_rds(kids_analysis_data_2obs_per_child, 
          paste0(file_path, "Output/kids_analysis_data_2obs_per_child.rds"))
write_csv(kids_analysis_data_2obs_per_child, 
          paste0(file_path, "Output/kids_analysis_data_2obs_per_child.csv"), na = "")
```


```{r}
# Load analysis dataset

file_path <- c("C:/Users/ethan.walker/Box/Ethan Walker UM/R/KidsAIR/")

analysis_data <- read_rds(paste0(file_path, 
                                 "Output/kids_analysis_data_1obs_per_child.rds")) %>% 
  rownames_to_column() %>% 
  mutate(filter_outliers = if_else(rowname %in% c(14, 57, 58, 249, 280, 16, 19, 20, 118), 1, 0)) %>% 
  filter(lrti_incidence < 0.7) %>% 
  filter(filter_outliers == 0)

health_exposure_data_sampling_day <- 
  read_rds(paste0(file_path, "Output/health_exposure_data_sampling_day.rds")) %>% 
  mutate(home_pets = as.factor(home_pets),
         home_pets_3level = fct_collapse(home_pets,
                                    "0" = "0",
                                    "1" = "1",
                                    "2+" = c("2","3","4","5","6","7","8","9","10","12","14")))

treatments_masked <- read_csv(paste0(file_path, "Input/KidsAIRrnd_masked.csv"), na = "NULL") %>% 
  mutate(home = gsub(" ", "", x = home),
         home = gsub("_", "", x = home))
```


```{r}
# Summary analysis for categorical variables

# clean up data for table 1 summary
table_1_data <- health_exposure_data_sampling_day %>% 
  mutate(treatment_assigned = factor(treatment_assigned,
                                     levels = c("Placebo", "Filter", "Education"))) %>% 
    #select(-treatment_assigned, -treatment_actual) %>% 
  #left_join(treatments_masked, by = "home") %>%
  #rename(treatment = newtx) %>% 
  arrange(area, home, winter_id, sampling_day) %>% 
  filter(winter_id == 1) %>% 
  filter(area == "AK") %>% # Change area filter as necessary
  distinct(area, home, .keep_all = TRUE) 


# summary data for manuscript tables
char_funct_total <- function(var, data = table_1_data){

demographics_summary <- data %>% 
  rename(new_var = var) %>% 
  mutate(total_n = n()) %>% 
  group_by(new_var) %>% 
  mutate(n = n(),
         percent = round(n()/total_n*100)) %>% 
  distinct(new_var, .keep_all = TRUE) %>% 
  dplyr::select(new_var, n, percent) %>% 
  arrange(new_var)
demographics_summary
}

char_funct_treatment <- function(var, data = table_1_data){

demographics_summary <- data %>% 
  rename(new_var = var) %>% 
  group_by(treatment_assigned) %>% 
  mutate(treatment_n = n()) %>% 
  group_by(treatment_assigned, new_var) %>% 
    mutate(n = n(),
         percent = round(n()/treatment_n*100)) %>% 
  distinct(new_var, .keep_all = TRUE) %>% 
  dplyr::select(new_var, n, percent) %>% 
  arrange(treatment_assigned, new_var)
demographics_summary
}



char_funct_total("gender_parent")
char_funct_treatment("gender_parent")
char_funct_total("race_parent")
char_funct_treatment("race_parent")
char_funct_total("education_3level")
char_funct_treatment("education_3level")
char_funct_total("income_3level")
char_funct_treatment("income_3level")
char_funct_total("home_floors_2level")
char_funct_treatment("home_floors_2level")
char_funct_total("home_year_built_2level")
char_funct_treatment("home_year_built_2level")
char_funct_total("home_pets_2level")
char_funct_treatment("home_pets_2level")
char_funct_total("home_pets_3level")
char_funct_treatment("home_pets_3level")
char_funct_total("residents_smoke")
char_funct_treatment("residents_smoke")
char_funct_total("residents_smoke_inside")
char_funct_treatment("residents_smoke_inside")
char_funct_total("stove_age_3level")
char_funct_treatment("stove_age_3level")
char_funct_total("chimney_clean_3level")
char_funct_treatment("chimney_clean_3level")
char_funct_total("wood_collect_method_2level")
char_funct_treatment("wood_collect_method_2level")
char_funct_total("wood_collect_2level")
char_funct_treatment("wood_collect_2level")
char_funct_total("stove_grade_3level")
char_funct_treatment("stove_grade_3level")
char_funct_total("burn_level_3level")
char_funct_treatment("burn_level_3level")
char_funct_total("ruca_code")
char_funct_treatment("ruca_code")
char_funct_total("ruca_code_2")
char_funct_treatment("ruca_code_2")
char_funct_total("ruca_code_3")
char_funct_treatment("ruca_code_3")
char_funct_total("home_act_smoking_sum")
char_funct_treatment("home_act_smoking_sum")
char_funct_total("home_act_windows_sum")
char_funct_treatment("home_act_windows_sum")
char_funct_total("home_act_sweep_sum")
char_funct_treatment("home_act_sweep_sum")
char_funct_total("home_act_door_sum")
char_funct_treatment("home_act_door_sum")
```


```{r}
# Summary analysis for numeric variables

# clean up data for table 1 summary
table_1_data <- health_exposure_data_sampling_day %>% 
  mutate(treatment_assigned = factor(treatment_assigned,
                                     levels = c("Placebo", "Filter", "Education"))) %>% 
  #select(-treatment_assigned, -treatment_actual) %>% 
  #left_join(treatments_masked, by = "home") %>%
  #rename(treatment = newtx) %>% 
  arrange(area, home, winter_id, sampling_day) %>% 
  filter(winter_id == 1) %>% 
  #filter(area == "AK") %>% # Change area filter as necessary
  distinct(area, home, .keep_all = TRUE) 


# summary data for manuscript tables
num_funct_total <- function(var, data = table_1_data){

demographics_summary <- data %>% 
  rename(new_var = var) %>% 
  mutate(new_var = as.numeric(new_var)) %>% 
  #mutate(new_var = (as.numeric(new_var)-32)*5/9) %>% 
  filter(!is.na(new_var)) %>% 
  select(treatment_assigned, home, new_var) %>% 
  summarize(mean_var = mean(new_var), sd_var = sd(new_var), n_var = n(), 
            min_var = min(new_var), med_var = median(new_var), max_var = max(new_var))
demographics_summary
}

num_funct_treatment <- function(var, data = table_1_data){

demographics_summary <- data %>% 
  rename(new_var = var) %>%
  mutate(new_var = as.numeric(new_var)) %>% 
  #mutate(new_var = (as.numeric(new_var)-32)*5/9) %>%
  filter(!is.na(new_var)) %>% 
  select(treatment_assigned, home, new_var) %>% 
  group_by(treatment_assigned) %>% 
  summarize(mean_var = mean(new_var), sd_var = sd(new_var), n_var = n(), 
            min_var = min(new_var), med_var = median(new_var), max_var = max(new_var))
demographics_summary
}


num_funct_total("residents_under_five")
num_funct_treatment("residents_under_five")
num_funct_total("home_bedrooms")
num_funct_treatment("home_bedrooms")
num_funct_total("pm_mean_sampling_period")
num_funct_treatment("pm_mean_sampling_period")
num_funct_total("pm_sample_interval")
num_funct_treatment("pm_sample_interval")
num_funct_total("moisture_closest")
num_funct_treatment("moisture_closest")
num_funct_total("temp_indoor_max")
num_funct_treatment("temp_indoor_max")
num_funct_total("rh_indoor_max")
num_funct_treatment("rh_indoor_max")
num_funct_total("mean_temp")
num_funct_treatment("mean_temp")
num_funct_total("amb_pm_24hr")
num_funct_treatment("amb_pm_24hr")
num_funct_total("sums_events_sampling_period_2.5")
num_funct_treatment("sums_events_sampling_period_2.5")
num_funct_total("sums_events_sampling_period_5")
num_funct_treatment("sums_events_sampling_period_5")
num_funct_total("sums_events_sampling_period_7.5")
num_funct_treatment("sums_events_sampling_period_7.5")
num_funct_total("home_act_smoking_sum")
num_funct_treatment("home_act_smoking_sum")
num_funct_total("home_act_windows_sum")
num_funct_treatment("home_act_windows_sum")
num_funct_total("home_act_sweep_sum")
num_funct_treatment("home_act_sweep_sum")
num_funct_total("home_act_door_sum")
num_funct_treatment("home_act_door_sum")
num_funct_total("home_act_incense_sum")
num_funct_treatment("home_act_candle_sum")

# At-home PM summary - different than function above due to distinct obs by child instead of home
at_home_pm_summary <- health_exposure_data_sampling_day %>% 
  select(-treatment_assigned, -treatment_actual) %>% 
  left_join(treatments_masked, by = "home") %>%
  rename(treatment = newtx) %>% 
  arrange(area, home, winter_id, sampling_day) %>% 
  filter(winter_id == 1) %>% 
  distinct(area, child_id_num, .keep_all = TRUE) %>% 
  mutate(new_var = pm_at_home_sampling_period) %>% 
  filter(!is.na(new_var)) %>%
  filter(area == "NN") %>% # Change area filter as necessary 
  group_by(treatment) %>% # Change treatment grouping as necessary 
  summarize(mean_var = mean(new_var), sd_var = sd(new_var), n_var = n(), 
            min_var = min(new_var), med_var = median(new_var), max_var = max(new_var))
at_home_pm_summary
```


```{r}
# Summary for outcome events and ambient data

# Initial summary data for LRTI
incidence_summary <- analysis_data %>% 
  filter(area == "NN") %>% # Change area filter as necessary  
  #group_by(treatment) %>% # Change treatment grouping as necessary  
  #filter(lrti_incidence < 0.7) %>% 
  summarize(mean_inc = mean(lrti_incidence, na.rm = TRUE),
            sd_inc = sd(lrti_incidence, na.rm = TRUE),
            n_inc = n(),
            min_inc = min(lrti_incidence, na.rm = TRUE),
            median_inc = median(lrti_incidence, na.rm = TRUE),
            max_inc = max(lrti_incidence, na.rm = TRUE))
incidence_summary


count_summary <- kids_analysis_data_1obs_per_child %>% 
  #group_by(treatment) %>% # Change treatment grouping as necessary 
  #filter(lrti_incidence < 0.7) %>% 
  summarize(mean_events = mean(lrti_events, na.rm = TRUE),
            sd_events = sd(lrti_events, na.rm = TRUE),
            n_events = n(),
            min_events = min(lrti_events, na.rm = TRUE),
            median_events = median(lrti_events, na.rm = TRUE),
            max_events = max(lrti_events, na.rm = TRUE))
count_summary


count_summary <- kids_analysis_data_2obs_per_child %>% 
  #group_by(treatment) %>% # Change treatment grouping as necessary 
  #filter(lrti_incidence < 0.7) %>% 
  summarize(mean_events = mean(lrti_events_winter, na.rm = TRUE),
            sd_events = sd(lrti_events_winter, na.rm = TRUE),
            n_events = n(),
            min_events = min(lrti_events_winter, na.rm = TRUE),
            median_events = median(lrti_events_winter, na.rm = TRUE),
            max_events = max(lrti_events_winter, na.rm = TRUE))
count_summary


# amb data summary
# amb_pm_lrti, amb_temp_lrti, amb_dewp_lrti, amb_pressure_lrti, amb_wind_lrti
ambient_summary <- analysis_data %>% 
  filter(area == "NN") %>% # Change area filter as necessary  
  mutate(new_var = amb_pm_lrti) %>% 
  group_by(treatment) %>% # Change treatment grouping as necessary 
  filter(!is.na(new_var)) %>% 
  #mutate(new_var = (as.numeric(new_var)-32)*5/9) %>% # convert degrees F to C 
  summarize(mean_amb = mean(new_var, na.rm = TRUE),
            sd_amb = sd(new_var, na.rm = TRUE),
            n_amb = n(),
            min_amb = min(new_var, na.rm = TRUE),
            median_amb = median(new_var, na.rm = TRUE),
            max_amb = max(new_var, na.rm = TRUE))
ambient_summary
```


```{r}
# Histograms for distribution of outcome data

events_plot <- analysis_data %>% 
  ggplot() +
    geom_histogram(aes(lrti_events)) +
    theme_light() +
    facet_wrap(~treatment)
events_plot

inc_plot <- analysis_data %>% 
  ggplot() +
    geom_histogram(aes(lrti_incidence)) +
    theme_light() +
    facet_wrap(~treatment)
inc_plot

events_plot_pm <- analysis_data %>% 
  mutate(pm_cat = cut(pm_mean_sampling_period,
                      breaks = c(0, 9.85, 18.06, 34.88, 286),
                      labels = c("Q1", "Q2", "Q3", "Q4"))) %>% 
  filter(!is.na(pm_cat)) %>% 
  ggplot() +
    geom_col(aes(pm_cat, lrti_events)) +
    theme_light() +
    facet_wrap(~treatment)
events_plot_pm

scatter_plot_pm <- analysis_data %>% 
  filter(!is.na(pm_mean_sampling_period)) %>% 
  ggplot() +
    geom_point(aes(lrti_events, pm_mean_sampling_period)) +
    theme_light() +
    facet_wrap(~treatment)
scatter_plot_pm

events_di_plot <- analysis_data %>% 
  ggplot() +
    geom_histogram(aes(lrti_events_di)) +
    facet_wrap(~treatment)
events_di_plot

events_di_plot <- analysis_data %>% 
  ggplot() +
    geom_boxplot(aes(lrti_events_di, pm_mean_sampling_period, group = lrti_events_di)) +
    facet_wrap(~treatment)
events_di_plot
```


```{r}
# Summarize initial models, check overdispersion and other diagnostic criteria

library(MASS)

# Simple model with offset
nb_results <- glm.nb(lrti_events ~ treatment + offset(log_person_time_at_risk), 
                     data = analysis_data)

summary(nb_results)
anova(nb_results, test="Chisq")

poisson_results <- glm(lrti_events ~ treatment + offset(log_person_time_at_risk), 
                       family = "poisson", data = analysis_data)

summary(poisson_results)
anova(poisson_results, test="Chisq")

# Link for analysis ideas and notes:
# https://stats.idre.ucla.edu/r/dae/negative-binomial-regression/ 
# https://stats.idre.ucla.edu/r/dae/poisson-regression/ 
# https://stats.idre.ucla.edu/r/faq/random-coefficient-poisson-models/ 

# Other diagnostic plots and tests
# https://stats.stackexchange.com/questions/70558/diagnostic-plots-for-count-regression 

library(vcd)
fit <- goodfit(analysis_data$lrti_events)
summary(fit) 
rootogram(fit)
Ord_plot(analysis_data$lrti_events)
distplot(analysis_data$lrti_events, type = "nbinom")


library(AER)
dispersiontest(poisson_results, trafo=1) # test indicates poisson model is overdispersed


library(pscl)
odTest(nb_results) # test indicates poisson model is overdispersed

# According to these results, data is overdispersed
# Variance is much higher than the mean for LRTI incidence
# Assumption of Poisson is variance = mean, so recommend using negative binomial model

mod2 <- zeroinfl(lrti_events ~ treatment + offset(log_person_time_at_risk), 
                 data = analysis_data, dist="poisson")
AIC(poisson_results, mod2)
# Above results indicate zero-inflated poisson model is a better fit than poisson model

mod2 <- zeroinfl(lrti_events ~ treatment + offset(log_person_time_at_risk), 
                 data = analysis_data, dist="negbin")
AIC(nb_results, mod2)
# Above results indicate neg bin model is a better fit than zero-inflated neg bin model
# Since data is also overdispersed (neg bin model better fit than poisson),
# a neg bin model seems to be the best fit overall


# plot residuals
res <- residuals(nb_results, type="deviance")
plot(predict(nb_results), res)
abline(h=0, lty=2)
qqnorm(res)
qqline(res)

library(faraway)
halfnorm(residuals(nb_results))

library(boot)
glm.diag.plots(nb_results)


# Check for influential datapoints
library(car)
nb_influence <- influencePlot(nb_results)
influencePlot(poisson_results)

inf_results <- influence(nb_results)$hat
inf_results

influence(nb_results)$coef


qqnorm(residuals(nb_results))
qqnorm(residuals(poisson_results))
```


```{r}
# Mixed model variations

poisson_results <- glmer(lrti_events ~ treatment + child_age + (1 | home:cohort:area), 
                         data = analysis_data, family = poisson(link = "log"), offset = log_person_time_at_risk)
summary(poisson_results)



negbin_results <- glmer.nb(lrti_events ~ treatment + child_age + (1 | home:cohort:area) + offset(log_person_time_at_risk), 
                           data = analysis_data)
summary(negbin_results)



logreg_results <- glmer(lrti_events_di ~ treatment + child_age + (1 | home:cohort:area), 
                        data = analysis_data, family = binomial, offset = log_person_time_at_risk)
summary(logreg_results)
```


```{r}
# Run mixed model and diagnostic plots from above

negbin_results <- glmer.nb(lrti_events ~ treatment_assigned + child_age + (1 | home:cohort:area) + 
                           offset(log_person_time_at_risk), data = analysis_data)

summary(negbin_results)
tidy(negbin_results, conf.int = TRUE)


# plot residuals
res <- residuals(negbin_results, type="deviance")
plot(predict(negbin_results), res)
abline(h=0, lty=2)
qqnorm(res)
qqline(res)

plot(residuals(negbin_results) ~ fitted(negbin_results), xlab="Fitted", ylab="Residuals")
abline(h=0)


library(faraway)
halfnorm(residuals(negbin_results))
```

