---
title: 'KidsAIR: Main analysis primary models'
author: "Ethan Walker"
date: "Started 27 Oct 2020, Updated 27 Oct 2020"
output:
  html_document:
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, include = TRUE,
                      message = FALSE, warning = FALSE)
```

```{r, eval=TRUE, include=TRUE}
library(readxl)
library(naniar)
library(lubridate)
library(broom)
library(broom.mixed)
library(zoo)
library(lme4)
library(lmerTest)
library(mctest)
library(tidyverse)
library(knitr)
library(kableExtra)
library(MASS)
library(faraway)
```


```{r}
# Load analysis dataset

file_path <- c("C:/Users/ethan.walker/Box/Ethan Walker UM/R/KidsAIR/")

analysis_data <- read_rds(paste0(file_path, 
                                 "Output/kids_analysis_data_1obs_per_child.rds")) %>% 
  rownames_to_column() %>% 
  mutate(filter_outliers = if_else(rowname %in% c(14, 57, 58, 249, 280, 16, 19, 20, 118), 1, 0)) %>% 
  filter(lrti_incidence < 0.7) %>% 
  filter(filter_outliers == 0)

health_exposure_data_sampling_day <- 
  read_rds(paste0(file_path, "Output/health_exposure_data_sampling_day.rds")) %>% 
  mutate(home_pets = as.factor(home_pets),
         home_pets_3level = fct_collapse(home_pets,
                                    "0" = "0",
                                    "1" = "1",
                                    "2+" = c("2","3","4","5","6","7","8","9","10","12","14")))

treatments_masked <- read_csv(paste0(file_path, "Input/KidsAIRrnd_masked.csv"), na = "NULL") %>% 
  mutate(home = gsub(" ", "", x = home),
         home = gsub("_", "", x = home))
```


```{r}
# Mixed model variations

poisson_results <- glmer(lrti_events ~ treatment + child_age + (1 | home:cohort:area), 
                         data = analysis_data, family = poisson(link = "log"), offset = log_person_time_at_risk)
summary(poisson_results)



nb_treatment_results <- glmer.nb(lrti_events ~ treatment + child_age + (1 | home:cohort:area) + 
                                 offset(log_person_time_at_risk), data = analysis_data)
summary(nb_treatment_results)



nb_pm_results <- glmer.nb(lrti_events ~ log(pm_mean_sampling_period) + child_age + 
                          (1 | home:cohort:area) + offset(log_person_time_at_risk), 
                          data = analysis_data)
summary(nb_pm_results)



logreg_results <- glmer(lrti_events_di ~ treatment + child_age + (1 | home:cohort:area), 
                        data = analysis_data, family = binomial, offset = log_person_time_at_risk)
summary(logreg_results)



linear_results <- glmer(pm_mean_sampling_period ~ treatment + child_age + (1 | home:cohort:area), 
                        data = analysis_data)
summary(linear_results)
```


Intent-to-treat model framework: LRTI outcome
```{r}
# Run mixed model and diagnostic plots from above

model_results <- glmer.nb(lrti_events ~ treatment + child_age + (1 | home:cohort:area) + 
                          offset(log_person_time_at_risk), data = analysis_data)

summary(model_results)

# plot residuals/diagnostics
res <- residuals(model_results, type="deviance")
plot(predict(model_results), res)
abline(h=0, lty=2)
qqnorm(res)
qqline(res)
halfnorm(residuals(model_results))

# plot results
tidy_results <- tidy(model_results, conf.int = TRUE) %>% 
  mutate(group_filter = if_else(grepl("treatment", term), 1, 0)) %>% 
  filter(group_filter == 1) %>% 
  mutate(term = gsub("treatment", "", term)) %>% 
  dplyr::select(term, estimate, p.value, conf.low, conf.high)
tidy_results

plot_estimates <- tidy_results %>%
  ggplot() +
  geom_point(aes(x=term, y=estimate), size = 4) +
  #scale_shape_manual(values = c(15, 16, 17, 18, 13, 9)) +
  geom_errorbar(aes(x=term, ymin=conf.low, ymax=conf.high), 
                size = 1.2, width = 0.5) +
  geom_hline(yintercept = 0) +
  theme_bw() +  
  #ggtitle(label = "Systolic BP ITT models") +
  labs(y = "Intervention vs Placebo") +
  labs(x = "") +
  theme(title = element_text(size = 16), 
          axis.text.x = element_text(size = 16, colour = "black", angle = 25,
                                     hjust = .8, vjust = .8),
          axis.text.y = element_text(size = 16, colour = "black"),
          axis.title.y = element_text(size = 16,
                                      margin = margin(t = 0, r = 20, b = 0, l = 0)),
          axis.line.x = element_line(colour = "black", size = 1.2), 
          axis.line.y = element_line(colour = "black", size = 1.2), 
          axis.ticks = element_blank(), 
          panel.border = element_blank(), 
          panel.grid = element_blank(),
          legend.position = "none") 
  scale_y_continuous(breaks = c(-3, -2, -1, 0, 1, 2, 3, 4, 5), 
                     labels = c(-3, -2, -1, 0, 1, 2, 3, 4, 5)) 
plot_estimates
```


Intent-to-treat model framework: PM outcome
```{r}
# Run mixed model and diagnostic plots from above

model_results <- glmer(log(pm_mean_sampling_period) ~ treatment + child_age + (1 | home:cohort:area), 
                        data = analysis_data)

summary(model_results)

# plot residuals/diagnostics
res <- residuals(model_results, type="deviance")
plot(predict(model_results), res)
abline(h=0, lty=2)
qqnorm(res)
qqline(res)
halfnorm(residuals(model_results))

# plot results
tidy_results <- tidy(model_results, conf.int = TRUE) %>% 
  mutate(group_filter = if_else(grepl("treatment", term), 1, 0)) %>% 
  filter(group_filter == 1) %>% 
  mutate(term = gsub("treatment", "", term)) %>% 
  dplyr::select(term, estimate, conf.low, conf.high)
#tidy_results

plot_estimates <- tidy_results %>%
  ggplot() +
  geom_point(aes(x=term, y=estimate), size = 4) +
  #scale_shape_manual(values = c(15, 16, 17, 18, 13, 9)) +
  geom_errorbar(aes(x=term, ymin=conf.low, ymax=conf.high), 
                size = 1.2, width = 0.5) +
  geom_hline(yintercept = 0) +
  theme_bw() +  
  #ggtitle(label = "Systolic BP ITT models") +
  labs(y = "Intervention vs Placebo") +
  labs(x = "") +
  theme(title = element_text(size = 16), 
          axis.text.x = element_text(size = 16, colour = "black", angle = 25,
                                     hjust = .8, vjust = .8),
          axis.text.y = element_text(size = 16, colour = "black"),
          axis.title.y = element_text(size = 16,
                                      margin = margin(t = 0, r = 20, b = 0, l = 0)),
          axis.line.x = element_line(colour = "black", size = 1.2), 
          axis.line.y = element_line(colour = "black", size = 1.2), 
          axis.ticks = element_blank(), 
          panel.border = element_blank(), 
          panel.grid = element_blank(),
          legend.position = "none") 
plot_estimates
```


Exposure-response model framework
```{r}
# Run mixed model and diagnostic plots from above

model_results <- glmer.nb(lrti_events ~ log(pm_mean_sampling_period) + child_age + 
                          (1 | home:cohort:area) + offset(log_person_time_at_risk), 
                          data = analysis_data)

summary(model_results)

# plot residuals/diagnostics
res <- residuals(model_results, type="deviance")
plot(predict(model_results), res)
abline(h=0, lty=2)
qqnorm(res)
qqline(res)
halfnorm(residuals(model_results))

# plot results
tidy_results <- tidy(model_results, conf.int = TRUE) %>% 
  mutate(group_filter = if_else(grepl("log", term), 1, 0)) %>% 
  filter(group_filter == 1) %>% 
  mutate(term = "Log PM2.5") %>% 
  dplyr::select(term, estimate, p.value, conf.low, conf.high)
tidy_results

plot_estimates <- tidy_results %>%
  ggplot() +
  geom_point(aes(x=term, y=estimate), size = 4) +
  #scale_shape_manual(values = c(15, 16, 17, 18, 13, 9)) +
  geom_errorbar(aes(x=term, ymin=conf.low, ymax=conf.high), 
                size = 1.2, width = 0.5) +
  geom_hline(yintercept = 0) +
  theme_bw() +  
  #ggtitle(label = "Systolic BP ITT models") +
  labs(y = "LRTI cases per log unit PM2.5 increase") +
  labs(x = "") +
  theme(title = element_text(size = 16), 
          axis.text.x = element_blank(),
          axis.text.y = element_text(size = 16, colour = "black"),
          axis.title.y = element_text(size = 16,
                                      margin = margin(t = 0, r = 20, b = 0, l = 0)),
          axis.line.x = element_line(colour = "black", size = 1.2), 
          axis.line.y = element_line(colour = "black", size = 1.2), 
          axis.ticks = element_blank(), 
          panel.border = element_blank(), 
          panel.grid = element_blank(),
          legend.position = "none") 
plot_estimates
```


