---
title: 'KidsAIR: Main analysis'
author: "Ethan Walker"
date: "Started 28 Oct 2020, Updated 10 Nov 2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE, include = TRUE,
                      message = FALSE, warning = FALSE)
```

```{r}
library(readxl)
library(naniar)
library(lubridate)
library(broom)
library(broom.mixed)
library(zoo)
library(lme4)
library(lmerTest)
library(mctest)
library(tidyverse)
library(knitr)
library(kableExtra)
library(MASS)
library(faraway)
```


```{r}
# Load analysis dataset

file_path <- c("C:/Users/ethan.walker/Box/Ethan Walker UM/R/KidsAIR/")

analysis_data <- read_rds(paste0(file_path, 
                                 "Output/kids_analysis_data_1obs_per_child.rds")) %>% 
  mutate(pm_mean_sampling_period_iqr = pm_mean_sampling_period/25,
         pm_at_home_sampling_period_iqr = pm_at_home_sampling_period/25) 
  #filter(gender == "Female")
  #filter(home_sqft_2level == "1500+")

analysis_data_outliers <- analysis_data %>% 
  #rownames_to_column() %>% 
  #mutate(filter_outliers = if_else(rowname %in% c(57), 1, 0)) %>% 
  mutate(log_person_time_at_risk = if_else(area == "AK" & child_id_num == 31, 2.33, log_person_time_at_risk)) %>% 
  mutate(person_time_at_risk = if_else(area == "AK" & child_id_num == 31, 72, person_time_at_risk)) 
  
analysis_data_winter1 <- read_rds(paste0(file_path, 
                                 "Output/kids_analysis_data_2obs_per_child.rds")) %>% 
  mutate(pm_mean_sampling_period_iqr = pm_mean_sampling_period/25,
         pm_at_home_sampling_period_iqr = pm_at_home_sampling_period/25) %>% 
  filter(person_time_at_risk_winter > 0) %>% 
  filter(winter_id == 1)

analysis_data_winter2 <- read_rds(paste0(file_path, 
                                 "Output/kids_analysis_data_2obs_per_child.rds")) %>% 
  mutate(pm_mean_sampling_period_iqr = pm_mean_sampling_period/25,
         pm_at_home_sampling_period_iqr = pm_at_home_sampling_period/25) %>% 
  filter(person_time_at_risk_winter > 0) %>% 
  filter(winter_id == 2)

health_exposure_data_sampling_day <- 
  read_rds(paste0(file_path, "Output/health_exposure_data_sampling_day.rds")) %>% 
  dplyr::select(area, home, child_id_num, at_home, at_home_location)
```


# Intent-to-treat framework, LRTI outcome

```{r, echo=TRUE}
# Run primary model and print results
itt_results <- glmer.nb(lrti_events_total ~ treatment_assigned + child_age + 
                        (1 | home:cohort:area) + 
                        offset(log_person_time_at_risk), data = analysis_data)
#write_rds(itt_results, paste0(file_path, "Output/itt_results.rds"))

summary(itt_results)

res <- residuals(itt_results, type="deviance")
plot(predict(itt_results), res)
abline(h=0, lty=2)
qqnorm(res)
qqline(res)
halfnorm(residuals(itt_results))
```

```{r, eval=FALSE, include=FALSE}
# Run and save model results

itt_winter1_results <- glmer.nb(lrti_events_winter ~ treatment_assigned + child_age + (1 | home:cohort:area) + 
                        offset(log_person_time_at_risk_winter), data = analysis_data_winter1)
write_rds(itt_winter1_results, paste0(file_path, "Output/itt_winter1_results.rds"))

itt_winter2_results <- glmer.nb(lrti_events_winter ~ treatment_assigned + child_age + (1 | home:cohort:area) + 
                        offset(log_person_time_at_risk_winter), data = analysis_data_winter2)
write_rds(itt_winter2_results, paste0(file_path, "Output/itt_winter2_results.rds"))

itt_income_results <- glmer.nb(lrti_events_total ~ treatment_assigned + child_age + (1 | home:cohort:area) + 
                        income_3level + 
                        offset(log_person_time_at_risk), data = analysis_data)
write_rds(itt_income_results, paste0(file_path, "Output/itt_income_results.rds"))

itt_education_results <- glmer.nb(lrti_events_total ~ treatment_assigned + child_age + (1 | home:cohort:area) + 
                        education_3level + 
                        offset(log_person_time_at_risk), data = analysis_data)
write_rds(itt_education_results, paste0(file_path, "Output/itt_education_results.rds"))

itt_smoke_results <- glmer.nb(lrti_events_total ~ treatment_assigned + child_age + (1 | home:cohort:area) + 
                        residents_smoke + 
                        offset(log_person_time_at_risk), data = analysis_data)
write_rds(itt_smoke_results, paste0(file_path, "Output/itt_smoke_results.rds"))

itt_burn_level_results <- glmer.nb(lrti_events_total ~ treatment_assigned + child_age + (1 | home:cohort:area) + 
                        burn_level_3level + 
                        offset(log_person_time_at_risk), data = analysis_data)
write_rds(itt_burn_level_results, paste0(file_path, "Output/itt_burn_level_results.rds"))

itt_smoking_results <- glmer.nb(lrti_events_total ~ treatment_assigned + child_age + (1 | home:cohort:area) + 
                        home_act_smoking_sum + 
                        offset(log_person_time_at_risk), data = analysis_data)
write_rds(itt_smoking_results, paste0(file_path, "Output/itt_smoking_results.rds"))

itt_windows_results <- glmer.nb(lrti_events_total ~ treatment_assigned + child_age + (1 | home:cohort:area) + 
                        home_act_windows_sum + 
                        offset(log_person_time_at_risk), data = analysis_data)
write_rds(itt_windows_results, paste0(file_path, "Output/itt_windows_results.rds"))

itt_door_results <- glmer.nb(lrti_events_total ~ treatment_assigned + child_age + (1 | home:cohort:area) + 
                        home_act_door_sum + 
                        offset(log_person_time_at_risk), data = analysis_data)
write_rds(itt_door_results, paste0(file_path, "Output/itt_door_results.rds"))

itt_sweep_results <- glmer.nb(lrti_events_total ~ treatment_assigned + child_age + (1 | home:cohort:area) + 
                        home_act_sweep_sum + 
                        offset(log_person_time_at_risk), data = analysis_data)
write_rds(itt_sweep_results, paste0(file_path, "Output/itt_sweep_results.rds"))

itt_home_results <- glmer.nb(lrti_events_total ~ treatment_assigned + child_age + (1 | home) + 
                        offset(log_person_time_at_risk), data = analysis_data)
write_rds(itt_home_results, paste0(file_path, "Output/itt_home_results.rds"))

itt_no_age_results <- glmer.nb(lrti_events_total ~ treatment_assigned + (1 | home:cohort:area) + 
                        offset(log_person_time_at_risk), data = analysis_data)
write_rds(itt_no_age_results, paste0(file_path, "Output/itt_no_age_results.rds"))

itt_outlier_results <- glmer.nb(lrti_events_total ~ treatment_assigned + child_age + (1 | home:cohort:area) + 
                        offset(log_person_time_at_risk), data = analysis_data_outliers)
write_rds(itt_outlier_results, paste0(file_path, "Output/itt_outlier_results.rds"))
```


```{r}
# Load results
itt_results <- read_rds(paste0(file_path, "Output/itt_results.rds"))
itt_winter1_results <- read_rds(paste0(file_path, "Output/itt_winter1_results.rds"))
#itt_winter2_results <- read_rds(paste0(file_path, "Output/itt_winter2_results.rds"))
itt_income_results <- read_rds(paste0(file_path, "Output/itt_income_results.rds"))
itt_education_results <- read_rds(paste0(file_path, "Output/itt_education_results.rds"))
itt_smoke_results <- read_rds(paste0(file_path, "Output/itt_smoke_results.rds"))
itt_burn_level_results <- read_rds(paste0(file_path, "Output/itt_burn_level_results.rds"))
itt_smoking_results <- read_rds(paste0(file_path, "Output/itt_smoking_results.rds"))
itt_windows_results <- read_rds(paste0(file_path, "Output/itt_windows_results.rds"))
itt_door_results <- read_rds(paste0(file_path, "Output/itt_door_results.rds"))
itt_sweep_results <- read_rds(paste0(file_path, "Output/itt_sweep_results.rds"))
itt_home_results <- read_rds(paste0(file_path, "Output/itt_home_results.rds"))
itt_no_age_results <- read_rds(paste0(file_path, "Output/itt_no_age_results.rds"))
itt_outlier_results <- read_rds(paste0(file_path, "Output/itt_outlier_results.rds"))


# Function to clean results
results_function <- function(model_results, model_name) {
  
tidy_results <- tidy(model_results, conf.int = TRUE) %>% 
  mutate(group_filter = if_else(grepl("treatment", term), 1, 0)) %>% 
  filter(group_filter == 1) %>% 
  mutate(term = gsub("treatment_assigned", "", term),
         model = model_name) %>% 
  dplyr::select(model, term, estimate, p.value, conf.low, conf.high)
tidy_results

}


# Run results through function, save, combine for plotting
itt_tidy <- results_function(itt_results, "ITT Primary")
itt_winter1_tidy <- results_function(itt_winter1_results, "ITT Winter 1")
#itt_winter2_tidy <- results_function(itt_winter2_results, "ITT Winter 2")
itt_income_tidy <- results_function(itt_income_results, "ITT + income")
itt_education_tidy <- results_function(itt_education_results, "ITT + education")
itt_smoke_tidy <- results_function(itt_smoke_results, "ITT + smoke hx")
itt_burn_level_tidy <- results_function(itt_burn_level_results, "ITT + burn level")
itt_smoking_tidy <- results_function(itt_smoking_results, "ITT + smoke act")
itt_windows_tidy <- results_function(itt_windows_results, "ITT + window act")
itt_door_tidy <- results_function(itt_door_results, "ITT + door act")
itt_sweep_tidy <- results_function(itt_sweep_results, "ITT + sweep act")
itt_home_tidy <- results_function(itt_home_results, "ITT home only")
itt_no_age_tidy <- results_function(itt_no_age_results, "ITT - age")
itt_outlier_tidy <- results_function(itt_outlier_results, "ITT outlier")


# Combine cleaned results
itt_results_combined <- rbind(itt_tidy, itt_winter1_tidy, 
                              itt_income_tidy, itt_education_tidy, 
                              itt_smoke_tidy, itt_burn_level_tidy, itt_smoking_tidy,
                              itt_windows_tidy, itt_door_tidy, itt_sweep_tidy,
                              itt_home_tidy, itt_no_age_tidy, itt_outlier_tidy)


# Plot results
itt_plot_estimates <- itt_results_combined %>%
  mutate(model = factor(model,
                        levels = c("ITT Primary", "ITT Winter 1", 
                                   "ITT + income", "ITT + education",
                                   "ITT + smoke hx", "ITT + burn level", "ITT + smoke act",
                                   "ITT + window act", "ITT + door act", "ITT + sweep act",
                                   "ITT home only", "ITT - age", "ITT outlier"))) %>% 
  ggplot(aes(group = term, shape = term)) +
  geom_point(aes(x=model, y=estimate), 
             position = position_dodge(width = 0.5), size = 4) +
  geom_errorbar(aes(x=model, ymin=conf.low, ymax=conf.high), 
             position = position_dodge(width = 0.5), size = 1.2, width = 0.5) +
  geom_hline(yintercept = 0) +
  theme_bw() +  
  labs(y = "LRTI events per child-week \n at risk compared to placebo") +
  labs(x = "", group = "", shape = "") +
  theme(title = element_text(size = 16), 
          axis.text.x = element_text(size = 16, colour = "black", angle = 45,
                                     hjust = 1, vjust = .8),
          axis.text.y = element_text(size = 16, colour = "black"),
          axis.title.y = element_text(size = 16,
                                      margin = margin(t = 0, r = 20, b = 0, l = 0)),
          axis.line.x = element_line(colour = "black", size = 1.2), 
          axis.line.y = element_line(colour = "black", size = 1.2), 
          axis.ticks = element_blank(), 
          panel.border = element_blank(), 
          panel.grid = element_blank(),
          legend.position = "top",
          legend.text = element_text(size = 14, colour = "black")) 
itt_plot_estimates


# Save plot as jpg
ggsave("itt_plot_estimates.jpg", width = 12, height = 6)
```

\pagebreak  

# Intent-to-treat framework, PM2.5 outcome

```{r, echo=TRUE}
# Run primary model and print results
itt_pm_results <- glmer(log(pm_mean_sampling_period) ~ treatment_assigned + child_age + 
                       (1 | home:cohort:area), data = analysis_data)
#write_rds(itt_pm_results, paste0(file_path, "Output/itt_pm_results.rds"))

summary(itt_pm_results)
```


```{r, eval=FALSE, include=FALSE}
# Run and save model results

itt_pm_winter1_results <- glmer(log(pm_mean_sampling_period) ~ treatment_assigned + child_age + 
                       (1 | home:cohort:area), data = analysis_data_winter1)
write_rds(itt_pm_winter1_results, paste0(file_path, "Output/itt_pm_winter1_results.rds"))

#itt_pm_winter2_results <- glmer(log(pm_mean_sampling_period) ~ treatment_assigned + child_age + 
#                       (1 | home:cohort:area), data = analysis_data_winter2)
#write_rds(itt_pm_winter2_results, paste0(file_path, "Output/itt_pm_winter2_results.rds"))

itt_pm_income_results <- glmer(log(pm_mean_sampling_period) ~ treatment_assigned + 
                               child_age + (1 | home:cohort:area) + 
                               income_3level, data = analysis_data)
write_rds(itt_pm_income_results, paste0(file_path, "Output/itt_pm_income_results.rds"))

itt_pm_education_results <- glmer(log(pm_mean_sampling_period) ~ treatment_assigned + 
                                  child_age + (1 | home:cohort:area) + 
                                  education_3level, data = analysis_data)
write_rds(itt_pm_education_results, paste0(file_path, "Output/itt_pm_education_results.rds"))

itt_pm_smoke_results <- glmer(log(pm_mean_sampling_period) ~ treatment_assigned + 
                              child_age + (1 | home:cohort:area) + 
                              residents_smoke, data = analysis_data)
write_rds(itt_pm_smoke_results, paste0(file_path, "Output/itt_pm_smoke_results.rds"))

itt_pm_burn_level_results <- glmer(log(pm_mean_sampling_period) ~ treatment_assigned + 
                                   child_age + (1 | home:cohort:area) + 
                                   burn_level_3level, data = analysis_data)
write_rds(itt_pm_burn_level_results, paste0(file_path, "Output/itt_pm_burn_level_results.rds"))

itt_pm_smoking_results <- glmer(log(pm_mean_sampling_period) ~ treatment_assigned + 
                                   child_age + (1 | home:cohort:area) + 
                                   home_act_smoking_sum, data = analysis_data)
write_rds(itt_pm_smoking_results, paste0(file_path, "Output/itt_pm_smoking_results.rds"))

itt_pm_windows_results <- glmer(log(pm_mean_sampling_period) ~ treatment_assigned + 
                                   child_age + (1 | home:cohort:area) + 
                                   home_act_windows_sum, data = analysis_data)
write_rds(itt_pm_windows_results, paste0(file_path, "Output/itt_pm_windows_results.rds"))

itt_pm_door_results <- glmer(log(pm_mean_sampling_period) ~ treatment_assigned + 
                                   child_age + (1 | home:cohort:area) + 
                                   home_act_door_sum, data = analysis_data)
write_rds(itt_pm_door_results, paste0(file_path, "Output/itt_pm_door_results.rds"))

itt_pm_sweep_results <- glmer(log(pm_mean_sampling_period) ~ treatment_assigned + 
                                   child_age + (1 | home:cohort:area) + 
                                   home_act_sweep_sum, data = analysis_data)
write_rds(itt_pm_sweep_results, paste0(file_path, "Output/itt_pm_sweep_results.rds"))

itt_pm_home_results <- glmer(log(pm_mean_sampling_period) ~ treatment_assigned + 
                             child_age + (1 | home), data = analysis_data)
write_rds(itt_pm_home_results, paste0(file_path, "Output/itt_pm_home_results.rds"))

itt_pm_no_age_results <- glmer(log(pm_mean_sampling_period) ~ treatment_assigned + 
                               (1 | home:cohort:area), data = analysis_data)
write_rds(itt_pm_no_age_results, paste0(file_path, "Output/itt_pm_no_age_results.rds"))

itt_pm_outlier_results <- glmer(log(pm_mean_sampling_period) ~ treatment_assigned + 
                                child_age + (1 | home:cohort:area), data = analysis_data_outliers)
write_rds(itt_pm_outlier_results, paste0(file_path, "Output/itt_pm_outlier_results.rds"))
```


```{r}
# Load results
itt_pm_results <- read_rds(paste0(file_path, "Output/itt_pm_results.rds"))
itt_pm_winter1_results <- read_rds(paste0(file_path, "Output/itt_pm_winter1_results.rds"))
#itt_pm_winter2_results <- read_rds(paste0(file_path, "Output/itt_pm_winter2_results.rds"))
itt_pm_income_results <- read_rds(paste0(file_path, "Output/itt_pm_income_results.rds"))
itt_pm_education_results <- read_rds(paste0(file_path, "Output/itt_pm_education_results.rds"))
itt_pm_smoke_results <- read_rds(paste0(file_path, "Output/itt_pm_smoke_results.rds"))
itt_pm_burn_level_results <- read_rds(paste0(file_path, "Output/itt_pm_burn_level_results.rds"))
itt_pm_smoking_results <- read_rds(paste0(file_path, "Output/itt_pm_smoking_results.rds"))
itt_pm_windows_results <- read_rds(paste0(file_path, "Output/itt_pm_windows_results.rds"))
itt_pm_door_results <- read_rds(paste0(file_path, "Output/itt_pm_door_results.rds"))
itt_pm_sweep_results <- read_rds(paste0(file_path, "Output/itt_pm_sweep_results.rds"))
itt_pm_home_results <- read_rds(paste0(file_path, "Output/itt_pm_home_results.rds"))
itt_pm_no_age_results <- read_rds(paste0(file_path, "Output/itt_pm_no_age_results.rds"))
itt_pm_outlier_results <- read_rds(paste0(file_path, "Output/itt_pm_outlier_results.rds"))


# Run function to clean results
results_function <- function(model_results, model_name) {
  
tidy_results <- tidy(model_results, conf.int = TRUE) %>% 
  mutate(group_filter = if_else(grepl("treatment", term), 1, 0)) %>% 
  filter(group_filter == 1) %>% 
  mutate(term = gsub("treatment_assigned", "", term),
         model = model_name) %>% 
  dplyr::select(model, term, estimate, conf.low, conf.high)
tidy_results

}


# Run results through function, save, combine for plotting
itt_pm_tidy <- results_function(itt_pm_results, "ITT Primary")
itt_pm_winter1_tidy <- results_function(itt_pm_winter1_results, "ITT Winter 1")
#itt_pm_winter2_results <- results_function(itt_pm_winter2_results, "ITT Winter 2")
itt_pm_income_tidy <- results_function(itt_pm_income_results, "ITT + income")
itt_pm_education_tidy <- results_function(itt_pm_education_results, "ITT + education")
itt_pm_smoke_tidy <- results_function(itt_pm_smoke_results, "ITT + smoke hx")
itt_pm_burn_level_tidy <- results_function(itt_pm_burn_level_results, "ITT + burn level")
itt_pm_smoking_tidy <- results_function(itt_pm_smoking_results, "ITT + smoke act")
itt_pm_windows_tidy <- results_function(itt_pm_windows_results, "ITT + window act")
itt_pm_door_tidy <- results_function(itt_pm_door_results, "ITT + door act")
itt_pm_sweep_tidy <- results_function(itt_pm_sweep_results, "ITT + sweep act")
itt_pm_home_tidy <- results_function(itt_pm_home_results, "ITT home only")
itt_pm_no_age_tidy <- results_function(itt_pm_no_age_results, "ITT - age")
itt_pm_outlier_tidy <- results_function(itt_pm_outlier_results, "ITT outlier")


# Combine cleaned results
itt_pm_results_combined <- rbind(itt_pm_tidy, itt_pm_winter1_tidy, 
                                 itt_pm_income_tidy, itt_pm_education_tidy, 
                              itt_pm_smoke_tidy, itt_pm_burn_level_tidy, itt_pm_smoking_tidy,
                              itt_pm_windows_tidy, itt_pm_door_tidy, itt_pm_sweep_tidy,
                              itt_pm_home_tidy, itt_pm_no_age_tidy, itt_pm_outlier_tidy)


# Plot results
itt_pm_plot_estimates <- itt_pm_results_combined %>%
  mutate(model = factor(model,
                        levels = c("ITT Primary", "ITT Winter 1", 
                                   "ITT + income", "ITT + education",
                                   "ITT + smoke hx", "ITT + burn level", "ITT + smoke act",
                                   "ITT + window act", "ITT + door act", "ITT + sweep act",
                                   "ITT home only", "ITT - age", "ITT outlier"))) %>% 
  ggplot(aes(group = term, shape = term)) +
  geom_point(aes(x=model, y=estimate), 
             position = position_dodge(width = 0.5), size = 4) +
  geom_errorbar(aes(x=model, ymin=conf.low, ymax=conf.high), 
             position = position_dodge(width = 0.5), size = 1.2, width = 0.5) +
  geom_hline(yintercept = 0) +
  theme_bw() +  
  labs(y = "Difference in log(PM2.5) \n compared to placebo") +
  labs(x = "", group = "", shape = "") +
  theme(title = element_text(size = 16), 
          axis.text.x = element_text(size = 16, colour = "black", angle = 45,
                                     hjust = 1, vjust = .8),
          axis.text.y = element_text(size = 16, colour = "black"),
          axis.title.y = element_text(size = 16,
                                      margin = margin(t = 0, r = 20, b = 0, l = 0)),
          axis.line.x = element_line(colour = "black", size = 1.2), 
          axis.line.y = element_line(colour = "black", size = 1.2), 
          axis.ticks = element_blank(), 
          panel.border = element_blank(), 
          panel.grid = element_blank(),
          legend.position = "top",
          legend.text = element_text(size = 14, colour = "black")) 
itt_pm_plot_estimates


# Save plot as jpg
ggsave("itt_pm_plot_estimates.jpg", width = 12, height = 6)
```

\pagebreak  

# Exposure-response framework, LRTI outcome

```{r, echo=TRUE}
# Run primary model and print results
er_results <- glmer.nb(lrti_events_total ~ pm_mean_sampling_period_iqr + child_age + 
                          education_3level + residents_smoke + 
                          (1 | home:cohort:area) + offset(log_person_time_at_risk), 
                          data = analysis_data)
#write_rds(er_results, paste0(file_path, "Output/er_results.rds"))

summary(er_results)
```


```{r, eval=FALSE, include=FALSE}
# Run and save model results

er_winter1_results <- glmer.nb(lrti_events_winter ~ pm_mean_sampling_period_iqr + child_age + 
                          education_3level + residents_smoke + 
                          (1 | home:cohort:area) + offset(log_person_time_at_risk_winter), 
                          data = analysis_data_winter1)
write_rds(er_winter1_results, paste0(file_path, "Output/er_winter1_results.rds"))

#er_winter2_results <- glmer.nb(lrti_events_total_winter ~ pm_mean_sampling_period_iqr + child_age + 
#                          education_3level + residents_smoke + 
#                          (1 | home:cohort:area) + offset(log_person_time_at_risk_winter), 
#                          data = analysis_data_winter2)
#write_rds(er_winter2_results, paste0(file_path, "Output/er_winter2_results.rds"))

er_income_results <- glmer.nb(lrti_events_total ~ pm_mean_sampling_period_iqr + child_age + 
                          income_3level + residents_smoke + 
                          (1 | home:cohort:area) + offset(log_person_time_at_risk), 
                          data = analysis_data)
write_rds(er_income_results, paste0(file_path, "Output/er_income_results.rds"))

er_burn_level_results <- glmer.nb(lrti_events_total ~ pm_mean_sampling_period_iqr + child_age + 
                          education_3level + residents_smoke + burn_level_3level +
                          (1 | home:cohort:area) + offset(log_person_time_at_risk), 
                          data = analysis_data)
write_rds(er_burn_level_results, paste0(file_path, "Output/er_burn_level_results.rds"))

er_smoking_results <- glmer.nb(lrti_events_total ~ pm_mean_sampling_period_iqr + child_age + 
                          education_3level + home_act_smoking_sum + 
                          (1 | home:cohort:area) + offset(log_person_time_at_risk), 
                          data = analysis_data)
write_rds(er_smoking_results, paste0(file_path, "Output/er_smoking_results.rds"))

er_windows_results <- glmer.nb(lrti_events_total ~ pm_mean_sampling_period_iqr + child_age + 
                          education_3level + residents_smoke + home_act_windows_sum +
                          (1 | home:cohort:area) + offset(log_person_time_at_risk), 
                          data = analysis_data)
write_rds(er_windows_results, paste0(file_path, "Output/er_windows_results.rds"))

er_door_results <- glmer.nb(lrti_events_total ~ pm_mean_sampling_period_iqr + child_age + 
                          education_3level + residents_smoke + home_act_door_sum +
                          (1 | home:cohort:area) + offset(log_person_time_at_risk), 
                          data = analysis_data)
write_rds(er_door_results, paste0(file_path, "Output/er_door_results.rds"))

er_sweep_results <- glmer.nb(lrti_events_total ~ pm_mean_sampling_period_iqr + child_age + 
                          education_3level + residents_smoke + home_act_sweep_sum +
                          (1 | home:cohort:area) + offset(log_person_time_at_risk), 
                          data = analysis_data)
write_rds(er_sweep_results, paste0(file_path, "Output/er_sweep_results.rds"))

er_home_results <- glmer.nb(lrti_events_total ~ pm_mean_sampling_period_iqr + child_age + 
                          education_3level + residents_smoke + home_act_windows_sum +
                          (1 | home) + offset(log_person_time_at_risk), 
                          data = analysis_data)
write_rds(er_home_results, paste0(file_path, "Output/er_home_results.rds"))

er_no_age_results <- glmer.nb(lrti_events_total ~ pm_mean_sampling_period_iqr + 
                          education_3level + residents_smoke + 
                          (1 | home:cohort:area) + offset(log_person_time_at_risk), 
                          data = analysis_data)
write_rds(er_no_age_results, paste0(file_path, "Output/er_no_age_results.rds"))

er_outlier_results <- glmer.nb(lrti_events_total ~ pm_mean_sampling_period_iqr + child_age + 
                          education_3level + residents_smoke + 
                          (1 | home:cohort:area) + offset(log_person_time_at_risk), 
                          data = analysis_data_outliers)
write_rds(er_outlier_results, paste0(file_path, "Output/er_outlier_results.rds"))
```


```{r}
# Load results
er_results <- read_rds(paste0(file_path, "Output/er_results.rds"))
er_winter1_results <- read_rds(paste0(file_path, "Output/er_winter1_results.rds"))
#er_winter2_results <- read_rds(paste0(file_path, "Output/er_winter2_results.rds"))
er_income_results <- read_rds(paste0(file_path, "Output/er_income_results.rds"))
er_burn_level_results <- read_rds(paste0(file_path, "Output/er_burn_level_results.rds"))
er_smoking_results <- read_rds(paste0(file_path, "Output/er_smoking_results.rds"))
er_windows_results <- read_rds(paste0(file_path, "Output/er_windows_results.rds"))
er_door_results <- read_rds(paste0(file_path, "Output/er_door_results.rds"))
er_sweep_results <- read_rds(paste0(file_path, "Output/er_sweep_results.rds"))
er_home_results <- read_rds(paste0(file_path, "Output/er_home_results.rds"))
er_no_age_results <- read_rds(paste0(file_path, "Output/er_no_age_results.rds"))
er_outlier_results <- read_rds(paste0(file_path, "Output/er_outlier_results.rds"))


# Run function to clean results
results_function <- function(model_results, model_name) {
  
tidy_results <- tidy(model_results, conf.int = TRUE) %>% 
  mutate(group_filter = if_else(grepl("pm", term), 1, 0)) %>% 
  filter(group_filter == 1) %>% 
  mutate(term = "PM2.5",
         model = model_name) %>% 
  dplyr::select(model, term, estimate, conf.low, conf.high)
tidy_results

}


# Run results through function, save, combine for plotting
er_tidy <- results_function(er_results, "ER Primary")
er_winter1_tidy <- results_function(er_winter1_results, "ER Winter 1")
#er_winter2_tidy <- results_function(er_winter2_results, "ER Winter 2")
er_income_tidy <- results_function(er_income_results, "ER + income")
er_burn_level_tidy <- results_function(er_burn_level_results, "ER + burn level")
er_smoking_tidy <- results_function(er_smoking_results, "ER + smoke act")
er_windows_tidy <- results_function(er_windows_results, "ER + window act")
er_door_tidy <- results_function(er_door_results, "ER + door act")
er_sweep_tidy <- results_function(er_sweep_results, "ER + sweep act")
er_home_tidy <- results_function(er_home_results, "ER home only")
er_no_age_tidy <- results_function(er_no_age_results, "ER - age")
er_outlier_tidy <- results_function(er_outlier_results, "ER outlier")


# Combine cleaned results
er_results_combined <- rbind(er_tidy, er_winter1_tidy, 
                             er_income_tidy, er_burn_level_tidy, 
                              er_smoking_tidy, er_windows_tidy, er_door_tidy,
                              er_sweep_tidy, er_home_tidy, er_no_age_tidy,
                              er_outlier_tidy)


# Plot results
er_plot_estimates <- er_results_combined %>%
  mutate(model = factor(model,
                        levels = c("ER Primary", "ER Winter 1",
                                   "ER + income", "ER + burn level",
                                   "ER + smoke act", "ER + window act", "ER + door act",
                                   "ER + sweep act", "ER home only", "ER - age",
                                   "ER outlier"))) %>% 
  ggplot(aes(group = term, shape = term)) +
  geom_point(aes(x=model, y=estimate), 
             position = position_dodge(width = 0.5), size = 4) +
  geom_errorbar(aes(x=model, ymin=conf.low, ymax=conf.high), 
             position = position_dodge(width = 0.5), size = 1.2, width = 0.5) +
  geom_hline(yintercept = 0) +
  theme_bw() +  
  labs(y = "LRTI cases per IQR \n increase in PM2.5") +
  labs(x = "", group = "", shape = "") +
  theme(title = element_text(size = 16), 
          axis.text.x = element_text(size = 16, colour = "black", angle = 45,
                                     hjust = 1, vjust = .8),
          axis.text.y = element_text(size = 16, colour = "black"),
          axis.title.y = element_text(size = 16,
                                      margin = margin(t = 0, r = 20, b = 0, l = 0)),
          axis.line.x = element_line(colour = "black", size = 1.2), 
          axis.line.y = element_line(colour = "black", size = 1.2), 
          axis.ticks = element_blank(), 
          panel.border = element_blank(), 
          panel.grid = element_blank(),
          legend.position = "none",
          legend.text = element_text(size = 14, colour = "black")) 
er_plot_estimates


# Save plot as jpg
ggsave("er_plot_estimates.jpg", width = 12, height = 6)
```

\pagebreak  

# Logistic Regression framework, LRTI outcome

```{r, echo=TRUE}
# Run primary model and print results
logreg_results <- glmer(lrti_events_di_total ~ treatment_assigned + child_age + 
                       (1 | home:cohort:area), data = analysis_data, 
                       family = binomial)
#write_rds(logreg_results, paste0(file_path, "Output/logreg_results.rds"))

summary(logreg_results)


at_risk_summary <- analysis_data %>% 
  group_by(treatment_assigned) %>% 
  summarize(mean(person_time_at_risk, na.rm = TRUE),
            sd(person_time_at_risk, na.rm = TRUE),
            median(person_time_at_risk, na.rm = TRUE))
at_risk_summary
```

