---
title: 'KidsAIR: manuscript tables/figures'
author: "Ethan Walker"
date: "Started 13 May 2020, Updated 30 June 2020"
output:
  powerpoint_presentation: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE, 
                      include = TRUE, warning = FALSE,
                      fig.height = 6, fig.width = 8)
```

```{r, message=FALSE}
library(tidyverse)
library(readxl)
library(naniar)
library(lubridate)
library(zoo)
library(knitr)
jv_palette <- c("#330099","#CC0066","#FF6633", 
                 "#0099CC", "#FF9900","#CC6633",
                  "#FF3366", "#33CC99", "#33999")
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", 
               "#0072B2", "#D55E00", "#CC79A7")
```


```{r}
# Load individual datasets

file_path <- c("C:/Users/ethan.walker/Box/Ethan Walker UM/R/KidsAIR/")

health_exposure_data_sampling_day <- 
  read_rds(paste0(file_path, "Output/health_exposure_data_sampling_day.rds")) %>% 
  mutate(home_sqft_2level = cut(home_sqft, breaks = c(0, 1400, 100000),
                                labels = c("<130 sq m", "130+ sq m")))

health_data_merged <- 
  read_rds(paste0(file_path, "Output/health_data_merged.rds")) 


kids_linked_ids <- read_rds(paste0(file_path, "Output/kids_linked_ids_final.rds")) 

treatments_masked <- read_csv(paste0(file_path, "Input/KidsAIRrnd_masked.csv"), na = "NULL") %>% 
  mutate(home = gsub(" ", "", x = home),
         home = gsub("_", "", x = home))

demographics <- read_rds(paste0(file_path, "Output/demographics_final.rds")) %>% 
  filter(area == "WMT") %>% 
  filter(winter_id == 1) %>% 
  distinct(home_winter_id, .keep_all = TRUE)

exposure_analysis_data_long <- 
  read_rds(paste0(file_path, "Output/exposure_analysis_data_long_new.rds")) 

exposure_analysis_data_medium <- 
  read_rds(paste0(file_path, "Output/exposure_analysis_data_medium.rds")) 

exposure_analysis_data_short <- 
  read_rds(paste0(file_path, "Output/exposure_analysis_data_short.rds"))

sums_rolling_pm_data <- 
  read_rds(paste0(file_path, "Output/sums_rolling_pm_data.rds"))
```

# Count number of kids initially randomized
```{r}
file_path <- c("C:/Users/ethan.walker/Box/Ethan Walker UM/R/KidsAIR/")

ak_demographics <- read_rds(paste0(file_path, "Output/ak_demographic_data.rds"))
nn_demographics <- read_rds(paste0(file_path, "Output/nn_demographic_data.rds"))
wmt_demographics <- read_rds(paste0(file_path, "Output/wmt_demographic_data.rds"))

kids_demographics <- rbind(ak_demographics, nn_demographics, wmt_demographics) %>% 
  filter(!is.na(treatment)) %>% 
  filter(!is.na(child_id_num)) %>% 
  count(area, winter_id, treatment) %>% 
  filter(winter_id != 2)
kids_demographics
```

# Count number of households initially randomized
```{r}
file_path <- c("C:/Users/ethan.walker/Box/Ethan Walker UM/R/KidsAIR/")

ak_ids <- read_rds(paste0(file_path, "Output/ak_ids_linked.rds")) %>% 
  mutate(home = gsub(" ", "", x = home),
         home = gsub("_", "", x = home))
nn_ids <- read_rds(paste0(file_path, "Output/nn_ids_linked.rds")) %>% 
  mutate(home = gsub(" ", "", x = home),
         home = gsub("_", "", x = home))
wmt_ids <- read_rds(paste0(file_path, "Output/wmt_ids_linked.rds")) %>% 
  mutate(home = gsub(" ", "", x = home),
         home = gsub("_", "", x = home))

kids_ids <- rbind(ak_ids, nn_ids, wmt_ids) %>% 
  filter(!is.na(treatment)) %>% 
  ### WMA222 and WMA 233 had a treatment but no kids - not counting in flow chart
  filter(home != "WMA222" & home != "WMA233") %>%
  count(area, winter_id, treatment) %>% 
  filter(winter_id != 2)

kids_ids <- rbind(ak_ids, nn_ids, wmt_ids) %>% 
  select(-treatment) %>% 
  filter(winter_id == 1) %>% 
  filter(!is.na(home)) %>% 
  mutate(original = 1) %>% 
  right_join(treatments_masked, by = "home") %>% 
  filter(home != "WMA222" & home != "WMA233") %>%
  filter(original == 1)

kids_ids
```


# Demographics summary
```{r}
table(demographics$hispanic_parent, demographics$race_parent, demographics$gender_parent)
```

# Count number of households and kids that participated by area and winter
```{r}
# number of households, total and by area
study_homes <- health_exposure_data_sampling_day %>% 
  distinct(home, winter_id, .keep_all = TRUE) %>%
  count(winter_id, treatment_assigned)
study_homes


study_kids <- health_exposure_data_sampling_day %>% 
  dplyr::select(area, home, child_id_char, child_id_num, winter_id, treatment_assigned) %>% 
  filter(!is.na(child_id_char)) %>% 
  distinct(area, child_id_char, winter_id, .keep_all = TRUE) %>% 
  count(winter_id, treatment_assigned)
study_kids
```


```{r}
# add new vars to dataset
checkdata <- health_exposure_data_sampling_day %>% 
  select(area, home, residents_under_five)
```

```{r}
demographics_summary <- health_exposure_data_sampling_day %>% 
  filter(winter_id == 1 | winter_id == 0) %>% 
  arrange(winter_id) %>% 
  #filter(treatment_assigned == "Placebo") %>%
  distinct(child_id_char, .keep_all = TRUE)

# summary data for manuscript tables
char_funct_total <- function(var, data = health_exposure_data_sampling_day){

demographics_summary <- data %>% 
  rename(new_var = var) %>% 
  filter(winter_id != 2) %>% 
  #filter(treatment_assigned == "Placebo") %>%
  arrange(area, child_id_char, new_var) %>% 
  distinct(area, child_id_char, .keep_all = TRUE) %>% # change to child_id_char or home as necessary
  mutate(total_n = n()) %>% 
  group_by(area) %>% 
  mutate(area_n = n()) %>% 
  group_by(new_var) %>% 
  mutate(n = n(),
         percent = n()/total_n) %>% 
  distinct(new_var, .keep_all = TRUE) %>% 
  dplyr::select(new_var, n, percent)
demographics_summary
}

char_funct_area <- function(var, data = health_exposure_data_sampling_day){

demographics_summary <- data %>% 
  rename(new_var = var) %>% 
  filter(winter_id != 2) %>% 
  #filter(treatment_assigned == "Placebo") %>% 
  arrange(area, child_id_char, new_var) %>% 
  distinct(area, child_id_char, .keep_all = TRUE) %>% # change to child_id_char or home as necessary
  mutate(total_n = n()) %>% 
  group_by(treatment_assigned) %>% 
  mutate(area_n = n()) %>% 
  group_by(treatment_assigned, new_var) %>% 
  mutate(n = n(),
         percent = n()/area_n) %>% 
  distinct(new_var, .keep_all = TRUE) %>% 
  dplyr::select(new_var, n, percent) %>% 
  arrange(treatment_assigned, new_var)
demographics_summary
}

# distinct by child - change var in functions above to child_id_char
char_funct_total("gender")
char_funct_area("gender")
char_funct_total("hispanic_parent")
char_funct_area("hispanic_parent")
char_funct_total("race_child")
char_funct_area("race_child")

# distinct by home - change var in functions above to home
char_funct_total("gender_parent")
char_funct_area("gender_parent")
char_funct_total("hispanic_parent")
char_funct_area("hispanic_parent")
char_funct_total("race_parent")
char_funct_area("race_parent")
char_funct_total("education_3level")
char_funct_area("education_3level")
char_funct_total("income_3level")
char_funct_area("income_3level")
char_funct_total("home_floors_2level")
char_funct_area("home_floors_2level")
char_funct_total("home_sqft_2level")
char_funct_area("home_sqft_2level")
char_funct_total("home_year_built_2level")
char_funct_area("home_year_built_2level")
char_funct_total("home_pets_2level")
char_funct_area("home_pets_2level")
char_funct_total("home_pets")
char_funct_area("home_pets")
char_funct_total("stove_age_3level")
char_funct_area("stove_age_3level")
char_funct_total("chimney_clean_3level")
char_funct_area("chimney_clean_3level")
char_funct_total("wood_collect_method_2level")
char_funct_area("wood_collect_method_2level")
char_funct_total("wood_collect_2level")
char_funct_area("wood_collect_2level")
char_funct_total("stove_grade_3level")
char_funct_area("stove_grade_3level")
char_funct_total("burn_level_3level")
char_funct_area("burn_level_3level")
char_funct_total("ruca_code")
char_funct_area("ruca_code")
char_funct_total("ruca_code_2")
char_funct_area("ruca_code_2")
char_funct_total("ruca_code_3")
char_funct_area("ruca_code_3")
```


```{r}
# summary data for manuscript tables
num_funct_total <- function(var, data = health_exposure_data_sampling_day){

demographics_summary <- data %>% 
  rename(new_var = var) %>% 
  mutate(new_var = as.numeric(new_var)) %>% 
  #mutate(new_var = (as.numeric(new_var)-32)*5/9) %>% 
  filter(winter_id == 1) %>% 
  filter(treatment_assigned == "Filter") %>% 
  arrange(new_var) %>% 
  distinct(home, .keep_all = TRUE) %>% 
  filter(!is.na(new_var)) %>% 
  dplyr::select(area, home, new_var) %>% 
  summarize(mean_var = mean(new_var), sd_var = sd(new_var), n_var = n(), 
            min_var = min(new_var), med_var = median(new_var), max_var = max(new_var))
demographics_summary
}

num_funct_area <- function(var, data = health_exposure_data_sampling_day){

demographics_summary <- data %>% 
  rename(new_var = var) %>%
  mutate(new_var = as.numeric(new_var)) %>% 
  #mutate(new_var = (as.numeric(new_var)-32)*5/9) %>%
  filter(winter_id == 1) %>% 
  filter(treatment_assigned == "Filter") %>% 
  arrange(new_var) %>% 
  distinct(home, .keep_all = TRUE) %>% 
  filter(!is.na(new_var)) %>% 
  dplyr::select(area, home, new_var) %>% 
  group_by(area) %>% 
  summarize(mean_var = mean(new_var), sd_var = sd(new_var), n_var = n(), 
            min_var = min(new_var), med_var = median(new_var), max_var = max(new_var))
demographics_summary
}


num_funct_total("residents_under_five")
num_funct_area("residents_under_five")
num_funct_total("home_bedrooms")
num_funct_area("home_bedrooms")
num_funct_total("pm_mean_sampling_period")
num_funct_area("pm_mean_sampling_period")
num_funct_total("pm_sample_interval")
num_funct_area("pm_sample_interval")
num_funct_total("moisture_closest")
num_funct_area("moisture_closest")
num_funct_total("temp_indoor_max")
num_funct_area("temp_indoor_max")
num_funct_total("rh_indoor_max")
num_funct_area("rh_indoor_max")
num_funct_total("mean_temp")
num_funct_area("mean_temp")
num_funct_total("amb_pm_24hr")
num_funct_area("amb_pm_24hr")
num_funct_total("sums_events_sampling_period_2.5")
num_funct_area("sums_events_sampling_period_2.5")
num_funct_total("sums_events_sampling_period_5")
num_funct_area("sums_events_sampling_period_5")
num_funct_total("sums_events_sampling_period_7.5")
num_funct_area("sums_events_sampling_period_7.5")
```


```{r}
other_vars_total <- health_exposure_data_sampling_day %>% 
  rename(new_var = home_act_sweep_sum) %>% 
  mutate(new_var = as.numeric(new_var)) %>% 
  filter(winter_id == 1) %>% 
  filter(treatment_assigned == "Placebo") %>% 
  arrange(new_var) %>% 
  distinct(home, .keep_all = TRUE) %>% 
  filter(!is.na(new_var)) %>% 
  select(area, home, new_var) %>% 
  summarize(mean_var = mean(new_var), sd_var = sd(new_var), n_var = n(), 
            min_var = min(new_var), med_var = median(new_var), max_var = max(new_var))
other_vars_total

other_vars_area <- health_exposure_data_sampling_day %>% 
  rename(new_var = home_act_sweep_sum) %>% 
  mutate(new_var = as.numeric(new_var)) %>% 
  filter(winter_id == 1) %>% 
  filter(treatment_assigned == "Placebo") %>% 
  arrange(new_var) %>% 
  distinct(home, .keep_all = TRUE) %>% 
  filter(!is.na(new_var)) %>% 
  select(area, home, new_var) %>% 
  group_by(area) %>% 
  summarize(mean_var = mean(new_var), sd_var = sd(new_var), n_var = n(), 
            min_var = min(new_var), med_var = median(new_var), max_var = max(new_var))
other_vars_area


other_vars_total <- health_exposure_data_sampling_day %>% 
  dplyr::select(area, child_id_num, race_child, treatment_assigned) %>% 
  arrange(race_child) %>% 
  distinct(area, child_id_num, .keep_all = TRUE) 
```



```{r, fig.height=1.25, fig.width=4.15}
# Poster figures

plot_data <- health_exposure_data_sampling_day %>% 
  mutate(income_3level = factor(income_3level, 
                                labels = c("< $20,000", "$20,000-$49,999", "$50,000+")),
         chimney_clean_3level = factor(chimney_clean_3level, 
                                labels = c("< 6 months ago", "6-12 months ago", "12 + months ago")),
         stove_grade_3level = factor(stove_grade_3level, 
                                labels = c("High-quality", "Medium-quality", "Low-quality")),
         area = factor(area,
                       labels = c("Alaska", "Navajo Nation", "Western Montana")))
  

home_char_function <- function(data, var, title_label) {
  
  home_char_plot <- data %>% 
  filter(winter_id == 1 & treatment_assigned == "Placebo") %>% 
  arrange(area, home, sampling_day) %>% 
  distinct(home, .keep_all = TRUE) %>% 
  select(area, var) %>% 
  rename(plot_var = var) %>% 
  filter(!is.na(plot_var)) %>% 
  ggplot() +
    geom_bar(aes(fct_rev(plot_var), fill = area)) +
    theme_minimal() +
    coord_flip() +
    theme(axis.text.x = element_text(size = 16, colour = "black", 
                                     vjust = 0.7, hjust = 0.7),
          axis.text.y = element_text(size = 16, colour = "black"),
          title = element_text(size = 16, colour = "black"),
          legend.text = element_blank(),
          legend.title = element_blank(),
          legend.position = "",
          axis.title.y = element_blank(),
          axis.title.x = element_blank(),
          axis.line.x = element_line(colour = "black", size = 1.2), 
          axis.line.y = element_line(colour = "black", size = 1.2), 
          axis.ticks = element_blank(),
          panel.grid = element_blank()) +
    labs(title = title_label) +
    scale_fill_manual(values = cbPalette)
  home_char_plot
  
}

home_char_function(plot_data, "income_3level", "Household income")
home_char_function(plot_data, "residents_under5_2level", "Kids < 5 years of age")
home_char_function(plot_data, "home_floors_2level", "Home floors/levels")
home_char_function(plot_data, "stove_age_3level", "Stove age")
home_char_function(plot_data, "chimney_clean_3level", "Chimney cleaned")
home_char_function(plot_data, "wood_collect_2level", "Wood collected")
home_char_function(plot_data, "stove_grade_3level", "Stove grade")
```


```{r}
# Summary data for results letters to send to participants

home_summary <- health_exposure_data_sampling_day %>% 
  group_by(home) %>% 
  arrange(home, sampling_day) %>% 
  select(area, home, winter_id, pm_mean_sampling_period, pm_mean_sampling_day, 
         rh_indoor_min, rh_indoor_max) %>% 
  mutate(daily_min = min(pm_mean_sampling_day, na.rm = TRUE),
         daily_max= max(pm_mean_sampling_day, na.rm = TRUE)) %>% 
  distinct(home, .keep_all = TRUE) %>% 
  replace_with_na_all(condition = ~.x %in% c("Inf", "-Inf")) %>% 
  mutate("Min RH (%)" = if_else(rh_indoor_min > rh_indoor_max, rh_indoor_max, rh_indoor_min),
         "Max RH (%)" = if_else(rh_indoor_max < rh_indoor_min, rh_indoor_min, rh_indoor_max)) %>% 
  arrange(area, home) %>% 
  mutate("Mean PM2.5 (ug/m3)" = round(pm_mean_sampling_period, digits = 1),
         "Min PM2.5 (ug/m3)" = round(daily_min, digits = 1),
         "Max PM2.5 (ug/m3)" = round(daily_max, digits = 1),
         check = if_else(`Min RH (%)` > `Max RH (%)`, 1, 0)) %>% 
  select(-rh_indoor_min, -rh_indoor_max, -pm_mean_sampling_period, -check,
         -daily_min, -daily_max) %>% 
  rename(Area = area,
         Home = home,
         Winter = winter_id)

write_csv(home_summary, paste0(file_path, "Output/kids_letter_data.csv"), na = "")
```


# Table S1 summary data
```{r}
analysis_data <- read_rds(paste0(file_path, 
                                 "Output/kids_analysis_data_1obs_per_child.rds")) %>% 
  mutate(pm_mean_sampling_period_iqr = pm_mean_sampling_period/25,
         pm_mean_at_home_sampling_period_iqr = pm_at_home_sampling_period/25,
         lrti_events_di_total = as.factor(lrti_events_di_total),
         person_time_at_risk_iqr = person_time_at_risk/20,
         child_age = factor(child_age, levels = c("< 1", "1+")),
         moisture_di = cut(moisture_closest, breaks = c(0, 11, 100),
                           labels = c("<11%", ">=11%")),
         stove_age_di = fct_collapse(stove_age_3level, 
                                     "0-5 years old" = "0-5 years old",
                                     "6+ years old" = c("6-15 years old", "16 + years old"),
                                     "Do not know" = "Do not know")) 
  #filter(area == "WMT")
  #filter(gender == "Female")
  #filter(home_sqft_2level == "1500+")

analysis_data_winter1 <- read_rds(paste0(file_path, 
                                 "Output/kids_analysis_data_2obs_per_child.rds")) %>% 
  mutate(pm_mean_sampling_period_iqr = pm_mean_sampling_period/25,
         pm_mean_at_home_sampling_period_iqr = pm_at_home_sampling_period/25,
         lrti_events_di_winter = as.factor(lrti_events_di_winter),
         child_age = factor(child_age, levels = c("< 1", "1+")),
         moisture_di = cut(moisture_closest, breaks = c(0, 11, 100),
                           labels = c("<11%", ">=11%")),
         stove_age_di = fct_collapse(stove_age_3level, 
                                     "0-5 years old" = "0-5 years old",
                                     "6+ years old" = c("6-15 years old", "16 + years old"),
                                     "Do not know" = "Do not know")) %>% 
  filter(person_time_at_risk_winter > 0) %>% 
  #filter(area == "WMT") %>% 
  filter(winter_id == 1)


n_summary_table <- analysis_data_winter1 %>% 
  distinct(area, home, .keep_all = T) %>% 
  mutate(int_var = stove_grade_3level) %>% 
  filter(!is.na(int_var)) %>% 
  dplyr::select(area, home, int_var, treatment_assigned) %>% 
  group_by(int_var, treatment_assigned) %>% 
  summarize("n" = n())
n_summary_table

pm_summary_table <- analysis_data_winter1 %>% 
  distinct(area, home, .keep_all = T) %>% 
  mutate(int_var = stove_grade_3level) %>% 
  filter(!is.na(int_var)) %>% 
  filter(!is.na(pm_mean_sampling_period)) %>% 
  group_by(int_var, treatment_assigned) %>% 
  summarize("n" = n(),
            "Mean PM" = mean(pm_mean_sampling_period, na.rm = TRUE),
            "SD PM" = sd(pm_mean_sampling_period, na.rm = TRUE),
            "Median PM" = median(pm_mean_sampling_period, na.rm = TRUE),
            "Min PM" = min(pm_mean_sampling_period, na.rm = TRUE),
            "Max PM" = max(pm_mean_sampling_period, na.rm = TRUE))
pm_summary_table

n_summary_table <- analysis_data %>% 
  distinct(area, child_id_num, .keep_all = T) %>% 
  mutate(int_var = stove_grade_3level) %>% 
  filter(!is.na(int_var)) %>% 
  group_by(int_var, treatment_assigned) %>% 
  summarize("n" = n())
n_summary_table

lrti_summary_table <- analysis_data %>% 
  distinct(area, child_id_num, .keep_all = T) %>% 
  mutate(int_var = stove_grade_3level) %>% 
  filter(!is.na(int_var)) %>% 
  group_by(int_var, treatment_assigned) %>% 
  mutate(lrti_events_num = as.numeric(lrti_events_di_total),
         lrti_events_num = lrti_events_num - 1) %>%  
  summarize("n" = n(),
            "Total LRTI" = sum(lrti_events_num, na.rm = TRUE),
            "Group %" = `Total LRTI`/n()*100)
lrti_summary_table
```

# Check ambient temp within groups of self-reported relative stove use
```{r}
analysis_data <- read_rds(paste0(file_path, 
                                 "Output/kids_analysis_data_2obs_per_child.rds"))

summary_results <- analysis_data %>% 
  select(home, area, winter_id, burn_level_3level, amb_temp_lrti) %>% 
  group_by(burn_level_3level) %>% 
  summarize(mean(amb_temp_lrti, na.rm = T),
            median(amb_temp_lrti, na.rm = T))

summary_results
```

