---
title: "KidsAIR: merge health datasets"
author: "Ethan Walker"
date: "Started 27 March 2020, Updated 26 June 2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
library(tidyverse)
library(readxl)
library(naniar)
library(lubridate)
library(zoo)
library(lme4)
library(lmerTest)
```

# Load individual datasets
```{r}
file_path <- c("C:/Users/ethan.walker/Box/Ethan Walker UM/R/KidsAIR/")

at_home_pm_merged <- 
  read_rds(paste0(file_path, "Output/at_home_pm_merged.rds"))
kids_med_visit <- 
  read_rds(paste0(file_path, "Output/kids_med_visit.rds")) %>% 
  mutate(visit_date = med_visit_date) 
kids_birth_infancy <- 
  read_rds(paste0(file_path, "Output/kids_birth_infancy.rds")) %>% 
  select(-home_id)
kids_csq <- 
  read_rds(paste0(file_path, "Output/kids_csq.rds")) 
kids_lrti <- 
  read_rds(paste0(file_path, "Output/kids_lrti.rds")) %>% 
  select(-home_id) %>% 
  mutate(winter_id = as.character(winter_id))
kids_medical_records <- 
  read_rds(paste0(file_path, "Output/kids_medical_records.rds")) %>% 
  select(-visit_date)
```


# Initial data merge - long format
```{r}
health_merged1 <- kids_csq %>% 
  select(-home_id) %>% 
  mutate(visit_date = csq_date) %>% 
  full_join(kids_med_visit, by = c("area", "home", "home_winter_id", 
                                   "treatment_assigned", "treatment_actual",
                                   "winter_id", "child_id_num", "visit_date")) %>% 
  select(area, home, home_winter_id, winter_id, child_id_num, visit_date,
         treatment_assigned, treatment_actual, csq_date:med_visit_mean_temp) %>% 
  arrange(area, home, home_winter_id, winter_id, child_id_num, visit_date) %>% 
  distinct(child_id_num, visit_date, .keep_all = TRUE) %>% 
  ungroup()


#health_merged2 <- health_merged1 %>% 
#  left_join(child_home_winter, by = c("area", "home", "home_winter_id", 
#                                      "treatment_assigned", "treatment_actual",
#                                      "winter_id", "child_id_num")) %>% 
#  arrange(area, home, home_winter_id, winter_id, child_id_num, visit_date) %>% 
#  ungroup()


health_merged2 <- health_merged1 %>% 
  left_join(kids_birth_infancy, by = c("area", "home", "home_winter_id", 
                                       "treatment_assigned", "treatment_actual",
                                       "winter_id", "child_id_num")) %>% 
  mutate(sample_date = as.character(visit_date)) %>% 
  arrange(area, home, home_winter_id, winter_id, child_id_num, visit_date) %>% 
  ungroup()


health_merged3 <- health_merged2 %>% 
  full_join(at_home_pm_merged, by = c("area", "home", "home_winter_id", "winter_id", 
                                      "child_id_num", "sample_date", 
                                      "treatment_assigned", "treatment_actual")) %>% 
  arrange(area, home, home_winter_id, winter_id, child_id_num, sample_date) %>% 
  select(area, home, home_winter_id, winter_id, child_id_num, visit_date,
         treatment_assigned, treatment_actual, 
         sample_date, sampling_day, at_home_location, 
         pm_at_home_sampling_day, pm_at_home_sampling_period, csq_date:at_home) %>% 
  ungroup() %>% 
  filter(!is.na(home))


#health_merged5 <- health_merged4 %>% 
# left_join(kids_medical_records, by = c("area", "home", "home_winter_id", "winter_id", 
#                                      "child_id_num", "treatment")) %>% 
#  arrange(area, home, home_winter_id, winter_id, child_id_num, sample_date) %>% 
#  select(area, home, home_winter_id, winter_id, child_id_num, visit_date,
#         treatment, sample_date, sampling_day, at_home_location, 
#         pm_at_home_sampling_day, pm_at_home_sampling_period, csq_date:med_rec_comments) %>% 
#  ungroup()


health_merged4 <- health_merged3 %>% 
  left_join(kids_lrti, by = c("area", "home", "home_winter_id", "winter_id", 
                              "child_id_num", "treatment_assigned", "treatment_actual")) %>% 
  arrange(area, home, home_winter_id, winter_id, child_id_num, sample_date) %>% 
  select(area, home, home_winter_id, winter_id, child_id_num, visit_date,
         treatment_assigned, treatment_actual, sample_date, sampling_day, at_home_location, 
         pm_at_home_sampling_day, pm_at_home_sampling_period, csq_date:lrti_professional_comments) %>% 
  ungroup() 


write_rds(health_merged3, paste0(file_path, "Output/health_data_merged.rds"))
write_csv(health_merged3, paste0(file_path, "Output/health_data_merged.csv"), na = "")
```


# Merge full health data with exposure data
```{r}
file_path <- c("C:/Users/ethan.walker/Box/Ethan Walker UM/R/KidsAIR/")

exposure_analysis_data_medium <- 
  read_rds(paste0(file_path, "Output/exposure_analysis_data_medium.rds")) 
  
health_data_merged <- 
  read_rds(paste0(file_path, "Output/health_data_merged.rds")) 

demographics <- read_rds(paste0(file_path, "Output/demographics_final.rds")) %>% 
  select(child_id_num, child_id_char, area, winter_id)

ruca_mt <- 
  read_xls(paste0(file_path, "Input/ruca2/ruca2_MT.xls")) %>% 
  rename(zip = ZIPN,
         ruca_code = RUCA2) %>% 
  select(zip, ruca_code)

ruca_ak <- 
  read_xls(paste0(file_path, "Input/ruca2/ruca2_AK.xls")) %>% 
  rename(zip = ZIPN,
         ruca_code = RUCA2) %>% 
  select(zip, ruca_code)

ruca_az <- 
  read_xls(paste0(file_path, "Input/ruca2/ruca2_AZ.xls")) %>% 
  rename(zip = ZIPN,
         ruca_code = RUCA2) %>% 
  select(zip, ruca_code)

ruca_nm <- 
  read_xls(paste0(file_path, "Input/ruca2/ruca2_NM.xls")) %>% 
  rename(zip = ZIPN,
         ruca_code = RUCA2) %>% 
  select(zip, ruca_code)

ruca_ut <- 
  read_xls(paste0(file_path, "Input/ruca2/ruca2_UT.xls")) %>% 
  rename(zip = ZIPN,
         ruca_code = RUCA2) %>% 
  select(zip, ruca_code)

ruca_codes <- rbind(ruca_mt, ruca_ak, ruca_az, ruca_nm, ruca_ut)



health_exposure_data_sampling_day <- health_data_merged %>% 
  select(-pm_mean_sampling_day, -pm_mean_sampling_period, -day_of_week,
         -pm_spike_1000, -pm_spike_2000, -pm_spike_5000) %>% 
  mutate(winter_id = as.character(winter_id)) %>% 
  full_join(exposure_analysis_data_medium,
            by = c("area", "child_id_num", "home", "home_winter_id", "winter_id", 
                   "treatment_assigned", "treatment_actual",
                   "sampling_day")) %>% 
  filter(!is.na(home)) %>% 
  filter(!is.na(child_id_num)) %>% 
  select(-child_id_char) %>% 
  left_join(demographics, by = c("area", "winter_id", "child_id_num")) %>% 
  select(area, home, home_id, home_winter_id, winter_id, child_id_num, child_id_char, 
         treatment_assigned, treatment_actual, sampling_day, visit_date:amb_pm_sampling_period_5) %>% 
  left_join(ruca_codes, by = "zip") %>% 
  mutate(ruca_code_2 = if_else(ruca_code >= 10, 10, ruca_code),
         ruca_code_2 = if_else(ruca_code_2 == 7.4, 7, ruca_code_2),
         ruca_code = as.factor(ruca_code),
         ruca_code_2 = as.factor(ruca_code_2),
         ruca_code_3 = fct_collapse(ruca_code_2,
                                    "metro" = c("1", "2"),
                                    "small_town" = c("7", "8", "9"),
                                    "rural" = c("10")))


write_rds(health_exposure_data_sampling_day, 
          paste0(file_path, "Output/health_exposure_data_sampling_day.rds"))
write_csv(health_exposure_data_sampling_day, 
          paste0(file_path, "Output/health_exposure_data_sampling_day.csv"), na = "")
```

```{r}
health_exposure_data_sampling_day <- 
  read_rds(paste0(file_path, "Output/health_exposure_data_sampling_day.rds")) %>% 
  select(area, home, zip)


save_var_names <- data.frame(t(health_exposure_data_sampling_day)) %>% 
  rownames_to_column() %>% 
  select(rowname)

#write_csv(save_var_names, paste0(file_path, "Output/kids_data_var_names.csv"), na = "")
```

