---
title: "Kids Moisture Summary"
author: "Ethan Walker"
date: "Started 22 Nov 2019, Updated 16 March 2020"
output: powerpoint_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE, 
                      include = TRUE, warning = FALSE)
```

```{r, message=FALSE}
library(tidyverse)
library(readxl)
library(naniar)
library(lubridate)
library(zoo)
library(knitr)
jv_palette <- c("#330099","#CC0066","#FF6633", 
                 "#0099CC", "#FF9900","#CC6633",
                  "#FF3366", "#33CC99", "#33999")
```

```{r}
# Load data
moisture_clean <- read_rds("Output/moisture_clean.rds")
kids_linked_ids <- read_rds("Output/kids_linked_ids.rds")
pm_clean <- read_rds("Output/pm_clean.rds")
```


```{r, include=FALSE}
# Moisture content summary stats
## Average of 3 measurements

summary_moisture <- moisture_clean %>%
  filter(winter_id == 1 & treatment == "Placebo") %>% 
  group_by(area) %>% 
  summarize(mean = mean(moisture_ave, na.rm = TRUE), 
            SD = sd(moisture_ave, na.rm = TRUE),
            median = median(moisture_ave, na.rm = TRUE),
            min = min(moisture_ave, na.rm = TRUE), 
            max = max(moisture_ave, na.rm = TRUE)) %>%
  select(-area) %>% 
  t() 
kable(summary_moisture, col.names = c("Alaska", "Navajo", "Montana"), 
      digits = 1, align = "c")
```


```{r, include=FALSE}
wood_split <- moisture_clean %>% 
  filter(winter_id == 1 & treatment == "Placebo") %>% 
  filter(!is.na(moisture_split)) %>% 
  group_by(area, moisture_split) %>% 
  summarise(n = n())
kable(wood_split, align = "c")
```


```{r, fig.height=6, fig.width=7}
boxplots_moisture <- moisture_clean %>% 
  filter(winter_id == 1 & treatment == "Placebo") %>% 
  select(area, moisture_ave) %>% 
  na.exclude() %>% 
  ggplot(aes(area, moisture_ave)) +
    geom_boxplot(aes(size = 1), lwd = 1.2, colour = "black", 
               fatten = 1, outlier.size = 1.5, width = 0.35) +
    stat_summary(fun.y=mean, geom="point", shape=17, size=4, color="red",
                 position=position_nudge(x = -0.1, y = 0)) +
    stat_summary(aes(label=round(..y.., digits = 1)), fun.y=mean, geom="text", 
                 size=7, position=position_nudge(x = -0.35, y = 0)) +
    stat_summary(fun.y=median, geom="point", shape=16, size=4, color="blue",
                 position=position_nudge(x = 0.1, y = 0)) +
    stat_summary(aes(label=round(..y.., digits = 1)), fun.y=median, geom="text", 
                 size=7, position=position_nudge(x = 0.35, y = 0)) +
    theme_minimal() +
    ylim(0, 50) +
    labs(title = "Mean wood moisture content") +
    labs(y = "%") +
    theme(axis.text.x = element_text(size = 16, colour = "black"),
          title = element_text(size = 20, colour = "black"),
          axis.text.y = element_text(size = 16, colour = "black"),
          axis.title.y = element_text(size = 16,
                                      margin = margin(t = 0, r = 20, b = 0, l = 0)),
          axis.title.x = element_blank(),
          axis.line.x = element_line(colour = "black", size = 1.2), 
          axis.line.y = element_line(colour = "black", size = 1.2), 
          axis.ticks = element_blank())
boxplots_moisture
```

```{r, fig.height=6, fig.width=7}
bar_plot <- moisture_clean %>% 
  filter(winter_id == 1 & treatment == "Placebo") %>% 
  select(area, moisture_split) %>% 
  ggplot() +
    geom_bar(aes(moisture_split, fill = area)) +
    theme_minimal() +
    labs(title = "Was wood split?") +
    theme(axis.text.x = element_text(size = 16, colour = "black", 
                                     angle = 40, vjust = 0.7, hjust = 0.7),
          axis.text.y = element_text(size = 16, colour = "black"),
          title = element_text(size = 20, colour = "black"),
          legend.text = element_text(size = 14, colour = "black"),
          legend.title = element_text(size = 16, colour = "black"),
          axis.title.y = element_blank(),
          axis.title.x = element_blank(),
          axis.line.x = element_line(colour = "black", size = 1.2), 
          axis.line.y = element_line(colour = "black", size = 1.2), 
          axis.ticks = element_blank(),
          panel.grid = element_blank()) +
    scale_fill_manual(values = jv_palette)
bar_plot
```


```{r}
#### Abstract/manuscript tables ####

# Filter for homes that have PM data

# 93 Winter 1 placebo homes have PM data
pm_homes_placebo <- pm_clean %>% 
  filter(winter_id == 1) %>% 
  filter(treatment == "Placebo") %>% 
  group_by(area, home) %>% 
  mutate(initial_obs = if_else(pm_datetime_new == first_datetime_new, 1, 0)) %>% 
  filter(initial_obs == 1) %>% 
  mutate(pm_home = "true") %>% 
  select(area, home, home_winter_id, pm_home, first_datetime_new) %>% 
  separate(first_datetime_new, c("first_date", "first_time"), sep = " ", remove = TRUE) %>% 
  ungroup() %>% 
  arrange(area, home)

moisture_filtered <- moisture_clean %>% 
  # change to correct joining data of interest
  left_join(pm_homes_placebo, by = c("area", "home", "home_winter_id")) %>% 
  filter(pm_home == "true") %>% 
  filter(winter_id == 1) %>% 
  ungroup() %>%
  arrange(area, home)

moisture_filtered_time <- moisture_filtered %>% 
  # fix wrong date
  mutate(moisture_date = as.character(moisture_date),
         moisture_date = if_else(home == "CH220" & moisture_date == "2014-04-10",
                                 "2017-04-10", moisture_date),
         moisture_date = ymd(moisture_date)) %>% 
  mutate(moisture_date = ymd(moisture_date),
         first_date = ymd(first_date),
         time_diff = moisture_date - first_date,
         time_diff = as.numeric(abs(time_diff))) %>% 
  group_by(home) %>% 
  mutate(time_diff_rank = if_else(time_diff == min(time_diff, na.rm = TRUE), 1, 0)) %>%
  ungroup() %>% 
  filter(time_diff_rank == 1)
```


```{r, include=FALSE}
# Summarize numeric vars
kids_moisture <- moisture_filtered_time %>%  
  group_by(area) %>% 
  summarize("Mean" = mean(moisture_ave, na.rm = TRUE), 
            "SD" = sd(moisture_ave, na.rm = TRUE),
            "min" = min(moisture_ave, na.rm = TRUE), 
            "med" = median(moisture_ave, na.rm = TRUE), 
            "max" = max(moisture_ave, na.rm = TRUE))
kable(kids_moisture, digits = 1, align = "c")

# Summarize numeric vars
kids_moisture <- moisture_filtered_time %>%  
  group_by(area) %>% 
  summarize("Mean" = mean(time_diff, na.rm = TRUE), 
            "SD" = sd(time_diff, na.rm = TRUE),
            "min" = min(time_diff, na.rm = TRUE), 
            "med" = median(time_diff, na.rm = TRUE), 
            "max" = max(time_diff, na.rm = TRUE))
kable(kids_moisture, digits = 1, align = "c")

table(moisture_filtered$area, moisture_filtered$moisture_split)
```

