---
title: "Kids PM Summary"
author: "Ethan Walker"
date: "Started 22 Nov 2019, Updated April 14 2020"
output: pdf_document
header-includes:
    - \usepackage[labelformat=empty]{caption}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE, 
                      include = TRUE, warning = FALSE)
```

```{r, message=FALSE}
library(tidyverse)
library(readr)
library(readxl)
library(knitr)
library(lubridate)
library(kableExtra)
jv_palette <- c("#330099","#CC0066","#FF6633", 
                 "#0099CC", "#FF9900","#CC6633",
                  "#FF3366", "#33CC99", "#33999")
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", 
               "#0072B2", "#D55E00", "#CC79A7")
```

```{r}
# Load data
file_path <- c("C:/Users/ethan.walker/Box/Ethan Walker UM/R/KidsAIR/")

health_exposure_data_sampling_day <- 
  read_rds(paste0(file_path, "Output/health_exposure_data_sampling_day.rds"))

pm_clean <- read_rds(paste0(file_path, "Output/pm_clean.rds"))

exposure_analysis_data_long <- 
  read_rds(paste0(file_path, "Output/exposure_analysis_data_long_new.rds")) 

exposure_analysis_data_medium <- 
  read_rds(paste0(file_path, "Output/exposure_analysis_data_medium.rds")) 

exposure_analysis_data_short <- 
  read_rds(paste0(file_path, "Output/exposure_analysis_data_short.rds"))

sums_rolling_pm_data <- 
  read_rds(paste0(file_path, "Output/sums_rolling_pm_data.rds"))
```


```{r}
# homes that exceed PM guidelines
pm_guidelines <- health_exposure_data_sampling_day %>% 
  filter(winter_id == 1 & treatment_assigned == "Placebo") %>% 
  filter(pm_mean_sampling_period > 12) %>% 
  distinct(home, .keep_all = TRUE) %>% 
  group_by(area) %>% 
  count()
pm_guidelines


pm_guidelines <- pm_clean %>% 
  filter(winter_id == 1 & treatment_assigned == "Placebo") %>% 
  #group_by(area) %>% 
  mutate(total_obs = n()) %>% 
  filter(pm > 12) %>% 
  mutate(cutoff_obs = n(),
         cutoff_perc = cutoff_obs/total_obs*100) %>% 
  distinct(area, .keep_all = TRUE)
pm_guidelines


#Pm by different levels of covariates
pm_check <- health_exposure_data_sampling_day %>% 
  filter(winter_id == 1 & treatment_assigned == "Placebo") %>% 
  arrange(pm_mean_sampling_period) %>% 
  distinct(home, .keep_all = TRUE) %>% 
  group_by(chimney_clean_3level) %>% 
  summarize("n" = n(),
            "Mean PM" = round(mean(pm_mean_sampling_period, na.rm = TRUE)), 
            "SD PM" = round(sd(pm_mean_sampling_period, na.rm = TRUE)),
            "Min PM" = round(min(pm_mean_sampling_period, na.rm = TRUE)), 
            "25%" = round(quantile(pm_mean_sampling_period, 0.25, na.rm = TRUE)),
            "Median PM" = round(median(pm_mean_sampling_period, na.rm = TRUE)),
            "75%" = round(quantile(pm_mean_sampling_period, 0.75, na.rm = TRUE)),
            "Max PM" = round(max(pm_mean_sampling_period, na.rm = TRUE)))
pm_check


# closer look at stove grade and PM
pm_stove_grade <- health_exposure_data_sampling_day %>%
  select(area, home, pm_mean_sampling_period, stove_grade_3level, 
         treatment_assigned, winter_id, home_winter_id) %>% 
  filter(winter_id == 1 & treatment_assigned == "Placebo") %>% 
  arrange(pm_mean_sampling_period) %>% 
  distinct(home, .keep_all = TRUE) %>% 
  mutate(stove_grade_2level = fct_collapse(stove_grade_3level,
                                           "A" = "A",
                                           "C or F" = c("C", "F"))) %>% 
  group_by(stove_grade_2level) %>% 
  summarize("n" = n(),
            "Mean PM" = round(mean(pm_mean_sampling_period, na.rm = TRUE)), 
            "SD PM" = round(sd(pm_mean_sampling_period, na.rm = TRUE)),
            "Min PM" = round(min(pm_mean_sampling_period, na.rm = TRUE)), 
            "25%" = round(quantile(pm_mean_sampling_period, 0.25, na.rm = TRUE)),
            "Median PM" = round(median(pm_mean_sampling_period, na.rm = TRUE)),
            "75%" = round(quantile(pm_mean_sampling_period, 0.75, na.rm = TRUE)),
            "Max PM" = round(max(pm_mean_sampling_period, na.rm = TRUE)))
pm_stove_grade

model_data <- exposure_analysis_data_short %>% 
  filter(winter_id == 1 & treatment == "Placebo") %>% 
  filter(area == "WMT") %>% 
  filter(home == "WMA300") %>% 
  distinct(home, .keep_all = TRUE)

check_model <- lm(log(pm_mean_sampling_period) ~ stove_grade_3level,
                  data = model_data)

summary(check_model)
```

\pagebreak

```{r}
# Summary stats

pm_500 <- pm_clean %>% 
  filter(winter_id == 1 & treatment == "Placebo") %>% 
  mutate(pm = if_else(pm > 500, 500, pm)) %>% 
  group_by(area) %>% 
  summarize("n" = n(),
            "Mean PM" = round(mean(pm, na.rm = TRUE)), 
            "SD PM" = round(sd(pm, na.rm = TRUE)),
            "Min PM" = round(min(pm, na.rm = TRUE)), 
            "25%" = round(quantile(pm, 0.25, na.rm = TRUE)),
            "Median PM" = round(median(pm, na.rm = TRUE)),
            "75%" = round(quantile(pm, 0.75, na.rm = TRUE)),
            "Max PM" = round(max(pm, na.rm = TRUE))) 

pm_2000 <- pm_clean %>% 
  filter(winter_id == 1 & treatment == "Placebo") %>% 
  mutate(pm = if_else(pm > 2000, 2000, pm)) %>% 
  group_by(area) %>% 
  summarize("n" = n(),
            "Mean PM" = round(mean(pm, na.rm = TRUE)), 
            "SD PM" = round(sd(pm, na.rm = TRUE)),
            "Min PM" = round(min(pm, na.rm = TRUE)), 
            "25%" = round(quantile(pm, 0.25, na.rm = TRUE)),
            "Median PM" = round(median(pm, na.rm = TRUE)),
            "75%" = round(quantile(pm, 0.75, na.rm = TRUE)),
            "Max PM" = round(max(pm, na.rm = TRUE))) 

pm_summary <- pm_clean %>% 
  filter(winter_id == 1 & treatment == "Placebo") %>% 
  group_by(area) %>% 
  summarize("n" = n(),
            "Mean PM" = round(mean(pm, na.rm = TRUE)), 
            "SD PM" = round(sd(pm, na.rm = TRUE)),
            "Min PM" = round(min(pm, na.rm = TRUE)), 
            "25%" = round(quantile(pm, 0.25, na.rm = TRUE)),
            "Median PM" = round(median(pm, na.rm = TRUE)),
            "75%" = round(quantile(pm, 0.75, na.rm = TRUE)),
            "Max PM" = round(max(pm, na.rm = TRUE))) 

full_summary <- rbind(pm_summary, pm_2000, pm_500)

kable(full_summary, 
      caption = "Kids Indoor PM2.5 (Winter 1 Placebo)") %>% 
   kable_styling() %>% 
   pack_rows("No PM2.5 Cutoff", 1, 3) %>% 
   pack_rows("PM2.5 Cutoff: 2000", 4, 6) %>% 
   pack_rows("PM2.5 Cutoff: 500", 7, 9) 
```

\clearpage  

```{r}
pm_by_day <- pm_clean %>% 
  mutate(sampling_month = month(pm_datetime_new, abbr = TRUE)) %>% 
  mutate(day_of_week = factor(day_of_week,
                                 levels = c("Monday", "Tuesday", "Wednesday", "Thursday",
                                            "Friday", "Saturday", "Sunday"),
                                 labels = c("Mon", "Tues", "Wed", "Thur", "Fri", "Sat", "Sun"))) %>% 
  filter(winter_id == 1 & treatment == "Placebo") %>% 
  group_by(area, day_of_week) %>% 
  summarize("Mean PM" = mean(pm, na.rm = TRUE), 
            "SD PM" = sd(pm, na.rm = TRUE),
            "Min PM" = min(pm, na.rm = TRUE), 
            "25%" = quantile(pm, 0.25, na.rm = TRUE),
            "Median PM" = median(pm, na.rm = TRUE),
            "75%" = quantile(pm, 0.75, na.rm = TRUE),
            "Max PM" = max(pm, na.rm = TRUE))
kable(pm_by_day, 
      caption = "Kids Indoor PM2.5 by day of week (Winter 1 Placebo)", digits = 0)
```

\clearpage  

# Boxplots for PM by study area
```{r, fig.height=6, fig.width=8}
boxplots_kids_pm <- pm_clean %>% 
  filter(winter_id == 1 & treatment_assigned == "Placebo") %>% 
  ggplot(aes(area, pm)) +
    geom_boxplot(aes(size = 1), lwd = 1.2, colour = "black", 
               fatten = 1, outlier.size = 1.5, width = 0.35) +
    stat_summary(fun.y=mean, geom="point", shape=17, size=4, color="red",
                 position=position_nudge(x = -0.1, y = 0)) +
    stat_summary(aes(label=round(..y.., digits = 1)), fun.y=mean, geom="text", 
                 size=7, position=position_nudge(x = -0.35, y = 0)) +
    stat_summary(fun.y=median, geom="point", shape=16, size=4, color="blue",
                 position=position_nudge(x = 0.1, y = 0)) +
    stat_summary(aes(label=round(..y.., digits = 1)), fun.y=median, geom="text", 
                 size=7, position=position_nudge(x = 0.35, y = 0)) +
    theme_minimal() +
    #ylim(0, 500) +
    labs(y = expression(paste("PM"[2.5], " (", mu, g/m^3, ")"))) +
    theme(axis.text.x = element_text(size = 16, colour = "black"),
          axis.text.y = element_text(size = 16, colour = "black"),
          axis.title.y = element_text(size = 16,
                                      margin = margin(t = 0, r = 20, b = 0, l = 0)),
          axis.title.x = element_blank(),
          axis.line.x = element_line(colour = "black", size = 1.2), 
          axis.line.y = element_line(colour = "black", size = 1.2), 
          axis.ticks = element_blank())
boxplots_kids_pm
```

\pagebreak  

```{r, fig.height=4, fig.width=3}
boxplots_kids_pm <- health_exposure_data_sampling_day %>% 
  filter(winter_id == 1 & treatment_assigned == "Placebo") %>% 
  arrange(area, home, sampling_day) %>% 
  distinct(home, .keep_all = TRUE) %>% 
  ungroup() %>% 
  ggplot(aes(area, pm_mean_sampling_period)) +
    geom_boxplot(aes(size = 1), lwd = 1.2, colour = "black", 
               fatten = 1, outlier.size = 1.5, width = 0.35) +
    stat_summary(fun.y=mean, geom="point", shape=17, size=4, color="red") +
    #scale_y_log10() +
    theme_minimal() +
    labs(y = expression(paste("PM"[2.5], " (", mu, g/m^3, ")"))) +
    theme(axis.text.x = element_text(size = 16, colour = "black",
                                      margin = margin(t = 0, r = 0, b = 30, l = 0)),
          axis.text.y = element_text(size = 16, colour = "black"),
          axis.title.y = element_text(size = 16,
                                      margin = margin(t = 0, r = 20, b = 0, l = 0)),
          axis.title.x = element_blank(),
          axis.line.x = element_line(colour = "black", size = 1.2), 
          axis.line.y = element_line(colour = "black", size = 1.2), 
          axis.ticks = element_blank())
boxplots_kids_pm

ggsave("boxplots_kids_pm.jpg", height = 7, width = 4)
```

\pagebreak  

```{r, fig.height=6, fig.width=8}
boxplots_kids_pm <- pm_clean %>% 
  filter(winter_id == 1 & treatment == "Placebo") %>% 
  ggplot(aes(area, log(pm))) +
    geom_boxplot(aes(size = 1), lwd = 1.2, colour = "black", 
               fatten = 1, outlier.size = 1.5, width = 0.35) +
    stat_summary(fun.y=mean, geom="point", shape=17, size=4, color="red",
                 position=position_nudge(x = -0.1, y = 0)) +
    stat_summary(aes(label=round(..y.., digits = 1)), fun.y=mean, geom="text", 
                 size=7, position=position_nudge(x = -0.35, y = 0)) +
    stat_summary(fun.y=median, geom="point", shape=16, size=4, color="blue",
                 position=position_nudge(x = 0.1, y = 0)) +
    stat_summary(aes(label=round(..y.., digits = 1)), fun.y=median, geom="text", 
                 size=7, position=position_nudge(x = 0.35, y = 0)) +
    theme_minimal() +
    #ylim(0, 500) +
    labs(y = expression(paste("Log PM"[2.5], " (", mu, g/m^3, ")"))) +
    theme(axis.text.x = element_text(size = 16, colour = "black"),
          axis.text.y = element_text(size = 16, colour = "black"),
          axis.title.y = element_text(size = 16,
                                      margin = margin(t = 0, r = 20, b = 0, l = 0)),
          axis.title.x = element_blank(),
          axis.line.x = element_line(colour = "black", size = 1.2), 
          axis.line.y = element_line(colour = "black", size = 1.2), 
          axis.ticks = element_blank())
boxplots_kids_pm
```


```{r}
# check PM spikes
spikes_data <- health_exposure_data_sampling_day %>% 
  filter(winter_id == 1 & treatment_assigned == "Placebo") %>% 
  select(area, home, sampling_day, pm_mean_sampling_day, pm_mean_sampling_period,
         pm_spike_1000, pm_spike_2000, pm_spike_5000,
         income_3level, stove_grade_3level, chimney_clean_3level, home_floors_2level) %>% 
  filter(!is.na(pm_mean_sampling_period)) %>% 
  group_by(area, home) %>% 
  distinct(area, home, sampling_day, .keep_all = TRUE) %>% 
  mutate(pm_spike_1000 = if_else(pm_spike_1000 == "Yes", 1, 0),
         pm_spike_2000 = if_else(pm_spike_2000 == "Yes", 1, 0),
         pm_spike_5000 = if_else(pm_spike_5000 == "Yes", 1, 0),
         spike_sum_1000 = sum(pm_spike_1000),
         spike_sum_2000 = sum(pm_spike_2000),
         spike_sum_5000 = sum(pm_spike_5000)) %>% 
  distinct(area, home, .keep_all = TRUE) %>% 
  mutate(spike_sum_1000 = as.factor(spike_sum_1000),
         spike_sum_1000 = fct_collapse(spike_sum_1000, "0" = "0",
                                       "1" = "1",
                                       "2" = "2",
                                       "3+" = c("3", "5"))) %>% 
  ungroup() %>% 
  arrange(area, home)

spikes_summary <- spikes_data %>% 
  mutate(spike_sum_1000 = as.factor(spike_sum_1000),
         spike_sum_1000 = fct_collapse(spike_sum_1000, "0" = "0",
                                       "1" = "1",
                                       "2" = "2",
                                       "3+" = c("3", "5"))) %>% 
  group_by(spike_sum_1000) %>% 
  summarize("N" = n(),
            "Mean PM" = mean(pm_mean_sampling_period, na.rm = TRUE), 
            "SD PM" = sd(pm_mean_sampling_period, na.rm = TRUE),
            "Min PM" = min(pm_mean_sampling_period, na.rm = TRUE), 
            "Median PM" = median(pm_mean_sampling_period, na.rm = TRUE),
            "Max PM" = max(pm_mean_sampling_period, na.rm = TRUE))
spikes_summary


table(spikes_data$spike_sum_1000)
table(spikes_data$spike_sum_1000, spikes_data$stove_grade_3level)
```

