---
title: "KidsAIR wood stove grades and usage"
author: "Ethan Walker"
date: "Started 13 Jan 2020, Updated 18 Oct 2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
library(tidyverse)
library(readxl)
library(naniar)
library(lubridate)
library(zoo)
```

# Load, format, and save wood stove grade data
```{r}
file_path <- c("C:/Users/ethan.walker/Box/Ethan Walker UM/R/KidsAIR/")

##### WMT #####
# Load data
stove_grades_initial_wmt <- read_xlsx(paste0(file_path, "Input/WMT/stove.xlsx"), 
                                  na = c("NULL", ""))

wmt_stove_grades <- stove_grades_initial_wmt %>% 
  # rename variables
  mutate(home_id = as.factor(HomeID),
         home_winter_id = as.factor(HomeWinterID),
         stove_grade = as.factor(Score1),
         area = "WMT") %>% 
  select(home_id, home_winter_id, area, stove_grade) %>% 
  ungroup() %>% 
  arrange(home_winter_id) %>% 
  filter(!is.na(stove_grade)) %>% 
  filter(home_id != 0 & home_id != 999) 
  

# Save as RDS
write_rds(wmt_stove_grades, paste0(file_path, "Output/wmt_stove_grades.rds"))


##### NN #####
# Load data
stove_grades_initial_nn <- read_xlsx(paste0(file_path, "Input/NN/stove.xlsx"), 
                                  na = c("NULL", ""))

nn_stove_grades <- stove_grades_initial_nn %>% 
  # rename variables
  mutate(home_id = as.factor(HomeID),
         home_winter_id = as.factor(HomeWinterID),
         stove_grade = as.factor(Score1),
         area = "NN") %>% 
  select(home_id, home_winter_id, area, stove_grade) %>% 
  ungroup() %>% 
  arrange(home_winter_id) %>% 
  filter(!is.na(stove_grade)) %>% 
  filter(home_id != 0 & home_id != 999)

# Save as RDS
write_rds(nn_stove_grades, paste0(file_path, "Output/nn_stove_grades.rds"))


##### AK #####
# Load data
stove_grades_initial_ak <- read_xlsx(paste0(file_path, "Input/AK/stove.xlsx"), 
                                  na = c("NULL", ""))

ak_stove_grades <- stove_grades_initial_ak %>% 
  # rename variables
  mutate(home_id = as.factor(HomeID),
         home_winter_id = as.factor(HomeWinterID),
         stove_grade = as.factor(Score1),
         area = "AK") %>% 
  select(home_id, home_winter_id, area, stove_grade) %>% 
  ungroup() %>% 
  arrange(home_winter_id) %>% 
  filter(!is.na(stove_grade)) %>% 
  filter(home_id != 0 & home_id != 999)

# Save as RDS
write_rds(ak_stove_grades, paste0(file_path, "Output/ak_stove_grades.rds"))
```

# Join stove grade data from different areas
```{r}
file_path <- c("C:/Users/ethan.walker/Box/Ethan Walker UM/R/KidsAIR/")

wmt_stove_grades <- read_rds(paste0(file_path, "Output/wmt_stove_grades.rds"))
nn_stove_grades <- read_rds(paste0(file_path, "Output/nn_stove_grades.rds"))
ak_stove_grades <- read_rds(paste0(file_path, "Output/ak_stove_grades.rds"))

kids_stove_grades <- rbind(wmt_stove_grades, nn_stove_grades, ak_stove_grades)

write_rds(kids_stove_grades, paste0(file_path, "Output/kids_stove_grades.rds"))
```

# Clean up all stove grade data
```{r}
file_path <- c("C:/Users/ethan.walker/Box/Ethan Walker UM/R/KidsAIR/")
kids_stove_grades <- read_rds(paste0(file_path, "Output/kids_stove_grades.rds"))
kids_linked_ids <- read_rds(paste0(file_path, "Output/kids_linked_ids_final.rds"))


stove_grades_clean <- kids_stove_grades %>% 
  mutate(area = as.factor(area)) %>% 
  # Mark gave a couple of "D" grades when there was not enough info to score the stove
  # removing those "D" grades from final dataset
  filter(stove_grade != "D") %>% 
  select(-home_id) %>% 
  left_join(kids_linked_ids, by = c("area", "home_winter_id")) %>% 
  arrange(area, home, winter_id)

summary(stove_grades_clean)

# Some homes/stoves were graded during both winters, typically when new photos were added
# Since photos were added in these cases, grades may have changed from Winter 1 to Winter 2
# We can't make the assumption that the stove was exactly the same for both winters,
# so it will be best to use the grade corresponding to each winter for analysis.

write_rds(stove_grades_clean, paste0(file_path, "Output/stove_grades_clean.rds"))

# Dataset showing homes with no stove grade
stove_grades_na <- stove_grades_clean %>% 
  filter(is.na(stove_grade)) %>% 
  distinct(home_id) 
```

###############################################

# Load, format, and save wood stove use data
```{r}
file_path <- c("C:/Users/ethan.walker/Box/Ethan Walker UM/R/KidsAIR/")

##### WMT #####
# Load data
stove_use_initial_wmt <- read_csv(paste0(file_path, "Input/WMT/woodstoveusage.csv"), 
                                  na = c("NULL", ""))

wmt_stove_use <- stove_use_initial_wmt %>% 
  # rename variables
  mutate(home_winter_id = as.factor(HomeWinterID),
         burn_level = as.factor(Burning),
         wood_type = as.factor(Wood),
         wood_type_other = as.character(WhOtherWood),
         wood_collect = as.factor(WhenGet),
         wood_collect_method = as.factor(HowGet),
         wood_cords = as.numeric(Cords),
         area = "WMT") %>% 
  select(home_winter_id, area, burn_level, wood_type, wood_type_other,
         wood_collect, wood_collect_method, wood_cords) %>% 
  ungroup() %>% 
  arrange(home_winter_id)

# Save as RDS
write_rds(wmt_stove_use, paste0(file_path, "Output/wmt_stove_use.rds"))


##### NN #####
# Load data
stove_use_initial_nn <- read_csv(paste0(file_path, "Input/NN/woodstoveusage.csv"), 
                                  na = c("NULL", ""))

nn_stove_use <- stove_use_initial_nn %>% 
  # rename variables
  mutate(home_winter_id = as.factor(HomeWinterID),
         burn_level = as.factor(Burning),
         wood_type = as.factor(Wood),
         wood_type_other = as.character(WhOtherWood),
         wood_collect = as.factor(WhenGet),
         wood_collect_method = as.factor(HowGet),
         wood_cords = as.numeric(Cords),
         area = "NN") %>% 
  select(home_winter_id, area, burn_level, wood_type, wood_type_other,
         wood_collect, wood_collect_method, wood_cords) %>% 
  ungroup() %>% 
  arrange(home_winter_id)

# Save as RDS
write_rds(nn_stove_use, paste0(file_path, "Output/nn_stove_use.rds"))


##### AK #####
# Load data
stove_use_initial_ak <- read_csv(paste0(file_path, "Input/AK/woodstoveusage.csv"), 
                                  na = c("NULL", ""))

ak_stove_use <- stove_use_initial_ak %>% 
  # rename variables
  mutate(home_winter_id = as.factor(HomeWinterID),
         burn_level = as.factor(Burning),
         wood_type = as.factor(Wood),
         wood_type_other = as.character(WhOtherWood),
         wood_collect = as.factor(WhenGet),
         wood_collect_method = as.factor(HowGet),
         wood_cords = as.numeric(Cords),
         area = "AK") %>% 
  select(home_winter_id, area, burn_level, wood_type, wood_type_other,
         wood_collect, wood_collect_method, wood_cords) %>% 
  ungroup() %>% 
  arrange(home_winter_id)

# Save as RDS
write_rds(ak_stove_use, paste0(file_path, "Output/ak_stove_use.rds"))
```

# Join stove use data from different areas
```{r}
wmt_stove_use <- read_rds(paste0(file_path, "Output/wmt_stove_use.rds"))
nn_stove_use <- read_rds(paste0(file_path, "Output/nn_stove_use.rds"))
ak_stove_use <- read_rds(paste0(file_path, "Output/ak_stove_use.rds"))

kids_stove_use <- rbind(wmt_stove_use, nn_stove_use, ak_stove_use)

write_rds(kids_stove_use, paste0(file_path, "Output/kids_stove_use.rds"))
```

# Clean up all stove use data
```{r}
file_path <- c("C:/Users/ethan.walker/Box/Ethan Walker UM/R/KidsAIR/")
kids_stove_use <- read_rds(paste0(file_path, "Output/kids_stove_use.rds"))
kids_linked_ids <- read_rds(paste0(file_path, "Output/kids_linked_ids_final.rds"))


stove_use_clean <- kids_stove_use %>% 
  mutate(area = as.factor(area)) %>% 
  replace_with_na(replace = list(wood_cords = -999)) %>%
  replace_with_na(replace = list(wood_cords = 0)) %>%
  mutate(wood_collect = factor(wood_collect,
                               levels = c("Less than 1 week",
                                          "Between 1 week and 1 month",
                                          "Between 1 month and 3 months",
                                          "Between 3 months and 6 months",
                                          "Between 6 months and 1 year",
                                          "More than 1 year"),
                               labels = c("< 1 week",
                                          "1 week to 1 mo",
                                          "1 mo to 3 mo",
                                          "3 mo to 6 mo",
                                          "6 mo to 1 year",
                                          "> 1 yr"))) %>% 
  right_join(kids_linked_ids, by = c("area", "home_winter_id"))

summary(stove_use_clean)

write_rds(stove_use_clean, paste0(file_path, "Output/stove_use_clean.rds"))
```

#####################################

# Load, format, and KW monitor data
```{r}
file_path <- c("C:/Users/ethan.walker/Box/Ethan Walker UM/R/KidsAIR/")

##### WMT #####
# Load data
kw_initial_wmt <- read_csv(paste0(file_path, "Input/WMT/filtretechange.csv"), 
                                  na = c("NULL", "", "...", -99, -999, -9999))

kw_wmt <- kw_initial_wmt %>% 
  # rename variables
  mutate(home_winter_id = as.factor(HomeWinterID),
         kw_date = ymd(ChangeDate),
         kw_hours = as.numeric(KWHours),
         area = "WMT") %>% 
  select(home_winter_id, area, kw_date, kw_hours) %>% 
  filter(!is.na(kw_hours)) %>% 
  ungroup() %>% 
  arrange(home_winter_id, kw_date) 
  

# Save as RDS
write_rds(kw_wmt, paste0(file_path, "Output/kw_wmt.rds"))


##### NN #####
# Load data
kw_initial_nn <- read_csv(paste0(file_path, "Input/NN/filtretechange.csv"), 
                                  na = c("NULL", "", "...", -99, -999, -9999))

kw_nn <- kw_initial_nn %>% 
  # rename variables
  mutate(home_winter_id = as.factor(HomeWinterID),
         kw_date = ymd(ChangeDate),
         kw_hours = as.numeric(KWHours),
         area = "NN") %>% 
  select(home_winter_id, area, kw_date, kw_hours) %>% 
  filter(!is.na(kw_hours)) %>%  
  ungroup() %>% 
  arrange(home_winter_id, kw_date) 
  

# Save as RDS
write_rds(kw_nn, paste0(file_path, "Output/kw_nn.rds"))


##### AK #####
# Load data
kw_initial_ak <- read_csv(paste0(file_path, "Input/AK/filtretechange.csv"), 
                                  na = c("NULL", "", "...", -99, -999, -9999))

kw_ak <- kw_initial_ak %>% 
  # rename variables
  mutate(home_winter_id = as.factor(HomeWinterID),
         kw_date = ymd(ChangeDate),
         kw_hours = as.numeric(KWHours),
         area = "AK") %>% 
  select(home_winter_id, area, kw_date, kw_hours) %>%  
  filter(!is.na(kw_hours)) %>% 
  ungroup() %>% 
  arrange(home_winter_id, kw_date) 
  

# Save as RDS
write_rds(kw_ak, paste0(file_path, "Output/kw_ak.rds"))
```

# Join KW hour data from different areas
```{r}
file_path <- c("C:/Users/ethan.walker/Box/Ethan Walker UM/R/KidsAIR/")

kw_wmt <- read_rds(paste0(file_path, "Output/kw_wmt.rds"))
kw_nn <- read_rds(paste0(file_path, "Output/kw_nn.rds"))
kw_ak <- read_rds(paste0(file_path, "Output/kw_ak.rds"))

kids_kw <- rbind(kw_wmt, kw_nn, kw_ak) %>% 
  ungroup() %>% 
  arrange(area, home_winter_id, kw_date)

write_rds(kids_kw, paste0(file_path, "Output/kids_kw.rds"))
```

# Clean up all KW hour data
```{r}
file_path <- c("C:/Users/ethan.walker/Box/Ethan Walker UM/R/KidsAIR/")
kids_kw <- read_rds(paste0(file_path, "Output/kids_kw.rds"))
kids_linked_ids <- read_rds(paste0(file_path, "Output/kids_linked_ids_final.rds"))
treatments_masked <- read_csv(paste0(file_path, "Input/KidsAIRrnd_masked.csv"), na = "NULL") %>% 
  mutate(home = gsub(" ", "", x = home),
         home = gsub("_", "", x = home))


kids_kw_clean <- kids_kw %>% 
  left_join(kids_linked_ids, by = c("area", "home_winter_id")) %>%  
  filter(!is.na(home)) %>% 
  arrange(area, home_winter_id, kw_date) %>% 
  group_by(area, home_winter_id) %>% 
  mutate(kw_hours_total = sum(kw_hours))

summary(kids_kw_clean)

kw_summary <- kids_kw_clean %>% 
  select(-treatment_assigned, -treatment_actual) %>% 
  left_join(treatments_masked, by = "home") %>% 
  distinct(area, home, kw_hours_total) %>% 
  ungroup() %>% 
  #group_by(newtx) %>% 
  summarize(mean(kw_hours_total),
            sd(kw_hours_total),
            n(),
            min(kw_hours_total),
            median(kw_hours_total),
            max(kw_hours_total))
kw_summary

# Some homes/stoves were graded during both winters, typically when new photos were added
# Since photos were added in these cases, grades may have changed from Winter 1 to Winter 2
# We can't make the assumption that the stove was exactly the same for both winters,
# so it will be best to use the grade corresponding to each winter for analysis.

write_rds(kids_kw_clean, paste0(file_path, "Output/kids_kw_clean.rds"))
```

