---
title: "Kids stove grades and usage summary"
author: "Ethan Walker"
date: "Started 15 Jan 2020, Updated 25 March 2020"
output: pdf_document 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE, 
                      include = TRUE, warning = FALSE)
```

```{r, message=FALSE}
library(tidyverse)
library(readr)
library(readxl)
library(knitr)
library(lubridate)
jv_palette <- c("#330099","#CC0066","#FF6633", 
                 "#0099CC", "#FF9900","#CC6633",
                  "#FF3366", "#33CC99", "#33999")
```

```{r}
# Load data
stove_grades_clean <- read_rds("Output/stove_grades_clean.rds") 
stove_use_clean <- read_rds("Output/stove_use_clean.rds")
kids_linked_ids <- read_rds("Output/kids_linked_ids.rds") 
demographics_clean <- read_rds("Output/demographics_clean.rds")
#pm_clean <- read_rds("Output/pm_clean.rds")
```


```{r, eval=FALSE}
# Save this for potential future use

# Summarize factor vars
## Use this as a quick look at all vars
table_list <- stove_use_clean %>% 
  #filter(area == "WMT") %>% 
  filter(winter_id == 1 & treatment == "Placebo") %>%  
  select(-home_winter_id, -wood_cords, -wood_type_other,
         -home_id, -home, -treatment) 
lapply(table_list, table)
```


```{r}
## Look further into NA values? ##
stove_grade_summary <- stove_grades_clean %>% 
  #filter(winter_id == 1 & treatment == "Placebo") %>% 
  select(area, home, stove_grade, winter_id) %>% 
  #filter(!is.na(stove_grade)) %>% 
  group_by(area, winter_id, stove_grade) %>% 
  distinct(home) %>% 
  summarize(n()) %>% 
  filter(!is.na(stove_grade))
#kable(stove_grade_summary, align = "c")

stove_grades_total <- stove_grades_clean %>% 
  filter(!is.na(stove_grade)) %>% 
  filter(!is.na(home)) %>% 
  group_by(area, home) %>% 
  distinct(home, .keep_all = TRUE) %>% 
  select(area, home, stove_grade) %>% 
  arrange(area, home) 
```



```{r, eval=FALSE}
# Generate random sample of stoves to re-grade and validate grading methods

# 10% of homes from each area, earlier winters
# send new ID linked to new ID to Kathrene

random_sample_wmt <- stove_grades_clean %>% 
  select(area, home, stove_grade, winter_id) %>% 
  mutate(winter_id = as.factor(winter_id)) %>% 
  left_join(demographics_clean, c("area", "home", "winter_id")) %>% 
  mutate(cutoff_date = if_else(intervention_date < "2018-06-06", 1, 0)) %>% 
  filter(!is.na(stove_grade)) %>% 
  filter(!is.na(home)) %>% 
  filter(cutoff_date == 1) %>% 
  filter(area == "WMT") %>% 
  group_by(area, home) %>% 
  distinct(home, .keep_all = TRUE) %>% 
  select(area, home, home_winter_id, stove_grade, intervention_date) %>% 
  arrange(area, home) %>% 
  group_by(area) %>% 
  sample_n(17)
#write_csv(random_sample_wmt, "Output/random_sample_wmt.csv")

random_sample_nn <- stove_grades_clean %>% 
  select(area, home, stove_grade, winter_id) %>% 
  mutate(winter_id = as.factor(winter_id)) %>% 
  left_join(demographics_clean, c("area", "home", "winter_id")) %>% 
  mutate(cutoff_date = if_else(intervention_date < "2018-06-06", 1, 0)) %>% 
  filter(!is.na(stove_grade)) %>% 
  filter(!is.na(home)) %>% 
  filter(cutoff_date == 1) %>% 
  filter(area == "NN") %>% 
  group_by(area, home) %>% 
  distinct(home, .keep_all = TRUE) %>% 
  select(area, home, home_winter_id, stove_grade, intervention_date) %>% 
  arrange(area, home) %>% 
  group_by(area) %>% 
  sample_n(8)
#write_csv(random_sample_nn, "Output/random_sample_nn.csv")

random_sample_ak <- stove_grades_clean %>% 
  select(area, home, stove_grade, winter_id) %>% 
  mutate(winter_id = as.factor(winter_id)) %>% 
  left_join(demographics_clean, c("area", "home", "winter_id")) %>% 
  mutate(cutoff_date = if_else(intervention_date < "2018-06-06", 1, 0)) %>% 
  filter(!is.na(stove_grade)) %>% 
  filter(!is.na(home)) %>% 
  filter(cutoff_date == 1) %>% 
  filter(area == "AK") %>% 
  group_by(area, home) %>% 
  distinct(home, .keep_all = TRUE) %>% 
  select(area, home, home_winter_id, stove_grade, intervention_date) %>% 
  arrange(area, home) %>% 
  group_by(area) %>% 
  sample_n(5)
#write_csv(random_sample_ak, "Output/random_sample_ak.csv")
```


```{r, include=FALSE, eval=FALSE}
## 18 homes with grades from 2 winters
## 4 of the homes were assigned different grades in each winter
### Was there an upgrade/downgrade to the stove? Check for comments/notes.

multiple_grades <- stove_grades_clean %>% 
  select(area, home, stove_grade, winter_id) %>% 
  filter(winter_id == 1 | winter_id == 2) %>% 
  filter(!is.na(stove_grade)) %>%
  group_by(home) %>% 
  filter(n() > 1) %>% 
  arrange(home, winter_id)
kable(multiple_grades)
```


```{r, include=FALSE, eval=FALSE}
# Summarize numeric vars
stove_use_summary <- stove_use_clean %>% 
  filter(winter_id == 1 & treatment == "Placebo") %>% 
  group_by(area) %>% 
  summarize("N" = n(),
            "Mean Cords" = mean(wood_cords, na.rm = TRUE),
            "SD Cords" = sd(wood_cords, na.rm = TRUE),
            "Min Cords" = min(wood_cords, na.rm = TRUE), 
            "Median Cords" = median(wood_cords, na.rm = TRUE), 
            "Max Cords" = max(wood_cords, na.rm = TRUE))
kable(stove_use_summary, digits = 1, align = "c")

## Select specific var to assess individually/group by area
table(stove_use_clean$burn_level, stove_use_clean$area, useNA = "ifany")
table(stove_use_clean$wood_type, stove_use_clean$area, useNA = "ifany")
table(stove_use_clean$wood_collect, stove_use_clean$area, useNA = "ifany")
table(stove_use_clean$wood_collect_method, stove_use_clean$area, useNA = "ifany")
```

```{r}
stove_grade_filtered <- stove_grades_clean %>% 
  arrange(area, home, winter_id) %>% 
  group_by(home) %>% 
  mutate(stove_grade = if_else(is.na(stove_grade), lead(stove_grade), stove_grade)) %>% 
  ungroup()

stove_grade_plot <- stove_grade_filtered %>% 
  filter(winter_id == 1) %>% 
  select(area, stove_grade) %>% 
  filter(!is.na(stove_grade)) %>% 
  ggplot() +
    geom_bar(aes(stove_grade, fill = area)) +
    theme_minimal() +
    labs(title = "Stove grades") +
    theme(axis.text.x = element_text(size = 16, colour = "black", 
                                     angle = 40, vjust = 0.7, hjust = 0.7),
          axis.text.y = element_text(size = 16, colour = "black"),
          title = element_text(size = 18, colour = "black"),
          legend.text = element_text(size = 14, colour = "black"),
          legend.title = element_text(size = 16, colour = "black"),
          axis.title.y = element_blank(),
          axis.title.x = element_blank(),
          axis.line.x = element_line(colour = "black", size = 1.2), 
          axis.line.y = element_line(colour = "black", size = 1.2), 
          axis.ticks = element_blank(),
          panel.grid = element_blank()) +
    scale_fill_manual(values = jv_palette)
stove_grade_plot
```


```{r}
stove_use_data <- read_rds("Output/stove_use_clean.rds") %>% 
  mutate(wood_cords = as.factor(wood_cords),
         burn_level = factor(burn_level,
                             levels = c("No burning", "Light burning",
                                        "Average burning", "Heavy burning")))

stove_use_plot_function <- function(data, var, title_label, y_label) {
  
  stove_use_plot <- data %>% 
  filter(winter_id == 1) %>% 
  select(area, var) %>% 
  rename(plot_var = var) %>% 
  filter(!is.na(plot_var)) %>% 
  ggplot() +
    geom_bar(aes(plot_var, fill = area)) +
    theme_minimal() +
    theme(axis.text.x = element_text(size = 16, colour = "black", 
                                     angle = 40, vjust = 0.7, hjust = 0.7),
          axis.text.y = element_text(size = 16, colour = "black"),
          title = element_text(size = 20, colour = "black"),
          legend.text = element_text(size = 18, colour = "black"),
          legend.title = element_text(size = 18, colour = "black"),
          axis.title.y = element_text(size = 18, colour = "black"),
          axis.title.x = element_blank(),
          axis.line.x = element_line(colour = "black", size = 1.2), 
          axis.line.y = element_line(colour = "black", size = 1.2), 
          axis.ticks = element_blank(),
          panel.grid = element_blank()) +
    labs(title = title_label) +
    ylab(y_label) +
    scale_fill_manual(values = jv_palette)
  stove_use_plot
  
}

stove_use_plot_function(stove_use_data, "burn_level", "Burn level", "count")
stove_use_plot_function(stove_use_data, "wood_type", "Wood type", "count")
stove_use_plot_function(stove_use_data, "wood_collect", "Wood collection", "count")
stove_use_plot_function(stove_use_data, "wood_collect_method", "Wood collect method", "count")
stove_use_plot_function(stove_use_data, "wood_cords", "Wood cords burned", "count")
```


```{r, eval=FALSE}
#### Abstract/manuscript tables ####

# Filter for homes that have PM data


# 93 Winter 1 placebo homes have PM data
pm_homes_placebo <- pm_clean %>% 
  filter(winter_id == 1) %>% 
  filter(treatment == "Placebo") %>% 
  group_by(area, home) %>% 
  mutate(initial_obs = if_else(pm_datetime_new == first_datetime_new, 1, 0)) %>% 
  filter(initial_obs == 1) %>% 
  mutate(pm_home = "true") %>% 
  select(area, home, home_winter_id, pm_home) %>% 
  ungroup() %>% 
  arrange(area, home)

stove_use_filtered <- stove_use_clean %>% 
  # change to correct joining data of interest
  left_join(pm_homes_placebo, by = c("area", "home", "home_winter_id")) %>% 
  filter(pm_home == "true") %>% 
  filter(winter_id == 1) %>% 
  ungroup() %>% 
  arrange(area, home)

stove_grades_filtered <- stove_grades_clean %>% 
  # change to correct joining data of interest
  left_join(pm_homes_placebo, by = c("area", "home", "home_winter_id")) %>% 
  filter(pm_home == "true") %>% 
  filter(winter_id == 1) %>% 
  ungroup() %>% 
  arrange(area, home)
```


```{r, include=FALSE, eval=FALSE}
# Summarize numeric vars
kids_use <- stove_use_filtered %>%  
  #distinct(home, .keep_all = TRUE) %>%  
  group_by(area) %>% 
  summarize("Mean" = mean(wood_cords, na.rm = TRUE), 
            "SD" = sd(wood_cords, na.rm = TRUE),
            "min" = min(wood_cords, na.rm = TRUE), 
            "med" = median(wood_cords, na.rm = TRUE), 
            "max" = max(wood_cords, na.rm = TRUE))
kable(kids_use, digits = 1, align = "c")

# Summarize factor vars
alaska_use <- stove_use_filtered %>%  
  #distinct(home, .keep_all = TRUE) %>% 
  filter(area == "AK") %>% 
  group_by(wood_collect_method) %>% 
  summarize(n = n(), percent = (n()/10)*100)
  #summarize(n = n(), percent = (n()/60)*100)
alaska_use

navajo_use <- stove_use_filtered %>%  
  #distinct(home, .keep_all = TRUE) %>% 
  filter(area == "NN") %>% 
  group_by(wood_collect_method) %>% 
  summarize(n = n(), percent = (n()/23)*100)
  #summarize(n = n(), percent = (n()/138)*100)
navajo_use

montana_use <- stove_use_filtered %>%  
  #distinct(home, .keep_all = TRUE) %>% 
  filter(area == "WMT") %>% 
  group_by(wood_collect_method) %>% 
  summarize(n = n(), percent = (n()/60)*100)
  #summarize(n = n(), percent = (n()/360)*100)
montana_use

kids_use <- rbind(alaska_use, navajo_use, montana_use)
kable(kids_use)


# stove grade table
stove_grades_filtered <- stove_grades_clean %>% 
  # change to correct joining data of interest
  left_join(pm_homes_placebo, by = c("area", "home", "home_winter_id")) %>% 
  arrange(area, home, winter_id) %>% 
  group_by(home) %>% 
  mutate(stove_grade = if_else(is.na(stove_grade), lead(stove_grade), stove_grade)) %>% 
  filter(pm_home == "true") %>% 
  filter(winter_id == 1) %>%
  filter(!is.na(stove_grade)) %>% 
  ungroup() %>% 
  arrange(area, home)

table(stove_grades_filtered$stove_grade, stove_grades_filtered$area)
```

