---
title: "Kids SUMs Summary"
author: "Ethan Walker"
date: "Started 9 Jan 2020, Updated 7 Feb 2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE, 
                      include = TRUE, warning = FALSE)
```

```{r, message=FALSE}
library(tidyverse)
library(readr)
library(readxl)
library(knitr)
library(lubridate)
jv_palette <- c("#330099","#CC0066","#FF6633", 
                 "#0099CC", "#FF9900","#CC6633",
                  "#FF3366", "#33CC99", "#33999")
```

```{r}
# Load data
sums_clean <- read_rds("Output/sums_clean.rds")
pm_clean <- read_rds("Output/pm_clean.rds")

```

# Summary stats by area (winter)
```{r}
sums_summary <- sums_clean %>% 
  # group by: area, treatment, dtid, day_of_week, Sampling_day
  #filter(winter_id == 1 & treatment == "Placebo") %>% 
  filter(temp_c_sums <= 0) %>% 
  group_by(area, home, ibid) %>% 
  summarize("n" = n(),
            "Mean Temp" = mean(temp_c_sums, na.rm = TRUE), 
            "SD Temp" = sd(temp_c_sums, na.rm = TRUE),
            "Min Temp" = min(temp_c_sums, na.rm = TRUE), 
            "Median Temp" = median(temp_c_sums, na.rm = TRUE),
            "Max Temp" = max(temp_c_sums, na.rm = TRUE)) %>% 
  select(-area) %>% 
  t() 

kable(sums_summary, col.names = c("Alaska", "Navajo", "Montana"), digits = 1, align = "c")


sums_summary <- sums_clean %>% 
  # group by: area, treatment, dtid, day_of_week, Sampling_day
  filter(winter_id == 1 & treatment == "Placebo") %>% 
  filter(temp_c_sums > 0) %>% 
  group_by(area) %>% 
  summarize("n" = n(),
            "Mean Temp" = mean(temp_c_sums, na.rm = TRUE), 
            "SD Temp" = sd(temp_c_sums, na.rm = TRUE),
            "Min Temp" = min(temp_c_sums, na.rm = TRUE), 
            "Median Temp" = median(temp_c_sums, na.rm = TRUE),
            "Max Temp" = max(temp_c_sums, na.rm = TRUE)) %>% 
  select(-area) %>% 
  t() 

kable(sums_summary, col.names = c("Alaska", "Navajo", "Montana"), digits = 1, align = "c")
```


# Boxplots for SUMs temp (C) by study area - Winter 1
```{r, fig.height=6, fig.width=5}
boxplots_kids_sums <- sums_clean %>%
  filter(winter_id == 1 & treatment == "Placebo") %>% 
  ggplot(aes(area, temp_c_sums)) +
    geom_boxplot(aes(size = 1), lwd = 1.2, colour = "black", 
               fatten = 1, outlier.size = 1.5, width = 0.35) +
    stat_summary(fun.y=mean, geom="point", shape=17, size=3, color="red") +
    theme_minimal() +
    ylim(-50, 100) +
    #geom_hline(yintercept = 50, color = "red", size = 1.2) +
    labs(y = "Temperature (degrees C)") +
    #labs(aes(x = "", y = paste("48-hour indoor PM "[2.5], " (", mu, g/m^3, ")"))) +
    theme(axis.text.x = element_text(size = 16, colour = "black"),
          axis.text.y = element_text(size = 16, colour = "black"),
          axis.title.y = element_text(size = 16,
                                      margin = margin(t = 0, r = 20, b = 0, l = 0)),
          axis.title.x = element_blank(),
          axis.line.x = element_line(colour = "black", size = 1.2), 
          axis.line.y = element_line(colour = "black", size = 1.2), 
          axis.ticks = element_blank())
boxplots_kids_sums
```

# Boxplots for SUMs temp (C) by study area - Winter 2
```{r, fig.height=6, fig.width=5}
boxplots_kids_sums <- sums_clean %>%
  filter(winter_id == 2) %>% 
  ggplot(aes(area, temp_c_sums)) +
    geom_boxplot(aes(size = 1), lwd = 1.2, colour = "black", 
               fatten = 1, outlier.size = 1.5, width = 0.35) +
    stat_summary(fun.y=mean, geom="point", shape=17, size=3, color="red") +
    theme_minimal() +
    ylim(-50, 100) +
    #geom_hline(yintercept = 50, color = "red", size = 1.2) +
    labs(y = "Temperature (degrees C)") +
    #labs(aes(x = "", y = paste("48-hour indoor PM "[2.5], " (", mu, g/m^3, ")"))) +
    theme(axis.text.x = element_text(size = 16, colour = "black"),
          axis.text.y = element_text(size = 16, colour = "black"),
          axis.title.y = element_text(size = 16,
                                      margin = margin(t = 0, r = 20, b = 0, l = 0)),
          axis.title.x = element_blank(),
          axis.line.x = element_line(colour = "black", size = 1.2), 
          axis.line.y = element_line(colour = "black", size = 1.2), 
          axis.ticks = element_blank())
boxplots_kids_sums
```

# Filter for homes that have PM data
```{r}
# 93 Winter 1 placebo homes have PM data
pm_homes_placebo <- pm_clean %>% 
  filter(winter_id == 1) %>% 
  filter(treatment == "Placebo") %>% 
  group_by(area, home) %>% 
  mutate(initial_obs = if_else(pm_datetime_new == first_datetime_new, 1, 0)) %>% 
  filter(initial_obs == 1) %>% 
  mutate(pm_home = "true") %>% 
  select(area, home, home_winter_id, pm_home, pm_datetime_new, pm) %>% 
  ungroup() %>% 
  arrange(area, home)

pm_homes_placebo_date <- pm_clean %>% 
  filter(winter_id == 1) %>% 
  filter(treatment == "Placebo") %>% 
  mutate(pm_home = "true") %>% 
  select(area, home, home_winter_id, pm_home, pm_datetime_new, pm) %>% 
  separate(pm_datetime_new, c("sample_date", "sample_time"), sep = " ", remove = FALSE) %>% 
  mutate(sample_date = ymd(sample_date)) %>% 
  group_by(area, home) %>% 
  distinct(sample_date, .keep_all = TRUE) %>% 
  ungroup() %>% 
  arrange(area, home)

sums_filtered <- sums_clean %>% 
  # change to correct joining data of interest
  left_join(pm_homes_placebo, by = c("area", "home", "home_winter_id")) %>% 
  filter(pm_home == "true") %>% 
  filter(winter_id == 1) %>% 
  ungroup() %>% 
  arrange(area, home) 

sums_filtered_date <- sums_clean %>% 
  mutate(sample_date = date_sums,
         sample_date = ymd(sample_date)) %>% 
  # change to correct joining data of interest
  left_join(pm_homes_placebo_date, by = c("area", "home", "home_winter_id", "sample_date")) %>% 
  filter(pm_home == "true") %>% 
  filter(winter_id == 1) %>% 
  ungroup() %>% 
  arrange(area, home)
```

# Function for calculating heating events using specified threshold temps
## Also specify the "gap" time between events
```{r}
thresholds_function <- function(data, temp, gap) {

thresholds <- data %>% 
  mutate(datetime_sums = ymd_hms(datetime_sums)) %>% 
  group_by(area, home, winter_id) %>%
  mutate(threshold_temp = if_else(temp_c_sums >= temp, 1, 0),
         threshold_temp_event = if_else(threshold_temp == 1 & lag(threshold_temp) == 0, 
                                        "start", "Temp < threshold"),
         threshold_temp_event = if_else(is.na(threshold_temp_event), "start", threshold_temp_event),
         threshold_temp_event = if_else(threshold_temp == 1 & threshold_temp_event == "Temp < threshold",
                                      "Temp >= threshold", threshold_temp_event),
         threshold_temp_event = if_else(threshold_temp_event == "Temp >= threshold" &
                                      lead(threshold_temp_event) == "Temp < threshold", 
                                      "event", threshold_temp_event)) %>% 
  filter(threshold_temp_event == "event" | threshold_temp_event == "start") %>% 
  mutate(time_sums = as.character(time_sums),
         date_sums = as.character(date_sums)) %>%  
  spread(threshold_temp_event, datetime_sums) %>% 
  mutate(event = lead(event),
         time_diff_min = (event - start),
         time_diff_min = as.numeric(time_diff_min/60)) %>% 
  filter(!is.na(time_diff_min)) %>% 
  mutate(next_event = (lead(start)-event),
         next_event = as.numeric(next_event)/3600,
         event2 = if_else(next_event <= gap, lead(event), event),
         time_diff_min2 = (event - start),
         time_diff_min2 = as.numeric(time_diff_min2/60),
         event3 = if_else(next_event <= gap & lead(next_event) <= gap, lead(event, 2), event2),
         time_diff_min3 = (event3 - start),
         time_diff_min3 = as.numeric(time_diff_min3/60)) %>% 
  distinct(event3, .keep_all = TRUE) %>% 
  mutate(time_diff_min4 = (event3 - start),
         time_diff_min4 = as.numeric(time_diff_min4/60)) %>% 
  filter(!is.na(time_diff_min4)) %>% 
  group_by(area, home, winter_id, date_sums) %>% 
  summarize(n = n(), mean_time = mean(time_diff_min4))

thresholds_by_home <<- thresholds %>% 
  group_by(home) %>% 
  summarize("Mean events per day" = round(mean(n), digits = 2),
            "SD events per day" = round(sd(n), digits = 2),
            "Mean event length (min)" = round(mean(mean_time), digits = 0),
            "SD event length (min)" = round(sd(mean_time), digits = 2))
thresholds_by_home

thresholds_by_area <<- thresholds %>% 
  group_by(area) %>% 
  summarize("Mean events per day" = round(mean(n), digits = 2),
            "SD events per day" = round(sd(n), digits = 2),
            "Mean event length (min)" = round(mean(mean_time), digits = 0),
            "SD event length (min)" = round(sd(mean_time), digits = 2))
thresholds_by_area

}

thresholds_function(sums_filtered_date, 25, 1.5)
thresholds_function(sums_filtered_date, 27, 1.5)
thresholds_function(sums_filtered_date, 30, 1.5)
```


# Function to look at percentage of time spent above a threshold
```{r}
thresholds_percent <- function(data, temp) {

thresholds <- data %>% 
  group_by(area, home, winter_id, date_sums) %>%
  mutate(threshold_temp = if_else(temp_c_sums >= temp, 1, 0)) %>% 
  summarize(percent_above = sum(threshold_temp)/n()*100) %>% 
  group_by(area) %>% 
  summarize("% time/day > threshold" = round(mean(percent_above), digits = 2))
thresholds

}

thresholds_percent(sums_filtered_date, 25)
thresholds_percent(sums_filtered_date, 27)
thresholds_percent(sums_filtered_date, 30)
```

