---
title: "KidsAIR: WMT addresses"
author: "Ethan Walker"
date: "Started 3 April 2020, Updated 30 April 2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE, 
                      include = TRUE, warning = FALSE, message = FALSE,
                      fig.height = 6, fig.width = 8)
```

```{r, message=FALSE}
library(tidyverse)
library(readxl)
library(naniar)
library(lubridate)
library(broom)
library(broom.mixed)
library(zoo)
library(lme4)
library(lmerTest)
library(ggmap)
library(maps)
library(tigris)
jv_palette <- c("#330099","#CC0066","#FF6633", 
                 "#0099CC", "#FF9900","#CC6633",
                  "#FF3366", "#33CC99", "#33999")
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", 
               "#0072B2", "#D55E00", "#CC79A7")
```


```{r}
input_path <- c("C:/Users/ethan.walker/Box/Ethan Walker UM/R/KidsAIR/")

wmt_addresses <- read_xlsx(paste0(input_path, "Input/WMT/wmt_addresses.xlsx"))

register_google(key = "")
```


```{r}
addresses_new <- wmt_addresses %>% 
  unite(address, c("Address", "City", "Zip"), sep = ", ", remove = FALSE) %>% 
  select(Home, address) 
```


```{r}
addresses_geocoded <- addresses_new %>% 
  mutate_geocode(location = address, output = "more",
                              source = "google")
```


```{r}
wmt_map <- map_data("state") %>% 
  filter(region == "montana")


wmt_homes <- addresses_geocoded %>% 
  ggplot() +
    geom_polygon(data=wmt_map, aes(x=long, y=lat, group=group), 
               colour="black", fill = "azure", size = 1.2) +
    geom_point(data=addresses_geocoded, 
             aes(lon, lat), size = 3) +
    theme_void() +
    labs(title = "WMT Homes Mapped", subtitle = "Geocoded from addresses") 
wmt_homes
```

